/* Opt-in native WKWebView interaction probe. Uses a caller-owned fixture,
   stays hidden and never requests permissions or writes system calendar data. */
(async()=>{
  document.documentElement.dataset.renderDiagnostic='true';
  const report={phase:'complete',checks:[],errors:[],actualEventKitWriteTested:false};
  const check=(ok,label)=>{report.checks.push({label,ok:!!ok});if(!ok)throw Error(label);};
  const wait=async fn=>{const until=Date.now()+40000;while(!fn()){if(Date.now()>until)throw Error('Native interaction initialization timed out');await new Promise(resolve=>setTimeout(resolve,100));}};
  try{
    await window.__TOUDI_DESKTOP_READY__;await wait(()=>serverMode&&data.length&&workspaceRefreshSnapshots.size>=7);
    switchView('table');
    check(!document.querySelector('#deliverySearchEntry,#settingsShortcut,#managementEntry'),'native global entries are not duplicated');
    check(document.querySelectorAll('.module-nav [data-module="settings"]').length===1,'native settings stay in the sidebar');
    const themeRect=document.querySelector('.sb-footer .theme-toolbar').getBoundingClientRect(),toolbarRect=document.getElementById('dashboardToolbar').getBoundingClientRect();
    report.navigation={themeBottom:themeRect.bottom,toolbarHeight:toolbarRect.height};
    check(themeRect.height>0&&themeRect.bottom<=innerHeight&&toolbarRect.height>0&&toolbarRect.height<=30,'native appearance shortcut and compact result row fit the viewport');
    check(document.getElementById('workspaceUpdatesButton').hidden,'native idle update status stays hidden');
    check(document.getElementById('storageBadge').hidden,'native healthy connection has no permanent badge');
    check([...document.querySelectorAll('.theme-mode-control button')].map(el=>el.getAttribute('aria-label')).join('|')==='浅色|深色|跟随电脑'&&!document.getElementById('themeMenu'),'native appearance uses three direct icon choices');
    for(const mode of ['dark','system','light']){
      document.querySelector('.theme-mode-control [data-theme="'+mode+'"]').click();
      check(workspace.theme===mode&&document.querySelector('.theme-mode-control [aria-pressed="true"]').dataset.theme===mode,'native appearance choice '+mode+' updates the selected control');
    }
    const openStarted=performance.now();await openManagement('records');
    report.recordDialog={openMs:performance.now()-openStarted,elements:document.querySelectorAll('#managementOverlay *').length};
    check(!document.querySelector('.management-list')&&report.recordDialog.elements<120&&document.querySelector('[data-mfield="名称"]').value==='','native record entry stays bounded with thousands of records');
    check([...document.querySelectorAll('#managementTools [role="tab"]')].map(el=>el.textContent).join('|')==='新增记录|导入 / 导出'&&document.getElementById('managementSubmit').textContent==='保存记录','native new-record flow needs only save');
    document.getElementById('recordTransferTab').click();
    check(!!document.querySelector('#managementBody input[type="file"]')&&!/导出完整规范|导出当前草稿|交给 Agent|检查与预览/.test(document.getElementById('managementOverlay').textContent),'native transfer task has clearly named import and export');
    closeManagement();
    const input=document.getElementById('searchInput'),totals=document.getElementById('statsBar').textContent;
    input.value='合成产品';input.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true,inputType:'insertCompositionText'}));
    check(searchQuery==='合成产品'&&getFiltered().length===1,'native IME input filters immediately');
    check(document.getElementById('statsBar').textContent===totals,'stage totals remain fixed');
    input.value='';input.dispatchEvent(new Event('search',{bubbles:true}));check(getFiltered().length===data.length,'native search clear restores results');
    switchView('schedule');await window.toudiSchedule.show();await wait(()=>document.querySelector('#scheduleCalendar [data-date]'));
    document.querySelector('[data-schedule="new"]').click();
    const editor=document.getElementById('scheduleForm');
    editor.elements.startTime.value='14:15';editor.elements.endTime.value='15:45';editor.elements.startTime.dispatchEvent(new Event('input',{bubbles:true}));
    const canvas=document.getElementById('scheduleCalendar');
    report.preview={start:canvas.dataset.previewStart,end:canvas.dataset.previewEnd};
    check(!!report.preview.start&&!!report.preview.end,'native editor keeps a time preview');
    editor.elements.title.value='完整的合成事项';editor.elements.title.dispatchEvent(new Event('input',{bubbles:true}));
    check(canvas.dataset.previewStart===report.preview.start&&canvas.dataset.previewEnd===report.preview.end,'preview persists while editing');
    const query=document.getElementById('scheduleCompanyQuery'),started=performance.now();
    query.value='目标城市';query.dispatchEvent(new Event('input',{bubbles:true}));
    const choices=[...document.querySelectorAll('#scheduleCompanyList [role="option"]')];report.companyLookupMs=performance.now()-started;
    check(choices.length===1,'native company search narrows the fixture');choices[0].click();
    check(!!editor.elements.companyKey.value&&editor.elements.title.value==='完整的合成事项','company binding preserves current editor');
    query.value='';query.dispatchEvent(new Event('input',{bubbles:true}));check(document.querySelectorAll('#scheduleCompanyList [role="option"]').length<=20,'native company list stays bounded');
    document.querySelector('[data-schedule="cancel"]').click();check(!canvas.dataset.previewStart&&window.toudiSchedule.get().events.length===0,'cancel clears preview without creating an event');
    report.nativeStatus=await window.toudiDesktop.calendar('status');check(report.nativeStatus.supported,'native EventKit status bridge');
    // Exercise synchronization policy in WKWebView without writing system events.
    const realCalendar=window.toudiDesktop.calendar,calls=[];
    window.toudiDesktop.calendar=async(action,request)=>{
      if(action==='status')return {supported:true,authorization:'fullAccess'};
      if(action==='calendars')return {supported:true,authorization:'fullAccess',calendars:[{id:'synthetic-calendar',title:'合成日历'}]};
      calls.push(request);return {supported:true,authorization:'fullAccess',results:request.items.map(item=>({id:item.id,ok:true,operation:item.status==='cancelled'?'deleted':'updated'}))};
    };
    const syncButton=document.getElementById('scheduleSyncButton');check(!!syncButton,'native standalone sync control');syncButton.click();
    await wait(()=>document.getElementById('scheduleNativeCalendar'));
    document.getElementById('scheduleNativeCalendar').value='synthetic-calendar';document.querySelector('[data-schedule="enable-sync"]').click();
    await wait(()=>window.toudiSchedule.get().calendar.syncAll&&!syncButton.disabled);
    check(window.toudiSchedule.get().calendar.enabled,'native connection enables whole-schedule policy');
    document.querySelector('[data-schedule="new"]').click();
    check(!document.querySelector('[name="syncToCalendar"]'),'native editor has no per-event sync checkbox');
    const syncEditor=document.getElementById('scheduleForm');syncEditor.elements.title.value='合成自动同步事项';syncEditor.elements.title.dispatchEvent(new Event('input',{bubbles:true}));
    syncEditor.requestSubmit();await wait(()=>calls.some(call=>call.items.some(item=>item.title==='合成自动同步事项'))&&!syncButton.disabled);
    const saved=window.toudiSchedule.get().events[0];check(!saved.syncToCalendar,'native new event syncs without a legacy flag');
    switchView('schedule');document.querySelector('[data-schedule-mode="agenda"]').click();
    document.querySelector('[data-schedule-id]').click();document.querySelector('[data-schedule="delete"]').click();
    await wait(()=>calls.some(call=>call.items.some(item=>item.id===saved.id&&item.status==='cancelled'))&&!syncButton.disabled);
    check(window.toudiSchedule.get().events[0].status==='cancelled','native cancellation keeps tombstone and synchronizes');
    window.toudiDesktop.calendar=realCalendar;
    switchView('table');const detailRow=data.find(row=>row['岗位']==='合成产品岗位')||data[0];showDetail(detailRow._idx);
    await wait(()=>!document.getElementById('detailSchedule').textContent.includes('正在读取'));
    check(!document.querySelector('#detailLead [role="tab"]')&&document.querySelectorAll('#detailContent>.detail-section').length===3,'native detail uses continuous sections');
    check(document.querySelectorAll('[data-material]').length===3&&!document.getElementById('detailNotes').open,'native related materials are visible and long notes start collapsed');
    check([...document.querySelectorAll('[data-material]')].map(el=>el.textContent.trim()).join('|')==='岗位探查|面试准备|面试复盘'&&!document.querySelector('#detailMaterials small,.detail-secondary-links'),'native company material links have no counters or global shortcuts');
    const status=document.getElementById('detailStatus'),statusRect=status.getBoundingClientRect(),arrowRect=document.querySelector('.detail-status-control>svg').getBoundingClientRect();
    report.statusControl={height:statusRect.height,arrowOffset:Math.abs(arrowRect.y+arrowRect.height/2-statusRect.y-statusRect.height/2),appearance:getComputedStyle(status).appearance,buttonHeights:[...document.querySelectorAll('.detail-progress-row button')].map(el=>el.getBoundingClientRect().height)};
    check(report.statusControl.height===34&&report.statusControl.buttonHeights.every(height=>height===34)&&report.statusControl.arrowOffset<.5&&report.statusControl.appearance==='none','native status selector has consistent dimensions and a centered arrow');
    check(document.querySelector('#detailNotes>summary').textContent.trim()==='跟进记录','native follow-up disclosure shows only its action label');
    check(document.querySelectorAll('#detailNotes>.detail-disclosure,#detailSourceInfo>.detail-disclosure').length===2,'native detail disclosures share the same visual control');
    check(document.querySelector('.detail-entry-actions>button').textContent==='添加日程','native schedule action describes editing a proposal');
    document.getElementById('detailNotes').open=true;document.getElementById('researchNote').value='完整的合成未保存记录';
    await openApplicationMaterial(detailRow._idx,'prep');check(view==='qbank'&&qbMode==='company','native preparation link navigates to its real module');
    switchView('table');showDetail(detailRow._idx);check(document.getElementById('researchNote').value==='完整的合成未保存记录','native navigation preserves unsaved follow-up text');
    const eventCount=window.toudiSchedule.get().events.length;
    document.querySelector('.detail-entry-actions>button').click();await wait(()=>document.getElementById('scheduleForm'));
    check(document.getElementById('scheduleForm').elements.companyKey.value===detailRow._key&&window.toudiSchedule.get().events.length===eventCount,'native add schedule binds the company without creating an event');
    document.querySelector('[data-schedule="cancel"]').click();switchView('table');showDetail(detailRow._idx);
    document.getElementById('researchNote').value=detailRow._researchNote||'';document.getElementById('detailNotes').open=false;
    await wait(()=>!document.getElementById('detailSchedule').textContent.includes('正在读取'));
    await new Promise(resolve=>setTimeout(resolve,300));
    const modal=document.querySelector('#detailModal .modal'),modalRect=modal.getBoundingClientRect(),body=document.getElementById('detailContent');
    report.detail={width:modalRect.width,height:modalRect.height,opacity:getComputedStyle(modal).opacity,bodyHeight:body.clientHeight,sections:document.querySelectorAll('#detailContent>.detail-section').length};
    check(report.detail.width>400&&report.detail.height>300&&Number(report.detail.opacity)===1&&report.detail.bodyHeight>0,'native recruitment detail has settled visible geometry');
    report.version=window.toudiDesktop.version;report.records=data.length;
    report.errors=(window.__TOUDI_RENDER_ERRORS__||[]).filter(error=>!String(error).includes('ResizeObserver loop completed'));
    check(report.errors.length===0,'native runtime has no JavaScript errors');
  }catch(error){report.phase='failed';report.failure=String(error);}
  await window.__TAURI__.core.invoke('native_render_report',{report});
})();
