'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),os=require('node:os');
const {chromium}=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const item=(label,html)=>`<div class="ant-row ant-form-item"><div class="ant-form-item-label"><label>${label}<span class="labelRequired">*</span></label></div><div class="ant-form-item-control-wrapper"><div class="ant-form-item-control"><span class="ant-form-item-children">${html}</span></div></div></div>`;
const select=(id,choices)=>`<div class="ant-select"><div id="${id}" role="combobox" class="ant-select-selection" aria-controls="menu-${id}" aria-expanded="false" data-choices='${JSON.stringify(choices)}'><div class="ant-select-selection__rendered"><div class="ant-select-selection__placeholder">请选择</div><input class="ant-select-search__field" style="display:none"></div></div></div>`;
const fixture=`<title>合成招聘表单</title><form><div class="form-cell"><div class="tit-wrap"><p>个人基本信息</p></div><div class="form-cell-inner">${item('姓名','<input placeholder="请填写姓名">')}${item('体重（KG）','<input placeholder="Kg">')}${item('性别','<div class="ant-radio-group"><label><input type="radio" value="opaque-male">男</label><label><input type="radio" value="opaque-female">女</label></div>')}${item('出生日期','<span class="ant-calendar-picker"><input readonly placeholder="请选择出生日期"></span>')}${item('最高学历',select('degree',['大学本科','硕士研究生']))}${item('最高学历毕业时间','<div class="cascader-plugins-wrap">'+select('year',['2026年','2027年'])+select('month',['5月','6月'])+'</div>')}${item('最高学历毕业院校',select('school',['合成本科学院','合成研究生大学']))}${item('籍贯','<div class="cascader-plugins-wrap">'+select('province',['江苏省','浙江省'])+select('city',['苏州市','杭州市'])+'</div>')}${item('联系电话','<input placeholder="请填写联系电话">')}${item('紧急联系人','<input placeholder="请填写紧急联系人">')}${item('紧急联系电话','<input placeholder="请填写紧急联系电话">')}${item('已通过的英语等级证书',select('cet',['大学英语四级考试','大学英语六级考试']))}${item('英语等级成绩','<input placeholder="请填写英语等级成绩">')}</div></div><div class="form-cell"><div class="tit-wrap"><p>教育背景</p></div><div class="form-cell-inner">${item('开始时间','<span class="ant-calendar-picker"><input readonly placeholder="请选择开始时间"></span>')}${item('结束时间','<span class="ant-calendar-picker"><input readonly placeholder="请选择结束时间"></span>')}${item('学校名称','<input placeholder="请填写学校名称">')}${item('专业课程','<textarea placeholder="请填写专业课程"></textarea>')}</div></div><button type="submit">提交</button></form>`;
const facts=[];function f(module,rid,label,value,more={}){facts.push({key:[module,rid,label].join('.'),module,recordId:rid,recordLabel:rid,label,value,...more});}
f('personal','self','姓名','合成同学');f('personal','self','体重kg','65');f('personal','self','性别','男');f('personal','self','出生日期','2002-03-01',{precision:'day'});f('personal','self','最高学历','硕士研究生');f('personal','self','籍贯','浙江省杭州市西湖区');f('personal','self','手机','13800000001');f('personal','self','紧急联系人姓名','合成联系人');f('personal','self','紧急联系人手机','13800000002');
for(const [rid,level,school,start,end] of [['bachelor','大学本科','合成本科学院','2020-10-01','2024-06-30'],['master','硕士研究生','合成研究生大学','2024-09-01','2027-06-30']]){f('education',rid,'学历',level);f('education',rid,'学校',school);f('education',rid,'开始日期',start,{precision:'day'});f('education',rid,'结束日期',end,{precision:'day'});f('education',rid,'主修课程','课程一、课程二。完整原文。');}
for(const [rid,name,score] of [['cet4','大学英语四级考试','500'],['cet6','大学英语六级考试','550']]){f('language',rid,'证书类型',name);f('language',rid,'考试成绩',score);}
const pack={schemaVersion:1,profiles:[{id:'general',label:'合成资料'}],facts,rules:[]};let browser;
(async()=>{browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://synthetic.invalid/**',r=>r.fulfill({contentType:'text/html;charset=utf-8',body:fixture}));await page.goto('https://synthetic.invalid/form');
await page.evaluate(()=>{window.submits=0;document.querySelector('form').addEventListener('submit',e=>{e.preventDefault();window.submits++});for(const box of document.querySelectorAll('[role="combobox"]')){const menu=document.createElement('div');menu.id=box.getAttribute('aria-controls');menu.className='ant-select-dropdown';menu.style.display='none';menu.innerHTML=JSON.parse(box.dataset.choices).map(v=>`<div role="option">${v}</div>`).join('');document.body.append(menu);box.onclick=()=>{for(const m of document.querySelectorAll('.ant-select-dropdown'))m.style.display='none';menu.style.display='block';box.setAttribute('aria-expanded','true');};for(const option of menu.children)option.onclick=()=>{let selected=box.querySelector('.ant-select-selection-selected-value');if(!selected){selected=document.createElement('span');selected.className='ant-select-selection-selected-value';box.querySelector('.ant-select-selection__rendered').append(selected);}selected.textContent=option.textContent;menu.style.display='none';box.setAttribute('aria-expanded','false');};box.onkeydown=e=>{if(e.key==='Escape'){menu.style.display='none';box.setAttribute('aria-expanded','false');}};}for(const input of document.querySelectorAll('.ant-calendar-picker input'))input.onclick=()=>{const layer=document.createElement('div');layer.className='ant-calendar-picker-container';layer.innerHTML='<input class="ant-calendar-input">';document.body.append(layer);const edit=layer.querySelector('input');edit.onkeydown=e=>{if(e.key==='Enter'){input.value=edit.value;layer.remove();}};};});
for(const file of ['assets/form-adapters.js','assets/form-engine.js','browser-extension/filling-aliases.js','browser-extension/filling-core.js'])await page.addScriptTag({path:path.resolve('app',file)});
const result=await page.evaluate(async pack=>{const E=TouDiFormEngine,C=TouDiFillingCore,p=C.profile(C.validatePack(pack));const scan=await E.scan(),cold=C.plan(p,scan);const edu=cold.groups.find(g=>g.module==='education');const plan=C.plan(p,scan,{},new Date(),{},{[edu.groupId]:'master'});if(plan.rows.some(r=>r.status!=='ready'))throw Error(JSON.stringify(plan.rows));const list=await E.inspectOptions({fingerprint:scan.fingerprint,fieldIds:[scan.fields.find(f=>f.label==='最高学历').id]});const after=await E.scan();if(scan.fingerprint!==after.fingerprint)throw Error('inspection changed fingerprint');const report=await E.apply(C.confirm(plan,plan.rows.map(r=>r.fieldId)));return {scan,cold,plan,list,report,after:await E.scan(),submits:window.submits};},pack);
assert.equal(result.scan.platforms[0].id,'ant-design');assert.equal(result.scan.fields.length,17);assert(result.scan.fields.every(f=>f.label&&!f.unsupported));assert.equal(result.cold.statusCounts.ambiguous,4);assert.equal(result.list.items[0].options.length,2);assert.equal(result.report.summary.verified,17,JSON.stringify(result.report));assert.equal(result.submits,0);assert.equal(result.plan.rows.find(r=>r.label==='最高学历毕业院校').value,'合成研究生大学');assert.equal(result.plan.rows.find(r=>r.label==='英语等级成绩').value,'550');assert.equal(result.after.fields.find(r=>r.label==='籍贯').value,'浙江省/杭州市');assert.deepEqual(errors,[]);
const phone=await page.getByPlaceholder('请填写联系电话').inputValue(),emergency=await page.getByPlaceholder('请填写紧急联系电话').inputValue();assert.equal(phone,'13800000001');assert.equal(emergency,'13800000002');
// A wrong menu or a duplicated option must never be chosen.
await page.evaluate(()=>{document.querySelector('#menu-degree').insertAdjacentHTML('beforeend','<div role="option">硕士研究生</div>');document.querySelector('#degree .ant-select-selection-selected-value').textContent='大学本科';});const failure=await page.evaluate(async pack=>{const E=TouDiFormEngine,C=TouDiFillingCore,s=await E.scan(),p=C.plan(C.profile(C.validatePack(pack)),s);const r=p.rows.find(r=>r.label==='最高学历');return E.apply(C.confirm(p,[r.fieldId],[r.fieldId]));},pack);assert.equal(failure.results[0].reason,'option-not-unique');assert.equal(await page.locator('#degree .ant-select-selection-selected-value').innerText(),'大学本科');await page.setContent('<fieldset><legend>个人信息</legend><input placeholder="请填写姓名"><input placeholder="请填写身高（CM）"><div class="ant-form-item"><div class="ant-form-item-row"><div class="ant-form-item-label"><label>民族</label></div><div><input placeholder="输入内容"></div></div></div></fieldset>');for(const file of ['assets/form-adapters.js','assets/form-engine.js'])await page.addScriptTag({path:path.resolve('app',file)});const generic=await page.evaluate(()=>TouDiFormEngine.scan());assert.deepEqual(generic.fields.map(f=>f.label),['姓名','身高（CM）','民族']);assert(generic.fields.every(f=>f.module==='personal'));console.log('PASS Ant form: 17 fields, title/module/record binding, native text/radio, scoped select and menu inspection, readonly calendar, split year/month, linked province/city, emergency identity, CET record consistency, exact readback, no submit, duplicate option preserves value, zero page errors');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close();});
