'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{webcrypto}=require('node:crypto');
const root=path.join(__dirname,'../app/browser-extension'),local={},session={};let listener,resolveModel,modelCalls=0,currentValue='',shape='shape-1',reject=false;
function storage(data){return {async get(key){return {[key]:structuredClone(data[key])};},async set(value){Object.assign(data,structuredClone(value));},async remove(keys){for(const k of Array.isArray(keys)?keys:[keys])delete data[k];},async setAccessLevel(){}};}
const context={structuredClone,crypto:webcrypto,TextEncoder,URL,console,setTimeout,clearTimeout,chrome:{storage:{local:storage(local),session:storage(session)},runtime:{getManifest:()=>({version:'fixture-version'}),getURL:p=>'chrome-extension://fixture/'+p,onMessage:{addListener(fn){listener=fn}},id:'fixture'},tabs:{query:async()=>[{id:1,url:'https://fixture.invalid/application?private=ignored'}]}}};vm.createContext(context);context.importScripts=(...names)=>{for(const n of names)vm.runInContext(fs.readFileSync(root+'/'+n,'utf8'),context)};vm.runInContext(fs.readFileSync(root+'/worker.js','utf8'),context);

let scans=0;context.fixtureEngine=async()=>{scans++;throw Error('copy must not scan')};vm.runInContext('engine=fixtureEngine',context);
const send=m=>new Promise((resolve,reject)=>listener(m,{id:'fixture',url:'chrome-extension://fixture/popup.html'},r=>r.error?reject(Error(r.error)):resolve(r.value)));
(async()=>{await send({op:'profile-save',base:null,pack:{schemaVersion:1,profiles:[{id:'general',label:'合成一版'},{id:'other',label:'合成另一版'}],rules:[],facts:[{key:'name',module:'personal',label:'姓名',value:'合成姓名',profiles:['general']},{key:'role',module:'campus-role',label:'职务',value:'合成任职',recordId:'c',recordLabel:'合成组织',profiles:['general']},{key:'other',module:'campus-role',label:'职务',value:'另一版职务',recordId:'o',recordLabel:'另一版组织',profiles:['other']}]}});
 const a=await send({op:'copy-library',profile:'general'});assert.equal(a.records.length,2);assert(a.records.some(r=>r.facts.some(f=>f.value==='合成姓名')));assert(a.records.some(r=>r.text==='合成组织\n职务：合成任职'));assert(!JSON.stringify(a).includes('另一版'));
 const b=await send({op:'copy-library',profile:'other'});assert.equal(b.records.length,1);assert(b.records[0].text.includes('另一版职务'));assert.equal(scans,0);await assert.rejects(()=>send({op:'copy-library',profile:'unknown'}));console.log('PASS copy library worker: no scan/page access, explicit selected version, self-use sensitive values and labelled complete record payload');
})().catch(e=>{console.error(e);process.exitCode=1});
