'use strict';
// Browser plugin not available. Isolated fixture only; real Chrome observations use CUA.
// UI flow: library tab -> continuous scroll -> directory anchors -> exact full-text copy -> bulk fill modes.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
let pw;try{pw=require('playwright')}catch(_){pw=require(process.env.TOUDI_PLAYWRIGHT_MODULE || path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'))}
const root=path.resolve(__dirname,'../app/browser-extension'),out=process.env.TOUDI_PANEL_EVIDENCE || os.tmpdir();let browser;
(async()=>{
 browser=await pw.chromium.launch({headless:true,executablePath:process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 const page=await browser.newPage({viewport:{width:400,height:660}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://fixture.invalid/**',r=>{const name=path.basename(new URL(r.request().url()).pathname);r.fulfill({body:fs.readFileSync(name==='logo.svg'?path.join(root,'../assets/favicon.svg'):path.join(root,name)),contentType:name.endsWith('.svg')?'image/svg+xml':name.endsWith('.css')?'text/css':name.endsWith('.js')?'application/javascript':'text/html'})});
 await page.addInitScript(()=>{
 window.fixtureCalls=[];window.copiedText='';Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.copiedText=text}}});
 const personal=[['name','姓名','示例姓名'],['mobile','手机号码','13900000000'],['emergency','紧急联系人姓名','示例联系人'],['emergencyCompany','紧急联系人工作单位','示例单位'],['target','期望工作地点','示例城市'],['evaluation','自我评价','完整评价原文。'.repeat(45)],['special','特定用途素材','专项完整内容']];
 const records=[{id:'personal|basic',module:'personal',title:'本人资料',facts:personal.map(([key,label,value])=>({key,label,value}))},...['master','bachelor'].map(id=>({id:'education|'+id,module:'education',title:id==='master'?'硕士 · 示例甲大学':'本科 · 示例乙大学',facts:[{key:id+'.school',label:'学校',value:id==='master'?'示例甲大学':'示例乙大学'},{key:id+'.start',label:'开始日期',value:id==='master'?'2024-09-01':'2020-09-01'}]})),{id:'family|parent',module:'family',title:'示例家庭成员',facts:[{key:'family.company',label:'工作单位',value:'家庭成员单位'}]}];
 const rows=[['blank','ready','紧急联系人'],['existing','conflict','联系人工作单位'],['same','already','姓名'],['unknown','missing','资料缺失'],['uncertain','ambiguous','关系不明']].map(([fieldId,status,label])=>({fieldId,module:'personal',label,status,factKey:['ready','conflict','already'].includes(status)?fieldId:null,displayValue:'示例值',reason:'对应资料'}));
 rows.push({fieldId:'unbound',module:'education',label:'学校',status:'ready',factKey:'school',recordBinding:{groupId:'unboundGroup',status:'unbound'},reason:'未选择经历'});
 const state={startedAt:1,plan:{origin:'https://fixture.invalid',path:'/apply',profileId:'general',rows,choices:[],statusCounts:{ready:2,conflict:1,already:1,missing:1,ambiguous:1},groups:[{groupId:'unboundGroup',module:'education',label:'教育经历',status:'unbound',candidates:[],fieldIds:['unbound']}]},agentReview:{status:'completed',requested:2,accepted:1,rejected:0,unresolved:1,model:'selected-model'},structureReview:{status:'completed',accepted:1,rejected:0}};
 window.chrome={runtime:{sendMessage:async m=>{fixtureCalls.push(m);if(m.op==='state')return {value:{state,extensionVersion:'test',profile:{count:personal.length,profiles:[{id:'general',label:'合成资料',count:personal.length}]},preferences:{profile:'general',agentMode:'external',agentModel:'',autoAgent:false},sync:{status:'disconnected'}}};if(m.op==='copy-library')return {value:{records}};if(m.op==='fill')return {value:state};return {value:state};}}};
 });
 await page.goto('https://fixture.invalid/popup.html');assert.equal(await page.title(),'TouDi · 辅助填报');await page.locator('#fill:not([disabled])').waitFor();
 assert.equal(await page.locator('#review input[type=checkbox][data-field]').count(),0);
 assert.equal(await page.locator('#fillMode').inputValue(),'all');await page.locator('#fill').click();
 assert.deepEqual(await page.evaluate(()=>fixtureCalls.filter(m=>m.op==='fill').at(-1).selected),['blank','existing']);assert.deepEqual(await page.evaluate(()=>fixtureCalls.filter(m=>m.op==='fill').at(-1).overwrite),['existing']);
 await page.locator('#fillMode').selectOption('empty');await page.locator('#fill').click();assert.deepEqual(await page.evaluate(()=>fixtureCalls.filter(m=>m.op==='fill').at(-1).selected),['blank']);assert.deepEqual(await page.evaluate(()=>fixtureCalls.filter(m=>m.op==='fill').at(-1).overwrite),[]);
 await page.locator('#tabLibrary').click();await page.locator('[data-copy-fact="name"]').waitFor();
 assert.equal(await page.locator('#fillPane').isVisible(),false);assert.equal(await page.locator('#actions').isVisible(),false);assert.equal(await page.locator('.extension-links').isVisible(),false);assert.equal(await page.locator('#sourceStatus').isVisible(),false);assert.equal(await page.locator('[data-copy-record]').count(),0);
 const height=await page.locator('#copyRecords').evaluate(el=>el.getBoundingClientRect().height);assert(height>=400,`Library content height ${height} must be >=400 at 400x660`);
 const sections=await page.locator('.copy-section').count(),facts=await page.locator('[data-copy-fact]').count();assert.equal(sections,7);assert.equal(facts,12);assert.equal(await page.locator('#copyRecordSelect').count(),0);
 for(const key of ['mobile','emergency'])assert(await page.locator('[data-copy-fact="'+key+'"]').locator('..').evaluate(n=>n.getBoundingClientRect().height<=34),'Short contact fields must fit in a compact line');
 await page.screenshot({path:path.join(out,'资料浏览_连续目录.png')});
 await page.locator('[data-copy-module="personal:contact"]').click();await page.waitForFunction(()=>document.querySelector('[data-copy-module="personal:contact"]').getAttribute('aria-current')==='location');assert.equal(await page.locator('[data-copy-fact]').count(),facts);assert.equal(await page.locator('[data-copy-fact="name"]').count(),1);await page.locator('[data-copy-fact="emergencyCompany"]').click();assert.equal(await page.evaluate(()=>copiedText),'示例单位');
 await page.screenshot({path:path.join(out,'资料浏览_紧凑联系信息.png')});
 await page.locator('[data-copy-module="personal:skills"]').click();assert.equal(await page.locator('.copy-value.collapsed').count(),1);await page.locator('.expand-value').click();assert.equal(await page.locator('.copy-value.collapsed').count(),0);await page.locator('[data-copy-fact="evaluation"]').click();assert.equal(await page.evaluate(()=>copiedText),'完整评价原文。'.repeat(45));
 await page.locator('[data-copy-module="education"]').click();assert.match(await page.locator('#copyRecords').innerText(),/2020-09-01/);assert.match(await page.locator('#copyRecords').innerText(),/2024-09-01/);assert.equal(await page.locator('.copy-section').count(),sections);
 await page.locator('#copySearch').fill('紧急联系人');assert.equal(await page.locator('[data-copy-fact]').count(),2);assert.equal(await page.locator('.copy-section').count(),1);
 await page.locator('#copySearch').fill('不存在的字段');assert.match(await page.locator('#copyRecords').innerText(),/没有找到/);
 await page.locator('#copySearch').fill('');await page.locator('[data-copy-module="personal:basic"]').click();await page.locator('#copyRecords').hover();await page.mouse.wheel(0,10000);await page.waitForFunction(()=>{const n=document.querySelector('#copyRecords');return n.scrollTop>0 && n.scrollHeight-n.clientHeight-n.scrollTop<2;});
 assert.equal(await page.locator('[data-copy-module="family"]').getAttribute('aria-current'),'location');assert.equal(await page.locator('[data-copy-fact]').count(),facts);await page.locator('[data-copy-fact="family.company"]').click();assert.equal(await page.evaluate(()=>copiedText),'家庭成员单位');
 for(const scheme of ['light','dark'])for(const width of [320,400]){await page.emulateMedia({colorScheme:scheme});await page.setViewportSize({width,height:500});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await page.locator('#copyRecords').evaluate(n=>n.clientHeight>280 && n.scrollHeight>n.clientHeight));}
 await page.emulateMedia({colorScheme:'light'});await page.setViewportSize({width:400,height:660});
 await page.locator('#tabFill').click();assert.equal(await page.locator('#fillMode').inputValue(),'empty');assert.equal(await page.locator('#agentFeedback .feedback-details').getAttribute('open'),null);await page.locator('#agentFeedback summary').first().click();assert.match(await page.locator('#agentFeedback').innerText(),/采纳 1 项/);
 await page.screenshot({path:path.join(out,'批量填写_全部或仅空白.png')});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log(`PASS compact panel: library ${height}px / 660px; all sections and records remain present, directory only scrolls, wheel reaches last field, compact inline contact facts, exact full-copy/expand/search, 320/400px light/dark; bulk fill preserves existing and excludes unbound records; zero page errors.`);
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>browser?.close());
