'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
let playwright;try{playwright=require('playwright')}catch(_){playwright=require(process.env.TOUDI_PLAYWRIGHT_MODULE || path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'))}
const root=path.resolve(__dirname,'../app/browser-extension');let browser;
(async()=>{
 browser=await playwright.chromium.launch({headless:true,executablePath:process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 const page=await browser.newPage({viewport:{width:1360,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://fixture.invalid/**',r=>{const name=path.basename(new URL(r.request().url()).pathname);if(name==='application')return r.fulfill({contentType:'text/html',body:'<!doctype html><meta charset="utf-8"><title>合成招聘表单</title><body style="background:#f5f6f7;margin:0;font:16px Arial;color:#243338"><header style="background:white;padding:30px 70px;border-bottom:1px solid #ddd">Career · 申请职位</header><main style="margin:38px 70px;width:650px;padding:32px;background:white;border:1px solid #ddd;border-radius:8px"><h1>填写申请资料</h1><h2>教育经历</h2><label>学校名称<input style="display:block;width:90%;padding:12px;margin:15px 0" value="示例大学"></label><label>专业名称<input style="display:block;width:90%;padding:12px;margin:15px 0" value="信息管理"></label><h2>实习经历</h2><label>工作职责<textarea style="display:block;width:90%;height:160px;margin:15px 0"></textarea></label></main></body>'});return r.fulfill({body:fs.readFileSync(name==='logo.svg'?path.join(root,'../assets/favicon.svg'):path.join(root,name)),contentType:name.endsWith('.svg')?'image/svg+xml':name.endsWith('.css')?'text/css':name.endsWith('.js')?'application/javascript':'text/html'})});
 await page.addInitScript(()=>{
 const long='需求研究：参与产品访谈与资料归纳，整理用户任务和场景。\n原型协作：与团队共同梳理流程、完成界面方案并记录迭代反馈。\n交付跟进：维护问题清单并核对实现结果。\n'+('这里是保留的完整原始职责内容，复制时必须包含每一个字。'.repeat(9));
 const records=[{id:'person',module:'personal',title:'基本资料',text:'姓名：示例同学\n现居地：示例城市',facts:[{key:'name',label:'姓名',value:'示例同学'},{key:'city',label:'现居地',value:'示例城市'}]},{id:'school',module:'education',title:'硕士 · 示例大学',text:'学校：示例大学',facts:[{key:'school',label:'学校',value:'示例大学'},{key:'major',label:'专业',value:'信息管理'}]},{id:'work',module:'internship',title:'示例公司 · 产品实习',text:'工作职责：'+long,facts:[{key:'company',label:'单位',value:'示例公司'},{key:'tasks',label:'工作职责',value:long}]},{id:'award',module:'awards',title:'案例竞赛',text:'奖项名称：案例竞赛',facts:[{key:'award',label:'奖项名称',value:'案例竞赛'},{key:'date',label:'日期',value:'2025-10-01'}]}];
 const preferences={profile:'general',agentMode:'external',agentModel:'',autoAgent:false};window.fixtureCalls=[];window.fixtureLong=long;window.fixtureCopied='';Object.defineProperty(navigator,'clipboard',{value:{writeText:async v=>{window.fixtureCopied=v}}});
 window.chrome={runtime:{onMessage:{addListener(){},removeListener(){}},sendMessage:async m=>{window.fixtureCalls.push(m);if(m.op==='state')return {value:{extensionVersion:'fixture',profile:{count:location.search.includes('empty')?0:8,profiles:[{id:'general',label:'合成资料',count:8}]},preferences,sync:{status:'disconnected'}}};if(m.op==='copy-library')return {value:{records}};if(m.op==='scan')return {value:{startedAt:1,plan:{origin:'https://fixture.invalid',path:'/application',profileId:'general',rows:[{fieldId:'school',label:'学校',module:'education',groupLabel:'教育经历',status:'ready',factKey:'school',displayValue:'示例大学',reason:'对应完整资料'}],statusCounts:{ready:1},choices:[]}}};return {value:{}};}}};
 });
 await page.goto('https://fixture.invalid/application');await page.addScriptTag({path:path.join(root,'panel-host.js')});await page.evaluate(()=>TouDiPanelHost({url:'https://fixture.invalid/popup.html?panel=fixture&tab=8'}));
 const frame=page.frameLocator('iframe'); // Closed shadow root deliberately hides the iframe from page queries.
 const iframe=()=>page.frames().find(f=>f.url().includes('/popup.html'));
 await page.waitForFunction(()=>document.querySelector('#toudi-floating-host'));
 for(let i=0;i<100&&!iframe();i++)await new Promise(r=>setTimeout(r,20));assert(iframe(),JSON.stringify(page.frames().map(f=>f.url())));const ui=iframe();await ui.locator('#fill').waitFor({state:'visible'});await ui.waitForFunction(()=>fixtureCalls.some(m=>m.op==='scan'));const scanCount=await ui.evaluate(()=>fixtureCalls.filter(m=>m.op==='scan').length);await ui.locator('#tabLibrary').click();await ui.locator('.copy-record').first().waitFor();
 assert.equal(await ui.evaluate(()=>fixtureCalls.filter(m=>m.op==='scan').length),scanCount,'Library navigation must not scan again');
 assert.equal(await ui.locator('.copy-record').count(),5);assert.equal(await ui.locator('#copyDirectory button').count(),5);assert.equal(await ui.locator('[data-copy-fact="city"]').count(),1);
 await ui.locator('[data-copy-module="internship"]').click();await ui.locator('[data-copy-fact="tasks"]').click();assert.equal(await ui.evaluate(()=>fixtureCopied),await ui.evaluate(()=>fixtureLong));assert(await ui.locator('[data-copy-fact="tasks"]').evaluate(e=>e.classList.contains('collapsed')));
 await ui.locator('.expand-value').click();assert.equal(await ui.locator('[data-copy-fact="tasks"]').evaluate(e=>e.classList.contains('collapsed')),false);

 await ui.locator('#copySearch').fill('案例竞赛');assert.equal(await ui.locator('.copy-record').count(),1);assert.match(await ui.locator('#copyRecords').innerText(),/案例竞赛/);
 await ui.locator('#copySearch').fill('不存在的合成内容');assert.match(await ui.locator('#copyRecords').innerText(),/没有找到/);
 await ui.locator('#copySearch').fill('');await ui.locator('#tabFill').click();await ui.locator('#scan').click();await ui.locator('#scanSummary').filter({hasText:'可填写'}).waitFor();assert.equal(await ui.locator('#fill').isEnabled(),true);

 let bounds=await page.locator('#toudi-floating-host').boundingBox();assert.equal(bounds.width,400);assert(bounds.height<=740);const start={x:bounds.x+100,y:bounds.y+16};await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(120,100);await page.mouse.up();bounds=await page.locator('#toudi-floating-host').boundingBox();assert(bounds.x<200);
 // Controls are in closed shadow DOM; use observed host geometry for real mouse interaction.
 await page.mouse.click(bounds.x+bounds.width-52,bounds.y+16);bounds=await page.locator('#toudi-floating-host').boundingBox();assert.equal(bounds.height,38);
 await page.mouse.click(bounds.x+bounds.width-52,bounds.y+16);assert((await page.locator('#toudi-floating-host').boundingBox()).height>300);
 await page.setViewportSize({width:360,height:640});await page.waitForFunction(()=>{const r=document.querySelector('#toudi-floating-host').getBoundingClientRect();return r.right<=innerWidth&&r.bottom<=innerHeight});bounds=await page.locator('#toudi-floating-host').boundingBox();assert(bounds.x>=0&&bounds.x+bounds.width<=360&&bounds.y+bounds.height<=640);await ui.locator('#tabLibrary').click();assert(await ui.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 assert.equal(await page.locator('#toudi-floating-host').evaluate(e=>e.shadowRoot),null);assert.equal(await page.locator('body').innerText().then(t=>t.includes('示例同学')),false);
 bounds=await page.locator('#toudi-floating-host').boundingBox();await page.mouse.click(bounds.x+bounds.width-22,bounds.y+16);assert.equal(await page.locator('#toudi-floating-host').count(),0);await page.goto('https://fixture.invalid/popup.html?empty=1');await page.locator('#empty').waitFor({state:'visible'});assert(await page.locator('#scan').isHidden());assert(await page.locator('#tabLibrary').isDisabled());await page.goto('https://fixture.invalid/popup.html#library');await page.locator('[data-copy-fact=\"name\"]').waitFor();await page.evaluate(()=>navigator.clipboard.writeText=async()=>{throw Error('denied')});await page.locator('[data-copy-fact=\"name\"]').click();assert.match(await page.locator('#notice').innerText(),/复制未完成/);assert.deepEqual(errors,[]);
 console.log('PASS floating panel: no scan required for library, continuous categories + search, expand and exact full copy, scan preserved, drag/minimize/close, 400px desktop and 360px viewport bounds, closed host/no profile DOM leak, zero page errors.');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>browser?.close());
