'use strict';
// Browser plugin unavailable: isolated Chrome with synthetic data, no user-profile writes.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const L=require('../app/browser-extension/profile-library.js'),{makePack,installFixture,fullText}=require('./profile_ui_fixture.cjs');
let pw;try{pw=require('playwright')}catch(_){pw=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'))}
let pack=makePack();const summary=pack.facts.find(f=>f.module==='personal'&&f.label==='自我评价'),skills=pack.facts.find(f=>f.module==='personal'&&f.label==='专业技能');
summary.recordId='legacy-summary';skills.recordId='legacy-skills';
pack.facts.push({key:'reference.short',module:'personal',recordId:'legacy-reference',recordLabel:'复用参考',label:'自我评价',value:'合成参考稿完整原文',manual:true,profiles:['general'],aliases:['自我评价']},{key:'reference.full',module:'personal',recordId:'legacy-reference',recordLabel:'复用参考',label:'完整表达版本',value:fullText,manual:true,profiles:['general'],aliases:['完整表达版本']},{key:'custom.personal',module:'personal',recordId:'legacy-custom',recordLabel:'基本信息',label:'自定义个人字段',value:'合成原文',profiles:['general'],aliases:['自定义个人字段']});pack=require('../app/browser-extension/filling-core.js').validatePack(pack);
const records=Object.fromEntries(pack.profiles.map(p=>[p.id,L.copyRecords(pack,p.id)])),root=path.resolve(__dirname,'../app/browser-extension'),out=process.env.TOUDI_PANEL_EVIDENCE || os.tmpdir();let browser;
(async()=>{
  browser=await pw.chromium.launch({headless:true,executablePath:process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
  const context=await browser.newContext({reducedMotion:'reduce'}),errors=[];await context.addInitScript(installFixture,{pack,records});
  await context.route('https://fixture.invalid/**',route=>{const file=path.basename(new URL(route.request().url()).pathname);return route.fulfill({body:fs.readFileSync(file==='logo.svg'?path.join(root,'../assets/favicon.svg'):path.join(root,file)),contentType:file.endsWith('.css')?'text/css':file.endsWith('.js')?'application/javascript':file.endsWith('.svg')?'image/svg+xml':'text/html'});});
  const popup=await context.newPage();popup.on('pageerror',e=>errors.push(e.message));await popup.setViewportSize({width:400,height:700});await popup.goto('https://fixture.invalid/popup.html#library');
  await popup.locator('[data-copy-fact]').first().waitFor();assert(await popup.locator('[data-copy-fact="reference.short"]').isHidden());
  await popup.locator('[data-copy-module="personal:supplement"]').click();assert(await popup.locator('[data-copy-fact="reference.short"]').isVisible());await popup.locator('[data-copy-fact="reference.full"]').click();assert.equal(await popup.evaluate(()=>fixtureCopied),fullText);
  const options=await context.newPage();options.on('pageerror',e=>errors.push(e.message));await options.setViewportSize({width:1240,height:900});await options.goto('https://fixture.invalid/options.html');
  const personal=options.locator('[data-profile-module="personal"]');await personal.locator('.record').waitFor();assert.equal(await personal.locator('.record').count(),1,'Legacy personal record IDs share one editing block');
  assert.equal(await personal.locator('[data-record-edit]').count(),1);assert.equal(await options.locator('.fact-actions,[data-edit]').count(),0);assert(!(await personal.innerText()).includes('人工确认'));
  assert(await personal.locator('[data-fact-copy="reference.short"]').isHidden());await personal.locator(`[data-fact-copy="${skills.key}"]`).click();assert.equal(await options.evaluate(()=>fixtureCopied),skills.value);
  await options.screenshot({path:path.join(out,'个人资料_统一查阅.png')});
  const summaryView=personal.locator(`[data-fact-copy="${summary.key}"]`);assert.equal(await summaryView.textContent(),fullText);await summaryView.click();assert.equal(await options.evaluate(()=>fixtureCopied),fullText);await summaryView.locator('..').locator('[data-fact-expand]').click();assert.equal(await summaryView.getAttribute('class'),'fact-value copied');await summaryView.locator('..').locator('[data-fact-expand]').click();assert((await summaryView.getAttribute('class')).includes('collapsed'));
  await personal.locator('[data-record-edit]').click();assert(await personal.locator('#recordEditor').isVisible());assert.equal(await options.locator('dialog:visible').count(),0);assert(await personal.locator('.record').isHidden());await options.screenshot({path:path.join(out,'个人资料_页内编辑.png')});
  assert.equal(await options.locator('#recordField-skills').inputValue(),skills.value);assert.equal(await options.locator('#recordField-summary').inputValue(),summary.value);
  const exact='  '+fullText+'\n新增完整原文。  ';await options.locator('#recordField-summary').fill(exact);await options.locator('[data-record-extra="custom.personal"]').fill('更新的合成原文');
  assert(await options.locator('[data-record-extra="reference.short"]').isHidden());await options.locator('#recordExtras .reference-material summary').click();assert.equal(await options.locator('[data-record-extra="reference.full"]').inputValue(),fullText);
  for(const width of [700,1240]){await options.setViewportSize({width,height:900});assert(await options.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const size=await options.locator('#recordEditor').evaluate(n=>({client:n.clientHeight,scroll:n.scrollHeight,overflow:getComputedStyle(n).overflowY}));assert(size.scroll<=size.client+1 && !['auto','scroll'].includes(size.overflow),'Page editing has no internal scroll trap: '+JSON.stringify(size));}
  await options.locator('#recordForm button[type=submit]').click();await options.locator('#recordEditor').waitFor({state:'hidden'});const saved=await options.evaluate(()=>fixtureSaved);
  assert.equal(saved.facts.find(f=>f.key===summary.key).value,exact);assert.equal(saved.facts.find(f=>f.key==='custom.personal').value,'更新的合成原文');
  for(const original of pack.facts){const current=saved.facts.find(f=>f.key===original.key);assert.equal(current.recordId,original.recordId);assert.deepEqual(current.profiles,original.profiles);if(original.key!==summary.key && original.key!=='custom.personal')assert.deepEqual(current,original);}
  await personal.locator('.reference-material summary').click();await personal.locator('[data-fact-copy="reference.full"]').click();assert.equal(await options.evaluate(()=>fixtureCopied),fullText);assert.equal(await personal.locator('[data-fact-copy]').count(),pack.facts.filter(f=>f.module==='personal'&&f.profiles.includes('general')).length);
  assert.deepEqual(errors,[]);console.log('PASS inline personal UI: one editor across legacy IDs, references separate and preserved, original text copied directly, no modal or per-field copy/edit buttons, whole-block save/readback preserves IDs and versions, 700/1240px and no nested scrolling.');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>browser?.close());
