'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{webcrypto}=require('node:crypto');
const root=path.join(__dirname,'../app/browser-extension'),local={},session={};let listener,resolveModel,modelCalls=0,currentValue='',shape='shape-1',reject=false;
function storage(data){return {async get(key){return {[key]:structuredClone(data[key])};},async set(value){Object.assign(data,structuredClone(value));},async remove(keys){for(const k of Array.isArray(keys)?keys:[keys])delete data[k];},async setAccessLevel(){}};}
const context={structuredClone,crypto:webcrypto,TextEncoder,URL,console,setTimeout,clearTimeout,chrome:{storage:{local:storage(local),session:storage(session)},runtime:{getManifest:()=>({version:'fixture-version'}),getURL:p=>'chrome-extension://fixture/'+p,onMessage:{addListener(fn){listener=fn}},id:'fixture'},tabs:{query:async()=>[{id:1,url:'https://fixture.invalid/application?private=ignored'}]}}};vm.createContext(context);context.importScripts=(...names)=>{for(const n of names)vm.runInContext(fs.readFileSync(root+'/'+n,'utf8'),context)};vm.runInContext(fs.readFileSync(root+'/worker.js','utf8'),context);
const candidates=[{fieldId:'field',labels:[{id:'label',text:'身高'}],groups:[{id:'group',text:'个人信息'}]}];
context.fixtureEngine=async(tab,op,hints)=>{const applies=hints?.field && !reject;return {protocol:1,engineVersion:'fixture-engine',origin:'https://fixture.invalid',path:'/application',fingerprint:applies?'mapped-'+shape:shape,platform:'fixture',fields:[{id:'field',label:applies?'身高':'',module:'personal',type:'text',value:currentValue}],structure:{fingerprint:shape,candidates,applied:applies?['field']:[],rejected:reject && hints?.field?['field']:[]}}};
context.fixtureNative=async p=>{assert.equal(p.op,'adapt');assert.equal(p.model,'fixture-model');assert.deepEqual(JSON.parse(JSON.stringify(p.candidates)),candidates);assert.deepEqual(Object.keys(p).sort(),['candidates','model','op','protocol']);modelCalls++;return new Promise(resolve=>{resolveModel=resolve})};vm.runInContext('engine=fixtureEngine;native=fixtureNative',context);
const send=m=>new Promise((resolve,reject)=>listener(m,{id:'fixture',url:'chrome-extension://fixture/popup.html'},r=>r.error?reject(Error(r.error)):resolve(r.value)));
const tick=()=>new Promise(r=>setImmediate(r));
(async()=>{
 await send({op:'profile-save',base:null,pack:{schemaVersion:1,profiles:[{id:'general',label:'合成资料'}],facts:[{key:'height',label:'身高',value:'175',module:'personal'}],rules:[]}});
 await send({op:'preferences',preferences:{agentMode:'codex',agentModel:'fixture-model',autoAgent:true}});
 let state=await send({op:'scan'});assert.equal(modelCalls,0);assert(state.structurePending);assert.equal(state.plan.statusCounts.ready || 0,0);
 const task=await send({op:'structure-task'});assert(!task.task.includes('175'));assert(!task.task.includes('private=ignored'));
 let run=send({op:'adapt',agent:true,startedAt:state.startedAt});await tick();assert.equal(modelCalls,1);assert.equal((await send({op:'state'})).state.structureReview.status,'running');
 resolveModel({hints:{field:{labelId:'label',groupId:'group'}},provider:{called:true,model:'fixture-model'}});state=await run;assert.equal(state.structureReview.accepted,1);assert.equal(state.plan.statusCounts.ready,1);
 const cache=JSON.stringify(local.toudiStructureHints);assert(!cache.includes('175'));assert(!cache.includes('private'));state=await send({op:'scan'});assert.equal(state.structureReview.status,'cached');assert.equal(state.structurePending,false);assert.equal(modelCalls,1);
 shape='shape-2';state=await send({op:'scan'});assert(state.structurePending);assert(!state.structureReview);run=send({op:'adapt',agent:true,startedAt:state.startedAt});await tick();await send({op:'remap',mappings:{field:'height'}});resolveModel({hints:{field:{labelId:'label'}},provider:{called:true}});await assert.rejects(run,/手动匹配已变化/);
 state=await send({op:'scan'});run=send({op:'adapt',agent:true});await tick();currentValue='user edited';resolveModel({hints:{field:{labelId:'label'}},provider:{called:true}});state=await run;assert.equal(state.structureReview.status,'failed');assert.match(state.structureReview.message,/字段值已变化/);assert.equal(Object.keys(local.toudiStructureHints).length,1);
 state=await send({op:'scan'});const invalid=await send({op:'adapt',hints:{field:{script:'anything'}}});assert.equal(invalid.structureReview.status,'failed');assert.equal(Object.keys(local.toudiStructureHints).length,1);
 state=await send({op:'scan'});reject=true;state=await send({op:'adapt',hints:{field:{labelId:'label'}}});assert.equal(state.structureReview.accepted,0);assert.equal(state.structureReview.rejected,1);assert.equal(Object.keys(local.toudiStructureHints).length,1);
 reject=false;state=await send({op:'scan'});run=send({op:'adapt',agent:true});await tick();await send({op:'clear-plan'});resolveModel({hints:{field:{labelId:'label'}},provider:{called:true}});await assert.rejects(run,/重新识别/);assert.equal((await send({op:'state'})).state,null);
 console.log('PASS structure worker: local plan first, candidate-only model request, engine-validated cache, fingerprint invalidation, manual/value/clear late-result protection and invalid hints rejection');
})().catch(e=>{console.error(e);process.exitCode=1});
