'use strict';
const assert=require('node:assert/strict');
const path=require('node:path');
const os=require('node:os');
const enginePath=path.resolve(__dirname,'../app/assets/form-engine.js');
assert.deepEqual(Object.keys(require(enginePath)).sort(),['apply','highlight','scan']);
let playwright;try{playwright=require('playwright');}catch(_){playwright=require(process.env.TOUDI_PLAYWRIGHT_MODULE || path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const fixture=`<!doctype html><meta charset="utf-8"><title>Synthetic application</title><form>
<fieldset><legend>个人信息</legend><label>姓名<input name="name"></label><label>联系地址<input name="address"></label><label>户籍地址<input name="address"></label><label>邮箱<input type="email" name="email"></label><label>备注<input maxlength="3" name="note"></label><label>必填项<input required name="required"></label><label>密码<input type="password" value="synthetic"></label><input type="hidden" name="token" value="synthetic"><label>验证码<input></label><label>资料附件<input type="file"></label><label>同意隐私条款<input type="checkbox"></label><label>接受调剂<input type="checkbox"></label><div class="form-item"><label>性别</label><label>选项甲<input type="radio" name="gender" value="a"></label><label>选项乙<input type="radio" name="gender" value="b"></label></div><label>地区<select><option value="">请选择</option><option value="a">测试地区甲</option></select></label></fieldset>
<label>有界数值<input name="bounded" type="number" min="0" max="4" step="0.1" value="2"></label><label>申请编码<input name="code" pattern="[A-Z]{2}" value="AB"></label>
<fieldset><legend>教育经历 · 硕士</legend><label>学校<input name="school"></label><div role="radiogroup" aria-label="学历"><label>硕士选项<input type="radio" name="qualification" value="master"></label><label>博士选项<input type="radio" name="qualification" value="doctor"></label></div></fieldset><fieldset><legend>教育经历 · 本科</legend><label>学校<input name="school"></label><span id="degree-question">学历</span><div role="radiogroup" aria-labelledby="degree-question"><label>本科选项<input type="radio" name="qualification" value="bachelor"></label><label>专科选项<input type="radio" name="qualification" value="associate"></label></div></fieldset>
<fieldset><legend>实习经历 · 合成单位甲</legend><label>岗位<input name="role"></label></fieldset><fieldset><legend>实习经历 · 合成单位乙</legend><label>岗位<input name="role"></label></fieldset>

<fieldset><legend>教育经历</legend><label>毕业日期<input type="date"></label></fieldset><div><span class="field-label">近邻字段</span><input></div><label>只读字段<input readonly></label><label>ARIA地区<input role="combobox" aria-controls="aria-options"></label><div id="aria-options"><button type="button" role="option" data-value="b" onclick="document.querySelector('[role=combobox]').value='测试地区乙'">测试地区乙</button></div><div role="combobox" aria-label="复杂级联" style="padding:10px"></div><div hidden><label>隐藏tab<input value="synthetic"></label></div><div id="host"></div><iframe id="same"></iframe><iframe src="https://cross.invalid/"></iframe><button type="submit">提交</button></form><script>window.submits=0;window.choiceClicks=0;window.choiceChanges=0;window.choiceState={};document.querySelectorAll('input[type=radio],input[type=checkbox]').forEach(n=>{n.addEventListener('click',()=>{choiceClicks++;choiceState[n.name || n.closest('label').textContent]=n.checked});n.addEventListener('change',()=>choiceChanges++)});document.querySelector('form').onsubmit=e=>{e.preventDefault();submits++};document.querySelector('#host').attachShadow({mode:'open'}).innerHTML='<label>影子字段<input></label>';document.querySelector('#same').srcdoc='<label>框架字段<input></label>';</script>`;
let browser;
(async()=>{browser=await playwright.chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('http://synthetic.test/**',route=>route.fulfill({contentType:'text/html',body:fixture}));await page.route('https://cross.invalid/**',route=>route.fulfill({body:'<input>'}));await page.goto('http://synthetic.test/app?excluded=synthetic#excluded');await page.waitForTimeout(100);await page.addScriptTag({path:enginePath});
const scan=()=>page.evaluate(()=>TouDiFormEngine.scan());const apply=(s,actions,extra={})=>page.evaluate(({s,actions,extra})=>TouDiFormEngine.apply({fingerprint:s.fingerprint,origin:s.origin,path:s.path,actions,...extra}),{s,actions,extra});const find=(s,label)=>s.fields.find(x=>x.label===label);const act=(f,value,extra={})=>({fieldId:f.id,value,expectedValue:f.value,...extra});
let s=await scan();assert.equal(s.protocol,1);assert.equal(s.path,'/app');assert(!JSON.stringify(s).includes('excluded'));assert(!s.fields.some(x=>/密码|隐藏tab/.test(x.label)));assert(s.warnings.some(x=>x.code==='cross-origin-frame'));assert(find(s,'影子字段'));assert(find(s,'框架字段'));assert(find(s,'近邻字段'));assert.notEqual(find(s,'联系地址').id,find(s,'户籍地址').id);const schools=s.fields.filter(x=>x.label==='学校');assert.deepEqual(schools.map(x=>x.recordHint),['教育经历 · 硕士','教育经历 · 本科']);assert(schools.every(x=>x.module==='education'));assert.equal(s.fields.filter(x=>x.label==='岗位'&&x.module==='work').length,2);assert.equal(find(s,'毕业日期').recordHint,'');assert.equal(find(s,'性别').groupLabel,'个人信息');assert.equal(find(s,'性别').module,'personal');assert.equal(find(s,'只读字段').unsupported,'disabled-or-readonly');const degrees=s.fields.filter(x=>x.label==='学历');assert.equal(degrees.length,2);assert(degrees.every(x=>x.module==='education'));assert.deepEqual(degrees.map(x=>x.options.map(o=>o.value)),[['master','doctor'],['bachelor','associate']]);
let r=await apply(s,[act(find(s,'姓名'),'合成甲'),act(find(s,'联系地址'),'甲'),act(find(s,'户籍地址'),'乙'),act(find(s,'接受调剂'),true),act(find(s,'地区'),'a'),act(find(s,'性别'),'b'),act(find(s,'ARIA地区'),'b'),act(find(s,'毕业日期'),'2035-06-01')]);assert.equal(r.summary.verified,8);assert.equal(r.submitted,false);assert.equal(r.saveState,'unconfirmed');assert.equal(await page.evaluate(()=>submits),0);assert.equal((await scan()).fingerprint,s.fingerprint);assert.deepEqual(await page.evaluate(()=>[choiceClicks,choiceChanges,choiceState.gender,choiceState['接受调剂']]),[2,2,true,true]);s=await scan();const clickBefore=await page.evaluate(()=>choiceClicks);r=await apply(s,[act(find(s,'接受调剂'),true,{overwrite:true})]);assert.equal(r.summary.verified,1);assert.equal(await page.evaluate(()=>choiceClicks),clickBefore);assert.equal(find(await scan(),'接受调剂').id,find(s,'接受调剂').id);
s=await scan();r=await apply(s,[act(find(s,'姓名'),'合成乙'),act(find(s,'姓名'),'合成丙')]);assert(r.results.every(x=>x.reason==='duplicate-action'));r=await apply(s,[act(find(s,'姓名'),'合成乙')]);assert.equal(r.results[0].reason,'existing-value');await page.locator('[name=name]').fill('用户改动');r=await apply(s,[act(find(s,'姓名'),'合成乙',{overwrite:true})]);assert.equal(r.results[0].reason,'value-changed');
s=await scan();await page.locator('[name=note]').fill(' ');r=await apply(s,[act(find(s,'备注'),'abc')]);assert.equal(r.results[0].reason,'value-changed');await page.locator('[name=note]').fill('');
s=await scan();r=await apply(s,[act(find(s,'备注'),'过长内容'),act(find(s,'必填项'),''),act(find(s,'地区'),'unknown',{overwrite:true}),act(find(s,'接受调剂'),'yes',{overwrite:true}),act(find(s,'同意隐私条款'),true),act(find(s,'验证码'),'123'),act(find(s,'资料附件'),'x'),act(find(s,'复杂级联'),'x'),act(find(s,'只读字段'),'x')]);assert.deepEqual(r.results.map(x=>x.reason),['maxlength-exceeded','required-empty','option-not-found','checkbox-requires-boolean','consent','verification-code','file-upload','custom-selector','disabled-or-readonly']);
s=await scan();r=await apply(s,[act(find(s,'邮箱'),'invalid')]);assert.equal(r.results[0].reason,'validation-failed');
s=await scan();assert.deepEqual(find(s,'有界数值').constraints,{min:'0',max:'4',step:'0.1'});r=await apply(s,[act(find(s,'有界数值'),'4.5',{overwrite:true}),act(find(s,'申请编码'),'ab',{overwrite:true}),act(find(s,'毕业日期'),'2035-02-30',{overwrite:true})]);assert.deepEqual(r.results.map(x=>x.reason),['validation-failed','validation-failed','invalid-value']);assert.equal(await page.locator('[name=bounded]').inputValue(),'2');assert.equal(await page.locator('[name=code]').inputValue(),'AB');assert.equal(find(await scan(),'毕业日期').value,'2035-06-01');
await page.locator('[name=note]').evaluate(n=>n.addEventListener('input',()=>setTimeout(()=>{const clone=n.cloneNode(true);clone.value='';n.replaceWith(clone)},250)));s=await scan();r=await apply(s,[act(find(s,'备注'),'abc')]);assert.equal(r.results[0].reason,'value-not-retained');assert.equal(find(await scan(),'备注').id,find(s,'备注').id);
await page.evaluate(()=>document.querySelector('form').insertAdjacentHTML('beforeend','<label>条件消失<input name=disappear></label>'));s=await scan();await page.locator('[name=disappear]').evaluate(n=>n.addEventListener('input',()=>n.closest('label').remove()));r=await apply(s,[act(find(s,'条件消失'),'x')]);assert.equal(r.results[0].reason,'field-disappeared');
s=await scan();r=await apply(s,[act(find(s,'必填项'),'x')],{path:'/other'});assert.equal(r.results[0].reason,'page-changed');await page.evaluate(()=>{document.querySelector('form').insertAdjacentHTML('beforeend','<label>动态字段<input></label>')});r=await apply(s,[act(find(s,'必填项'),'x')]);assert.equal(r.results[0].reason,'structure-changed');
s=await scan();await page.locator('[name=required]').evaluate(n=>n.addEventListener('input',()=>document.querySelector('form').insertAdjacentHTML('beforeend','<label>条件字段<input></label>')));r=await apply(s,[act(find(s,'必填项'),'x')]);assert.equal(r.summary.verified,1);assert(r.warnings.some(x=>x.code==='structure-changed'));
await page.screenshot({path:'/tmp/toudi-form-engine-fixture.png'});assert.deepEqual(errors,[]);console.log('PASS form engine: semantics, unordered education, duplicate names, iframe/shadow, native readback, checkbox protocol, existing values, conflict, limits, native constraints preserve existing values, required, options, React remount/reset, page/fingerprint rejection, dynamic warning, no submit; 0 page errors');await browser.close();})().catch(error=>{console.error(error);process.exitCode=1}).finally(async()=>{if(browser)await browser.close()});
