'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{webcrypto}=require('node:crypto');
const root=path.join(__dirname,'../app/browser-extension'),local={},session={};let listener,resolveModel,modelCalls=0,writes=0,value='',author='',offered=['第一作者','通讯作者','其他'];
function storage(data){return {async get(key){return {[key]:structuredClone(data[key])}},async set(value){Object.assign(data,structuredClone(value))},async remove(keys){for(const key of Array.isArray(keys)?keys:[keys])delete data[key]},async setAccessLevel(){}}}
const ctx={structuredClone,crypto:webcrypto,TextEncoder,URL,console,setTimeout,clearTimeout,chrome:{storage:{local:storage(local),session:storage(session)},runtime:{getManifest:()=>({version:'fixture'}),getURL:p=>'chrome-extension://fixture/'+p,onMessage:{addListener(fn){listener=fn}},id:'fixture'},tabs:{get:async()=>({id:1,url:'https://fixture.invalid/apply'}),query:async()=>[{id:1,url:'https://fixture.invalid/apply'}]}}};vm.createContext(ctx);ctx.importScripts=(...names)=>names.forEach(n=>vm.runInContext(fs.readFileSync(path.join(root,n),'utf8'),ctx));vm.runInContext(fs.readFileSync(path.join(root,'worker.js'),'utf8'),ctx);
function scan(){return {protocol:1,origin:'https://fixture.invalid',path:'/apply',fingerprint:'shape',fields:[{id:'start',label:'开始时间',module:'work',groupId:'work',groupLabel:'实习经历',recordHint:'合成单位',type:'date',options:[],value},{id:'author',label:'作者',module:'publications',groupId:'paper',groupLabel:'论文发表',recordHint:'合成论文',type:'combobox',adapter:'phoenix-select',options:[],value:author}]}}
ctx.fixtureEngine=async(tab,op,arg)=>{
 if(op==='inspect-options')return {fingerprint:'shape',items:[{fieldId:'author',options:offered.map(text=>({value:text,text}))}]};
 if(op==='apply'){writes++;for(const action of arg.actions){if(action.fieldId==='start')value=action.value;if(action.fieldId==='author')author=action.optionValue;}return {summary:{verified:arg.actions.length},results:arg.actions.map(a=>({fieldId:a.fieldId,status:'verified'})),submitted:false}}return scan();
};
ctx.fixtureNative=request=>{assert.equal(request.op,'map');assert.deepEqual(Array.from(request.fields,f=>f.id),['author'],'deterministic start dates do not require model decisions');assert.equal(request.fields[0].options.length,3,'model decides against the inspected real choices');assert.equal(request.allowedFacts[0].value,'第五作者');modelCalls++;return new Promise(r=>resolveModel=()=>r({mappings:{author:'rank'},provider:{called:true,model:'fixture-model',optionDecisions:{author:{factKey:'rank',optionValue:'其他',sourceKeys:['rank'],reason:'第五作者属于其他作者。'}}}}))};vm.runInContext('engine=fixtureEngine;native=fixtureNative',ctx);
const send=m=>new Promise((r,j)=>listener(m,{id:'fixture',url:'chrome-extension://fixture/popup.html'},result=>result.error?j(Error(result.error)):r(result.value)));
async function wait(){for(let i=0;i<100&&!resolveModel;i++)await new Promise(r=>setTimeout(r,5));assert(resolveModel,JSON.stringify((await send({op:"state"})).state?.agentReview))}
(async()=>{
 await send({op:'profile-save',base:null,pack:{schemaVersion:1,profiles:[{id:'general',label:'合成资料'}],facts:[{key:'company',label:'单位',value:'合成单位',module:'internship',recordId:'w'},{key:'start-fact',label:'开始日期',value:'2025-05-01',module:'internship',recordId:'w'},{key:'paper-name',label:'论文名称',value:'合成论文',module:'publications',recordId:'p'},{key:'rank',label:'作者排序',value:'第五作者',module:'publications',recordId:'p'}],rules:[]}});await send({op:'preferences',preferences:{agentMode:'codex',agentModel:'fixture-model',autoAgent:false}});
 const initial=await send({op:'scan'});assert.equal(writes,0);assert.equal(initial.plan.rows.find(r=>r.fieldId==='start').status,'ready');
 const localFill=await send({op:'auto-fill'});assert.equal(modelCalls,0,'Filling is independent of optional model review');assert.equal(writes,1);assert.equal(value,'2025-05-01');assert.equal(author,'');assert.equal(localFill.report.summary.verified,1);
 value='';author='';await send({op:'scan'});const first=send({op:'agent-review'});await wait();const duplicate=send({op:'agent-review'});assert.equal(writes,1,'Review never fills the page');const progress=await send({op:'state'});assert.equal(progress.state.agentReview.status,'running');assert.equal((await send({op:'copy-library',localOnly:true})).records.length,2);await assert.rejects(send({op:'auto-fill'}),/核对/);
 resolveModel();const a=await first,b=await duplicate;assert.equal(modelCalls,1);assert.equal(writes,1);assert.equal(a.agentReview.status,'completed');assert.equal(b.agentReview.status,'completed');assert.equal(a.plan.rows.find(r=>r.fieldId==='author').status,'ready','Review returns an executable choice before filling');
 const filled=await send({op:'auto-fill'});assert.equal(modelCalls,1,'Applying a reviewed plan never requests a second model call');assert.equal(writes,2);assert.equal(filled.report.summary.verified,2);assert.equal(value,'2025-05-01');assert.equal(author,'其他','Fresh scan preserves the verified option decision');
 value='';author='';resolveModel=null;await send({op:'scan'});const stale=send({op:'agent-review'});await wait();await send({op:'preferences',preferences:{agentMode:'codex',agentModel:'fixture-model'}});resolveModel();await assert.rejects(stale,/变化/);assert.equal(writes,2);
 ctx.fixtureNative=async()=>{throw Error('fixture model unavailable')};vm.runInContext('native=fixtureNative',ctx);await send({op:'scan'});const failed=await send({op:'agent-review'});assert.equal(failed.agentReview.status,'failed');const fallback=await send({op:'auto-fill'});assert.equal(fallback.report.summary.verified,1);assert.equal(value,'2025-05-01');assert.equal(author,'');
 console.log('PASS workflow: scan only -> optional structured review -> returned ready choice -> separate fill with no model wait; local date without review, actual options, duplicate review, library browsing, stale protection, reviewed choice survives rescan, model outage preserves local fill');
})().catch(e=>{console.error(e);process.exitCode=1});
