'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../app/assets/workbench.js'),'utf8');
const html=fs.readFileSync(path.join(__dirname,'../app/投递管理.html'),'utf8');
const bootstrap=html.slice(html.indexOf('const AGENT_START_GUIDE_URL='),html.indexOf('\nasync function copyAgentBootstrap'));
const copyStart=source.indexOf('copyAgentBootstrap = async function');
const copy=source.slice(copyStart,source.indexOf('const workspaceRefreshSnapshots',copyStart));
let copied='';
const desktop={workspace:'/fixture/Private Workspace',agentTool:'/fixture/Private App/tool',guideRoot:'/fixture/Private App/guides'};
const context={window:{__TOUDI_DESKTOP__:desktop},navigator:{clipboard:{writeText:async text=>{copied=text}}},showToast:()=>{}};
vm.createContext(context);vm.runInContext(bootstrap+copy,context);
(async()=>{
  const general=context.agentBootstrapText();
  for(const value of Object.values(desktop))assert(!general.includes(value));
  for(const step of ['我的信源','我的材料','本次任务','已有资料','workspace status','preference-catalog','read','validate','commit','刷新资料'])assert(general.includes(step));
  await context.copyAgentBootstrap();assert.equal(copied,general);
  await context.copyAgentBootstrap('true');assert.equal(copied,general);
  await context.copyAgentBootstrap(true);assert.equal(copied,general);
  for(const value of Object.values(desktop))assert(!copied.includes(value));
  assert.equal(context.agentBootstrapText(),general);
  context.window.__TOUDI_DESKTOP__=null;assert.equal(context.agentBootstrapText(),general);
  const panel=html.slice(html.indexOf('id="settings-panel-agent"'),html.indexOf('// Legacy partial exports'));
  assert.equal((panel.match(/onclick="copyAgentBootstrap\(\)"/g)||[]).length,1);
  assert(!html.includes('copyAgentBootstrap(true)'));
  const guide=fs.readFileSync(path.join(__dirname,'../docs/开始与初始化.md'),'utf8');
  assert(guide.includes(general));
  console.log('PASS Agent startup: one complete message matches the guide and never copies private directories');
})().catch(e=>{console.error(e);process.exitCode=1});
