'use strict';
// Shared Phoenix interaction contract observed in live résumé forms; all data synthetic.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),C=require('../app/browser-extension/filling-core.js');
let pw;try{pw=require('playwright')}catch(_){pw=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'))}
const records=[['work','internship','w','实习经历',[['单位名称','单位','合成单位','text'],['开始时间','开始日期','2018-05-01','month'],['结束时间','结束日期','2018-08-30','month']]],['projects','project','p','项目经历',[['项目名称','名称','合成项目','text'],['开始时间','开始日期','2024-12-01','month'],['结束时间','结束日期','至今','month']]],...['a','b','c'].map((id,i)=>['awards','awards',id,'获奖情况',[['奖项','奖项名称','合成奖项'+id,'text'],['获奖时间','获奖日期',['2010-10-01','2024-06-30','2023-11-01'][i],'day'],['获奖级别','获奖级别',i<2?'校级':'省级','select']]])];
const facts=records.flatMap(([wire,module,id,title,fields])=>fields.map(([field,label,value,type])=>({key:id+label,recordId:id,module,label,value,profiles:['general'],...(/日期/.test(label)&&value!=='至今'?{precision:'day'}:{})}))),p=C.profile(C.validatePack({schemaVersion:1,profiles:[{id:'general',label:'合成资料'}],facts,rules:[]}));
const html='<meta charset="utf-8"><style>body{font:14px sans-serif}.form-item{display:inline-block;padding:10px;width:30%}.phoenix-select__content,input{min-width:140px}.common-unmodeled-layer{position:fixed;top:30px;right:30px;background:#fff;border:1px solid #ddd;padding:12px;z-index:100}.phoenix-calendar-cell{display:inline-block;width:30px;padding:5px}.phoenix-calendar-year-panel-year,.phoenix-calendar-month-panel-month{display:inline-block;width:65px;padding:8px}</style><form><div id="sections"></div><button type="submit">提交申请</button></form><div class="common-unmodeled-layer" style="display:none"></div>';
function install(records){
 window.submissions=0;document.querySelector('form').onsubmit=e=>{e.preventDefault();submissions++};let owner=null,year=2026,month=10,mode='day',panel='',decade=2020;
 const layers=document.querySelector('.common-unmodeled-layer');
 document.querySelector('#sections').innerHTML=records.map(([wire,module,id,title,fields])=>`<section><div>${title}</div><div class="ux-standard-form" data-record="${id}">${fields.map(([label,,value,type])=>`<div class="form-item form-item--phoenix" data-kind="${type}"><div class="form-item__title"><span class="form-item__text">${label}</span></div>${type==='text'?`<input value="${value}">`:`<div class="phoenix-select"><span class="phoenix-select__content"></span><input class="phoenix-select__input" readonly></div>`}</div>`).join('')}${module==='project'?'<div class="phoenix-checkbox"><input type="checkbox"><span class="phoenix-checkbox__text">至今</span></div>':''}</div></section>`).join('');
 const close=()=>{document.querySelectorAll('.phoenix-select--active').forEach(n=>n.classList.remove('phoenix-select--active'));layers.style.display='none'};
 const commit=value=>{owner.querySelector('.phoenix-select__content').textContent=value;close()};
 const yearPanel=()=>`<div class="phoenix-calendar-year-panel"><button type="button" class="phoenix-calendar-year-panel-prev-decade-btn">前十年</button><span class="phoenix-calendar-year-panel-decade-select">${decade}-${decade+9}x</span><button type="button" class="phoenix-calendar-year-panel-next-decade-btn">后十年</button>${Array.from({length:12},(_,i)=>`<a class="phoenix-calendar-year-panel-year">${decade-1+i}</a>`).join('')}</div>`;
 const months=()=>`<div class="phoenix-calendar-month-panel">${mode==='month'?`<a class="phoenix-calendar-month-panel-year-select"><span class="phoenix-calendar-month-panel-year-select-content">${year}</span>x</a>`:''}${Array.from({length:12},(_,i)=>`<a class="phoenix-calendar-month-panel-month">${i+1}月</a>`).join('')}</div>`;
 const render=()=>{
  if(mode==='select'){layers.innerHTML='<div class="phoenix-selectList">'+['院校级','省区级','国家级','国际级'].map(v=>`<div class="phoenix-selectList__listItem"><span class="phoenix-selectList__singleLabel">${v}</span></div>`).join('')+'</div>';layers.querySelectorAll('.phoenix-selectList__listItem').forEach(n=>n.onclick=()=>commit(n.textContent));return;}
  layers.innerHTML=`<div class="phoenix-date-picker"><div class="phoenix-calendar${mode==='month'?' phoenix-calendar-month-calendar':''}">${mode==='day'?`<a class="phoenix-calendar-year-select">${year}年</a><a class="phoenix-calendar-month-select">${month}月</a>`:''}${panel==='year'?yearPanel():panel==='month'||mode==='month'?months():`<table><tr><td class="phoenix-calendar-cell phoenix-calendar-last-month-cell"><div class="phoenix-calendar-date">1</div></td>${Array.from({length:31},(_,i)=>`<td class="phoenix-calendar-cell"><div class="phoenix-calendar-date" aria-disabled="${i+1===29?'true':'false'}">${i+1}</div></td>`).join('')}<td class="phoenix-calendar-cell phoenix-calendar-next-month-btn-day"><div class="phoenix-calendar-date">1</div></td></tr></table>`}</div></div>`;
  const yearButton=layers.querySelector('.phoenix-calendar-year-select,.phoenix-calendar-month-panel-year-select');if(yearButton)yearButton.onclick=()=>{panel='year';decade=Math.floor(year/10)*10;render()};
  const monthButton=layers.querySelector('.phoenix-calendar-month-select');if(monthButton)monthButton.onclick=()=>{panel='month';render()};
  layers.querySelectorAll('.phoenix-calendar-year-panel-year').forEach(n=>n.onclick=()=>{year=Number(n.textContent);panel='';render()});
  for(const d of ['prev','next']){const b=layers.querySelector('.phoenix-calendar-year-panel-'+d+'-decade-btn');if(b)b.onclick=()=>{decade+=d==='prev'?-10:10;render()};}
  layers.querySelectorAll('.phoenix-calendar-month-panel-month').forEach(n=>n.onclick=()=>{month=parseInt(n.textContent);if(mode==='month')commit(year+'-'+String(month).padStart(2,'0'));else{panel='';render()}});
  layers.querySelectorAll('.phoenix-calendar-date').forEach(n=>n.onclick=()=>{if(n.getAttribute('aria-disabled')!=='true'&&!n.closest('.phoenix-calendar-last-month-cell'))commit(year+'-'+String(month).padStart(2,'0')+'-'+n.textContent.padStart(2,'0'))});
 };
 document.querySelectorAll('.form-item__title').forEach(n=>n.onclick=close);
 document.querySelectorAll('.phoenix-select__input').forEach(n=>n.onmousedown=()=>{close();owner=n.closest('.form-item');owner.querySelector('.phoenix-select').classList.add('phoenix-select--active');mode=owner.dataset.kind;panel='';year=2026;month=10;layers.style.display='block';render()});
 document.querySelectorAll('.phoenix-checkbox input').forEach(n=>n.onchange=()=>{const input=n.closest('.ux-standard-form').querySelectorAll('.phoenix-select__input')[1];input.disabled=n.checked});
}
let browser;
(async()=>{
 browser=await pw.chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const page=await browser.newPage();await page.route('https://fixture.invalid/**',r=>r.fulfill({body:html,contentType:'text/html'}));await page.goto('https://fixture.invalid/apply');await page.evaluate(install,records);
 for(const file of ['form-adapters.js','form-engine.js'])await page.addScriptTag({path:path.join(__dirname,'../app/assets',file)});
 let scan=await page.evaluate(()=>TouDiFormEngine.scan()),plan=C.plan(p,scan);assert(plan.groups.every(g=>g.status==='bound'),JSON.stringify({groups:plan.groups.map(g=>({label:g.label,module:g.module,status:g.status,candidates:g.candidates})),awards:scan.fields.filter(f=>f.module==='awards')}));assert.equal(plan.rows.find(r=>r.value==='至今').status,'ready');
 const ready=plan.rows.filter(r=>r.status==='ready');assert.equal(ready.length,10,JSON.stringify(plan.rows.map(r=>[r.label,r.status,r.reason])));
 const result=await page.evaluate(request=>TouDiFormEngine.apply(request),C.confirm(plan,ready.map(r=>r.fieldId)));assert.equal(result.summary.verified,10,JSON.stringify(result));
 scan=await page.evaluate(()=>TouDiFormEngine.scan());assert.equal(scan.fields.filter(f=>f.label==='获奖时间'&&!f.value).length,0);assert.equal(scan.fields.filter(f=>f.label==='获奖级别'&&!f.value).length,0);assert.equal(scan.fields.find(f=>f.label==='开始时间'&&f.module==='work').value,'2018-05');assert.equal(scan.fields.find(f=>f.label==='结束时间'&&f.module==='projects').value,'至今');assert.equal(C.plan(p,scan).rows.filter(r=>r.status==='conflict').length,0,'Month controls accept date facts without redundant overwrite');
 const target=scan.fields.find(f=>f.label==='获奖时间');const disabled=await page.evaluate(request=>TouDiFormEngine.apply(request),{protocol:1,origin:scan.origin,path:scan.path,fingerprint:scan.fingerprint,actions:[{fieldId:target.id,value:'2024-06-29',expectedValue:target.value,overwrite:true}]});assert.equal(disabled.results[0].reason,'date-day-disabled');assert.equal((await page.evaluate(()=>TouDiFormEngine.scan())).fields.find(f=>f.id===target.id).value,target.value);
 assert.equal(await page.evaluate(()=>submissions),0);console.log('PASS Phoenix date/award protocol: exact start/end records, decade suffix, month/year/day clicks, 3 award dates and semantic levels, ongoing checkbox, disabled day refusal, month precision readback, zero submission');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>browser?.close());
