'use strict';
// Browser plugin not available. Exercise the existing UI with isolated synthetic data.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const {spawn}=require('node:child_process'),{once}=require('node:events');
let pw;try{pw=require('playwright')}catch(_){pw=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const root=path.resolve(__dirname,'..'),workspace=fs.mkdtempSync(path.join(os.tmpdir(),'toudi-calendar-layout-'));
const out=process.env.TOUDI_SCHEDULE_EVIDENCE||os.tmpdir(),token=crypto.randomBytes(32).toString('hex');let service,browser;
const write=(name,value)=>{const dest=path.join(workspace,name);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,JSON.stringify(value));};
const date=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const job='产品与业务研究岗\n职责一：完整记录业务需求与处理流程。\n职责二：与团队合作完成研究、验证和交付。';
const record=i=>({名称:'示例企业'+String(i+1).padStart(2,'0'),岗位:i===0?job:'研究与产品岗位',地点:'上海、苏州',应届生:'2027 届',学历要求:'硕士研究生及以上',性质:'国有企业',行业:'信息技术与专业服务',录入时间:date,截止时间:date,校招类型:'校园招聘',公告链接:'https://example.com/announcement','网申链接/邮箱':'https://example.com/apply'});
const events=[{id:'test-meeting',title:'示例企业01 · 面试',type:'interview',status:'planned',allDay:false,start:date+'T14:00:00+08:00',end:date+'T15:00:00+08:00',timeZone:'Asia/Shanghai',companyKey:'示例企业01',notes:'完整原始备注。\n逐字保留第二行。',syncToCalendar:false}];
write('投递数据/投递记录.json',Array.from({length:20},(_,i)=>record(i)).concat({...record(20),截止时间:'日期待定'}));
write('投递数据/日程数据.json',{schemaVersion:1,timeZone:'Asia/Shanghai',calendar:{enabled:false,calendarId:''},events});
write('投递数据/面试准备数据.json',{preps:[]});
write('投递数据/面试复盘数据.json',{sessions:[]});
(async()=>{
 fs.mkdirSync(out,{recursive:true});
 const command=process.env.TOUDI_TEST_RUNTIME||'python3',args=process.env.TOUDI_TEST_RUNTIME?['serve']:[path.join(root,'app/desktop_runtime.py'),'serve'];
 service=spawn(command,args,{env:{...process.env,TOUDI_WORKSPACE:workspace,TOUDI_APP_HOME:path.join(workspace,'config'),TOUDI_DESKTOP_TOKEN:token,TOUDI_PORT:'0'},stdio:['pipe','pipe','pipe']});
 let logs='',line='';service.stderr.on('data',chunk=>logs+=chunk);
 const signal=await new Promise((resolve,reject)=>{service.stdout.on('data',chunk=>{line+=chunk;try{resolve(JSON.parse(line.split('\n')[0]));}catch(_){}});service.once('exit',code=>reject(Error('Runtime exited '+code+' '+logs)));});
 const origin='http://127.0.0.1:'+signal.port;
 browser=await pw.chromium.launch({headless:true,executablePath:process.env.TOUDI_CHROMIUM});
 const context=await browser.newContext({viewport:{width:1249,height:891},extraHTTPHeaders:{Authorization:'Bearer '+token}}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const current=async module=>(await context.request.get(origin+'/api/manage?module='+module)).json();
 const commit=async(module,extra)=>{const base=await current(module);const response=await context.request.post(origin+'/api/manage',{data:{module,base:base.version,workspaceKey:base.workspaceKey,...extra},headers:{Origin:origin}});assert(response.ok(),await response.text());return response.json();};
 await commit('preps',{action:'upsert',item:{id:'example-prep',company:'示例企业01',companyKey:'示例企业01',position:'岗位准备原文',structured:true,markdown:'## 面试准备\n\n完整准备内容。'}});
 const monthRows=()=>page.locator('#scheduleCalendar [role="rowgroup"]>[role="row"]:has(>[role="gridcell"][data-date])').evaluateAll(rows=>rows.map(el=>{const rect=el.getBoundingClientRect();return {y:rect.y,height:rect.height,cells:el.querySelectorAll('[role="gridcell"][data-date]').length};}));
 const checkMonth=async label=>{await page.waitForTimeout(350);const rows=await monthRows();assert.equal(rows.length,6,label);assert(rows.every(row=>row.cells===7));assert(Math.max(...rows.map(row=>row.height))-Math.min(...rows.map(row=>row.height))<.2,label+': equal edge/middle weeks');for(let i=1;i<rows.length;i++)assert(Math.abs(rows[i].y-rows[i-1].y-rows[i-1].height)<.2,label+': no gaps/overlap');return rows;};
 await page.goto(origin+'/投递管理.html');await page.waitForFunction(()=>serverMode&&data.length===21);
 await page.locator('[data-module="schedule"]').click();await page.waitForFunction(()=>!!document.querySelector('[data-schedule-event]'));
 const allDay=await page.locator('#scheduleCalendar [role="row"]:has(>.schedule-all-day-header)').boundingBox();assert(allDay&&allDay.height<=100,'Crowded all-day band is bounded');
 await page.locator('.schedule-more').filter({hasText:'+18 项'}).click();await page.locator('.schedule-popover').waitFor();
 assert.equal(await page.locator('.schedule-popover [data-schedule-event]').count(),20,'Overflow retains all source deadlines');
 await page.locator('.schedule-popover [data-schedule-event="deadline:示例企业20"]').click();await page.getByRole('button',{name:'查看招聘详情',exact:true}).click();
 await page.locator('#detailModal').waitFor({state:'visible'});assert.equal(await page.locator('#detailTitle').textContent(),'示例企业20');
 await page.locator('.detail-nav').getByRole('button',{name:'关闭',exact:true}).click();
 await page.locator('[data-schedule="cancel"]').first().click();
 await page.locator('[data-schedule-mode="dayGridMonth"]').click();const initialRows=await checkMonth('crowded current month');
 await page.screenshot({path:path.join(out,'日历_等高月历.png')});
 const months=[initialRows];for(let i=0;i<3;i++){await page.locator('[data-schedule="next"]').click();months.push(await checkMonth('next month '+i));}
 // Resize and reopen are essential: the original defect depended on content and container size.
 await page.setViewportSize({width:1536,height:1024});await checkMonth('wide month');await page.setViewportSize({width:1024,height:768});await checkMonth('compact month');
 assert.equal(await page.evaluate(()=>document.body.scrollWidth>innerWidth),false);
 await page.locator('[data-module="delivery"]').click();await page.locator('[data-module="schedule"]').click();await checkMonth('reopened month');
 await page.setViewportSize({width:1249,height:891});await page.locator('[data-module="delivery"]').click();await page.evaluate(()=>showDetail(0));await page.waitForTimeout(350);
 await page.locator('[data-detail-event="test-meeting"]').waitFor();
 assert.equal(await page.locator('#detailRecruitment .detail-fact.wide dd').first().textContent(),job,'Original role text is intact');
 assert.equal(await page.locator('#detailContent>[role=tabpanel]:visible').count(),1);
 assert(await page.locator('#detailContent').evaluate(el=>el.scrollHeight<=el.clientHeight),'Typical recruitment detail fits without scrolling');
 await page.screenshot({path:path.join(out,'详情_招聘信息.png')});
 await page.locator('#tab-detailFollowup').click();await page.locator('#researchNote').fill('尚未保存的原始核实内容。');
 await page.locator('#tab-detailMaterials').click();await page.locator('#detailMaterials .detail-linked button').filter({hasText:'岗位准备原文'}).waitFor();
 await page.screenshot({path:path.join(out,'详情_准备与复盘.png')});
 await page.locator('#tab-detailMaterials').press('ArrowLeft');assert.equal(await page.locator('#tab-detailFollowup').getAttribute('aria-selected'),'true');
 assert.equal(await page.locator('#researchNote').inputValue(),'尚未保存的原始核实内容。');
 await page.locator('#detailFollowup').getByRole('button',{name:'收藏',exact:true}).click();await page.waitForFunction(()=>byId(0)._starred);assert.equal(await page.locator('#researchNote').inputValue(),'尚未保存的原始核实内容。');
 assert.equal(await page.locator('#tab-detailFollowup').getAttribute('aria-selected'),'true','Status/mark refresh preserves the active tab and draft');
 await page.locator('#tab-detailRecruitment').click();await page.locator('#detailSourceInfo>summary').click();
 assert(await page.locator('#detailSourceInfo').getAttribute('open')!==null);await page.locator('#detailRecruitment').getByRole('button',{name:'修改信息',exact:true}).click();
 assert.equal(await page.locator('#fe_岗位').inputValue(),job);await page.locator('#detailRecruitment').getByRole('button',{name:'收起修改',exact:true}).click();
 assert.equal(await page.locator('#detailRecruitment .detail-fact.wide dd').first().textContent(),job);
 await page.locator('.detail-entry-actions').getByRole('button',{name:'添加到日历',exact:true}).click();
 await page.locator('#scheduleForm').waitFor();assert.equal(await page.locator('#scheduleForm [name=companyKey]').inputValue(),'示例企业01');
 assert.equal(await page.locator('#scheduleForm [name=date]').inputValue(),date);assert.equal(await page.locator('#scheduleForm [name=type]').inputValue(),'application');
 assert(await page.locator('#scheduleForm [name=allDay]').isChecked());assert.equal((await current('schedule')).data.events.length,1,'Navigation alone does not create an event');
 await page.locator('#scheduleForm [name=title]').fill('详情添加的投递计划');await page.locator('#scheduleForm [type=submit]').click();await page.getByText('日程已保存',{exact:true}).waitFor();
 const added=(await current('schedule')).data.events.find(event=>event.title==='详情添加的投递计划');assert.equal(added.companyKey,'示例企业01');assert.equal(added.start,date);
 await page.locator('[data-schedule-mode="agenda"]').click();await page.locator('#scheduleAgenda [data-schedule-id="'+added.id+'"]').click();
 await page.locator('.schedule-record-link').click();await page.locator('[data-detail-event="'+added.id+'"]').waitFor();
 await page.locator('[data-detail-event="test-meeting"]').click();await page.waitForFunction(()=>document.querySelector('#scheduleForm [name=title]')?.value==='示例企业01 · 面试');assert.equal(await page.locator('#scheduleForm [name=notes]').inputValue(),events[0].notes,'Detail-to-calendar retains full event notes');
 await page.locator('[data-schedule="cancel"]').first().click();
 await page.locator('[data-module="delivery"]').click();await page.evaluate(()=>showDetail(20));await page.getByRole('button',{name:'添加到日历',exact:true}).click();
 assert.equal(await page.locator('#scheduleForm [name=companyKey]').inputValue(),'示例企业21');assert.equal(await page.locator('#scheduleForm [name=scheduled]').isChecked(),false,'Unknown deadline does not fabricate a date');
 await page.locator('[data-schedule="cancel"]').first().click();await page.locator('[data-schedule-mode="timeGridWeek"]').click();await page.locator('[data-schedule="today"]').click();
 await page.waitForTimeout(350);await page.screenshot({path:path.join(out,'日历_受控全天栏.png')});
 await page.evaluate(()=>chooseTheme('dark'));await page.waitForTimeout(350);await page.locator('[data-module="delivery"]').click();await page.evaluate(()=>showDetail(0));await page.waitForTimeout(350);await page.screenshot({path:path.join(out,'详情_深色.png')});
 await page.evaluate(()=>chooseTheme('light'));await page.setViewportSize({width:390,height:844});await page.waitForTimeout(350);
 assert.equal(await page.evaluate(()=>document.body.scrollWidth>innerWidth),false);assert((await page.locator('.detail-entry-actions button').boundingBox()).width>70);
 assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(out,'日历与详情交互验收.json'),JSON.stringify({version:signal.version,allDayHeight:allDay.height,monthRows:months,errors,checks:['bounded all-day overflow and all 20 entries retained','equal first/middle/last month rows across four months, two resizes and reopen','deadline-to-correct-recruitment-detail','one active detail panel, original full text','related preparation loaded','tab keyboard navigation and unsaved text preservation','favorites preserve active panel','field editing preserves full original','detail-to-calendar proposal then persisted save','own event-to-recruitment and reverse navigation','unknown deadline remains unplanned','dark theme and narrow layout']},null,2));
 console.log('PASS '+signal.version+' calendar geometry and recruitment detail workflow');
})().catch(async error=>{console.error(error);for(const context of browser?.contexts()||[])for(const page of context.pages()){console.error((await page.locator('body').innerText()).slice(-2000));await page.screenshot({path:path.join(out,'日历详情_失败.png')}).catch(()=>{});}process.exitCode=1;}).finally(async()=>{await browser?.close();if(service&&service.exitCode===null){service.stdin.write('shutdown\n');await once(service,'exit');}fs.rmSync(workspace,{recursive:true,force:true});});
