'use strict';
// Browser plugin not available. Exercise the existing UI with isolated synthetic data.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const {spawn}=require('node:child_process'),{once}=require('node:events');
let pw;try{pw=require('playwright')}catch(_){pw=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const root=path.resolve(__dirname,'..'),workspace=fs.mkdtempSync(path.join(os.tmpdir(),'toudi-calendar-layout-'));
const out=process.env.TOUDI_SCHEDULE_EVIDENCE||os.tmpdir(),token=crypto.randomBytes(32).toString('hex');let service,browser;
const write=(name,value)=>{const dest=path.join(workspace,name);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,JSON.stringify(value));};
const date=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const job='产品与业务研究岗\n职责一：完整记录业务需求与处理流程。\n职责二：与团队合作完成研究、验证和交付。';
const record=i=>({名称:'示例企业'+String(i+1).padStart(2,'0'),岗位:i===0?job:'研究与产品岗位',地点:'上海、苏州',应届生:'2027 届',学历要求:'硕士研究生及以上',性质:'国有企业',行业:'信息技术与专业服务',录入时间:date,截止时间:date,校招类型:'校园招聘',公告链接:'https://example.com/announcement','网申链接/邮箱':'https://example.com/apply'});
const events=[{id:'test-meeting',title:'示例企业01 · 面试',type:'interview',status:'planned',allDay:false,start:date+'T14:00:00+08:00',end:date+'T15:00:00+08:00',timeZone:'Asia/Shanghai',companyKey:'示例企业01',notes:'完整原始备注。\n逐字保留第二行。',syncToCalendar:false}];
write('投递数据/投递记录.json',Array.from({length:20},(_,i)=>record(i)).concat({...record(20),截止时间:'日期待定'}));
write('投递数据/日程数据.json',{schemaVersion:1,timeZone:'Asia/Shanghai',calendar:{enabled:false,calendarId:''},events});
write('投递数据/面试准备数据.json',{preps:[]});
write('投递数据/面试复盘数据.json',{sessions:[{id:'example-review',company:'示例企业01',companyKey:'示例企业01',position:'研究岗位',date:date,round:'一面',summary:{raw:'完整原始复盘总结。'},questions:[]}]});
write('岗位探查/探查目录.json',{companies:[{id:'example-prospect',company:'示例企业01',title:'示例企业01 岗位探查',researchedAt:date,file:'example.md'}]});
fs.writeFileSync(path.join(workspace,'岗位探查/example.md'),'# 示例企业01 岗位探查\n\n## 结论\n完整的合成探查原文。');
(async()=>{
 fs.mkdirSync(out,{recursive:true});
 const command=process.env.TOUDI_TEST_RUNTIME||'python3',args=process.env.TOUDI_TEST_RUNTIME?['serve']:[path.join(root,'app/desktop_runtime.py'),'serve'];
 service=spawn(command,args,{env:{...process.env,TOUDI_WORKSPACE:workspace,TOUDI_APP_HOME:path.join(workspace,'config'),TOUDI_DESKTOP_TOKEN:token,TOUDI_PORT:'0'},stdio:['pipe','pipe','pipe']});
 let logs='',line='';service.stderr.on('data',chunk=>logs+=chunk);
 const signal=await new Promise((resolve,reject)=>{service.stdout.on('data',chunk=>{line+=chunk;try{resolve(JSON.parse(line.split('\n')[0]));}catch(_){}});service.once('exit',code=>reject(Error('Runtime exited '+code+' '+logs)));});
 const origin='http://127.0.0.1:'+signal.port;
 browser=await pw.chromium.launch({headless:true,executablePath:process.env.TOUDI_CHROMIUM});
 const context=await browser.newContext({viewport:{width:1249,height:891},extraHTTPHeaders:{Authorization:'Bearer '+token}}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const current=async module=>(await context.request.get(origin+'/api/manage?module='+module)).json();
 const commit=async(module,extra)=>{const base=await current(module);const response=await context.request.post(origin+'/api/manage',{data:{module,base:base.version,workspaceKey:base.workspaceKey,...extra},headers:{Origin:origin}});assert(response.ok(),await response.text());return response.json();};
 await commit('preps',{action:'upsert',item:{id:'example-prep',company:'示例企业01',companyKey:'示例企业01',position:'岗位准备原文',structured:true,markdown:'## 面试准备\n\n完整准备内容。'}});
 const monthRows=()=>page.locator('#scheduleCalendar [role="rowgroup"]>[role="row"]:has(>[role="gridcell"][data-date])').evaluateAll(rows=>rows.map(el=>{const rect=el.getBoundingClientRect();return {y:rect.y,height:rect.height,cells:el.querySelectorAll('[role="gridcell"][data-date]').length};}));
 const checkMonth=async label=>{await page.waitForTimeout(350);const rows=await monthRows();assert.equal(rows.length,6,label);assert(rows.every(row=>row.cells===7));assert(Math.max(...rows.map(row=>row.height))-Math.min(...rows.map(row=>row.height))<.2,label+': equal edge/middle weeks');for(let i=1;i<rows.length;i++)assert(Math.abs(rows[i].y-rows[i-1].y-rows[i-1].height)<.2,label+': no gaps/overlap');return rows;};
 await page.goto(origin+'/投递管理.html');await page.waitForFunction(()=>serverMode&&data.length===21);
 assert.equal(await page.title(),'TouDi · 投递中控台');assert(new URL(page.url()).pathname.endsWith('投递管理.html')||decodeURI(new URL(page.url()).pathname).endsWith('投递管理.html'));
 assert.equal(await page.locator('#deliverySearchEntry,#settingsShortcut,#managementEntry').count(),0,'No duplicate global controls');
 assert.equal(await page.locator('.topbar-actions .theme-toolbar').count(),0);assert(await page.locator('.sb-footer .theme-mode-control').isVisible());
 assert.deepEqual(await page.locator('.theme-mode-control button').evaluateAll(buttons=>buttons.map(el=>el.getAttribute('aria-label'))),['浅色','深色','跟随电脑']);
 assert.equal(await page.locator('#themeMenu,#themeMenuButton,#themeQuickToggle').count(),0);
 assert(await page.locator('#storageBadge').isHidden(),'Healthy connection does not occupy the sidebar');
 for(const mode of ['light','dark','system']){
   await page.locator('.theme-mode-control [data-theme="'+mode+'"]').click();
   await page.waitForFunction(mode=>workspace.theme===mode,mode);
   assert.equal(await page.locator('.theme-mode-control [aria-pressed=true]').getAttribute('data-theme'),mode);
 }
 await page.emulateMedia({colorScheme:'dark'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');
 assert.equal(await page.locator('.theme-mode-control [aria-pressed=true]').getAttribute('data-theme'),'system','System follows the computer without switching the selected mode');
 await page.emulateMedia({colorScheme:'light'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');
 await page.locator('.theme-mode-control [data-theme=light]').focus();await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>workspace.theme==='dark');
 await page.locator('.theme-mode-control [data-theme=light]').click();
 await page.waitForFunction(()=>workspaceSettingsSaving===0);
 await page.evaluate(()=>{for(const mode of ['dark','system','light'])document.querySelector('.theme-mode-control [data-theme="'+mode+'"]').click();});
 await page.waitForFunction(()=>workspaceSettingsSaving===0);
 assert.equal((await current('settings')).data.display.theme,'light','Rapid icon switching persists the final choice');
 assert.equal(await page.evaluate(()=>toudiWorkspaceStorage.getItem('toudiPendingSettings')),null,'Rapid switching leaves no failed settings draft');
 await page.evaluate(()=>{SAVE_DOMAINS.edits.state='error';SAVE_DOMAINS.edits.message='合成读取失败';SAVE_DOMAINS.edits.readFailed=true;updateStorageBadge();});
 assert(await page.locator('#storageBadge').isVisible());assert.equal(await page.locator('#storageBadge').innerText(),'合成读取失败');
 await page.evaluate(()=>{SAVE_DOMAINS.edits.state='saving';SAVE_DOMAINS.edits.readFailed=false;updateStorageBadge();});assert(await page.locator('#storageBadge').isHidden(),'Ordinary saves do not flash a sidebar banner');
 await page.evaluate(()=>{SAVE_DOMAINS.edits.state='idle';serverMode=false;updateStorageBadge();});assert(await page.locator('#storageBadge').isVisible());assert((await page.locator('#storageBadge').innerText()).includes('未连接'));
 await page.evaluate(()=>{serverMode=true;updateStorageBadge();});assert(await page.locator('#storageBadge').isHidden());
 assert(await page.locator('#workspaceUpdatesButton').isHidden());assert(await page.locator('#moduleImportButton').isHidden());
 const toolbar=await page.locator('#dashboardToolbar').boundingBox(),overview=await page.locator('#recordsOverview').boundingBox(),table=await page.locator('.table-wrap').boundingBox();
 assert(toolbar.height<=30,'Count and columns share a compact row');assert(table.y-overview.y-overview.height<=52,'No oversized gap before the table');
 await page.locator('#recordDataEntry').click();await page.locator('#managementOverlay').waitFor({state:'visible'});
 assert.equal(await page.locator('#managementForm [data-mfield="名称"]').inputValue(),'');
 assert.deepEqual(await page.locator('#managementTools [role=tab]').allTextContents(),['新增记录','导入 / 导出']);
 assert.equal(await page.locator('.management-list').count(),0,'No full-list record editor');
 assert.equal(await page.locator('#managementOverlay').getByRole('button',{name:'检查与预览',exact:true}).count(),0);
 await page.locator('#recordTransferTab').click();assert.equal(await page.locator('#managementBody input[type=file]').count(),1,'Import is a distinct task');
 assert(await page.locator('#managementOverlay').getByRole('button',{name:'导出记录',exact:true}).isVisible());
 assert.equal(await page.locator('#managementOverlay').getByRole('button',{name:/导出完整规范|导出当前草稿|交给 Agent/}).count(),0);
 await page.locator('#managementOverlay').getByRole('button',{name:'关闭',exact:true}).click();
 await page.waitForFunction(()=>document.getElementById('workspaceUpdatesButton').hidden);
 assert(await page.locator('.sb-footer .theme-mode-control').evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;}));
 await page.screenshot({path:path.join(out,'投递管理_紧凑工具行.png')});
 await page.locator('[data-module="schedule"]').click();await page.waitForFunction(()=>!!document.querySelector('[data-schedule-event]'));
 const allDay=await page.locator('#scheduleCalendar [role="row"]:has(>.schedule-all-day-header)').boundingBox();assert(allDay&&allDay.height<=100,'Crowded all-day band is bounded');
 await page.locator('.schedule-more').filter({hasText:'+18 项'}).click();await page.locator('.schedule-popover').waitFor();
 assert.equal(await page.locator('.schedule-popover [data-schedule-event]').count(),20,'Overflow retains all source deadlines');
 await page.locator('.schedule-popover [data-schedule-event="deadline:示例企业20"]').click();await page.getByRole('button',{name:'查看招聘详情',exact:true}).click();
 await page.locator('#detailModal').waitFor({state:'visible'});assert.equal(await page.locator('#detailTitle').textContent(),'示例企业20');
 await page.locator('.detail-nav').getByRole('button',{name:'关闭',exact:true}).click();
 await page.locator('[data-schedule="cancel"]').first().click();
 await page.locator('[data-schedule-mode="dayGridMonth"]').click();const initialRows=await checkMonth('crowded current month');
 await page.screenshot({path:path.join(out,'日历_等高月历.png')});
 const months=[initialRows];for(let i=0;i<3;i++){await page.locator('[data-schedule="next"]').click();months.push(await checkMonth('next month '+i));}
 // Resize and reopen are essential: the original defect depended on content and container size.
 await page.setViewportSize({width:1536,height:1024});await checkMonth('wide month');await page.setViewportSize({width:1024,height:768});await checkMonth('compact month');
 assert.equal(await page.evaluate(()=>document.body.scrollWidth>innerWidth),false);
 await page.locator('[data-module="delivery"]').click();await page.locator('[data-module="schedule"]').click();await checkMonth('reopened month');
 await page.setViewportSize({width:1249,height:891});await page.locator('[data-module="delivery"]').click();await page.evaluate(()=>showDetail(0));await page.waitForTimeout(350);
 await page.locator('[data-detail-event="test-meeting"]').waitFor();
 assert.equal(await page.locator('#detailRecruitment .detail-fact.wide dd').first().textContent(),job,'Original role text is intact');
 assert.equal(await page.locator('#detailContent [role=tabpanel],#detailLead [role=tab]').count(),0);
 assert.equal(await page.locator('#detailContent>.detail-section:visible').count(),3);
 assert.deepEqual(await page.locator('[data-material]').allTextContents(),['岗位探查','面试准备','面试复盘']);
 assert.equal(await page.locator('#detailMaterials small,.detail-secondary-links').count(),0,'Company details contain no material counters or duplicate global links');
 assert.equal((await page.locator('#detailNotes>summary').textContent()).trim(),'跟进记录');
 const detailControls=await page.locator('.detail-progress-row').evaluate(row=>{
   const select=row.querySelector('select'),arrow=row.querySelector('.detail-status-control>svg'),r=select.getBoundingClientRect(),a=arrow.getBoundingClientRect();
   return {heights:[...row.querySelectorAll('select,button')].map(el=>el.getBoundingClientRect().height),arrowOffset:Math.abs(a.y+a.height/2-r.y-r.height/2),arrowRight:r.right-a.right,appearance:getComputedStyle(select).appearance};
 });
 assert(detailControls.heights.every(height=>height===34),'Progress selector and adjacent actions share the same height');
 assert(detailControls.arrowOffset<.5&&detailControls.arrowRight>=10&&detailControls.appearance==='none','Dropdown arrow is centered with intentional right padding');
 assert((await page.locator('[data-material="prep"]').boundingBox()).height===34,'Company material navigation uses the shared compact control');
 await page.locator('#detailStatus').selectOption('已投递');await page.waitForFunction(()=>byId(0)._status==='已投递'&&!editsSaveInFlight);
 assert.equal(await page.locator('#detailStatus').inputValue(),'已投递','Native status selection still changes the real record');
 assert(await page.locator('#detailContent').evaluate(el=>el.scrollHeight<=el.clientHeight),'Typical recruitment detail fits without scrolling');
 await page.screenshot({path:path.join(out,'详情_招聘信息.png')});
 await page.locator('#detailNotes>summary').click();await page.locator('#researchNote').fill('尚未保存的原始核实内容。');
 await page.screenshot({path:path.join(out,'详情_展开跟进记录.png')});
 assert.equal(await page.locator('#researchNote').inputValue(),'尚未保存的原始核实内容。');
 await page.locator('#detailFollowup').getByRole('button',{name:'收藏',exact:true}).click();await page.waitForFunction(()=>byId(0)._starred);assert.equal(await page.locator('#researchNote').inputValue(),'尚未保存的原始核实内容。');
 assert(await page.locator('#detailNotes').evaluate(el=>el.open),'Mark refresh preserves expanded notes and draft');
 await page.locator('[data-material="prep"]').click();await page.waitForFunction(()=>view==='qbank'&&currentQbCat==='prep:example-prep');assert(await page.locator('#qbMain').innerText().then(t=>t.includes('完整准备内容')));
 await page.locator('#qbView').getByRole('button',{name:'返回投递',exact:true}).click();await page.evaluate(()=>showDetail(0));
 assert.equal(await page.locator('#researchNote').inputValue(),'尚未保存的原始核实内容。','Material navigation preserves the follow-up draft');
 await page.locator('[data-material="prospect"]').click();await page.waitForFunction(()=>view==='prospect'&&currentProspectId==='example-prospect');assert(await page.locator('#prospectMain').innerText().then(t=>t.includes('完整的合成探查原文')));
 await page.locator('#prospectView').getByRole('button',{name:'返回投递',exact:true}).click();await page.evaluate(()=>showDetail(0));
 await page.evaluate(()=>{reviewTab='weakness';reviewSearch='不相关公司';});
 await page.locator('[data-material="review"]').click();await page.waitForFunction(()=>view==='review'&&reviewTab==='sessions'&&currentReviewId==='example-review');
 assert(await page.locator('#reviewMain').innerText().then(t=>t.includes('完整原始复盘总结')));
 await page.locator('#reviewView').getByRole('button',{name:'返回投递',exact:true}).click();await page.evaluate(()=>showDetail(0));
 await page.locator('#detailSourceInfo>summary').click();
 assert(await page.locator('#detailSourceInfo').getAttribute('open')!==null);await page.locator('#detailRecruitment').getByRole('button',{name:'修改信息',exact:true}).click();
 assert.equal(await page.locator('#fe_岗位').inputValue(),job);await page.locator('#detailRecruitment').getByRole('button',{name:'收起修改',exact:true}).click();
 assert.equal(await page.locator('#detailRecruitment .detail-fact.wide dd').first().textContent(),job);
 await page.locator('.detail-entry-actions').getByRole('button',{name:'添加日程',exact:true}).click();
 await page.locator('#scheduleForm').waitFor();assert.equal(await page.locator('#scheduleForm [name=companyKey]').inputValue(),'示例企业01');
 assert.equal(await page.locator('#scheduleForm [name=date]').inputValue(),date);assert.equal(await page.locator('#scheduleForm [name=type]').inputValue(),'application');
 assert(await page.locator('#scheduleForm [name=allDay]').isChecked());assert.equal((await current('schedule')).data.events.length,1,'Navigation alone does not create an event');
 await page.locator('#scheduleForm [name=title]').fill('详情添加的投递计划');await page.locator('#scheduleForm [type=submit]').click();await page.getByText('日程已保存',{exact:true}).waitFor();
 const added=(await current('schedule')).data.events.find(event=>event.title==='详情添加的投递计划');assert.equal(added.companyKey,'示例企业01');assert.equal(added.start,date);
 await page.locator('[data-schedule-mode="agenda"]').click();await page.locator('#scheduleAgenda [data-schedule-id="'+added.id+'"]').click();
 await page.locator('.schedule-record-link').click();await page.locator('[data-detail-event="'+added.id+'"]').waitFor();
 await page.locator('[data-detail-event="test-meeting"]').click();await page.waitForFunction(()=>document.querySelector('#scheduleForm [name=title]')?.value==='示例企业01 · 面试');assert.equal(await page.locator('#scheduleForm [name=notes]').inputValue(),events[0].notes,'Detail-to-calendar retains full event notes');
 await page.locator('[data-schedule="cancel"]').first().click();
 await page.locator('[data-module="delivery"]').click();await page.evaluate(()=>showDetail(20));await page.getByRole('button',{name:'添加日程',exact:true}).click();
 assert.equal(await page.locator('#scheduleForm [name=companyKey]').inputValue(),'示例企业21');assert.equal(await page.locator('#scheduleForm [name=scheduled]').isChecked(),false,'Unknown deadline does not fabricate a date');
 await page.locator('[data-schedule="cancel"]').first().click();await page.locator('[data-schedule-mode="timeGridWeek"]').click();await page.locator('[data-schedule="today"]').click();
 await page.waitForTimeout(350);await page.screenshot({path:path.join(out,'日历_受控全天栏.png')});
 await page.evaluate(()=>chooseTheme('dark'));await page.waitForTimeout(350);await page.locator('[data-module="delivery"]').click();await page.evaluate(()=>showDetail(0));await page.waitForTimeout(350);await page.screenshot({path:path.join(out,'详情_深色.png')});
 await page.evaluate(()=>chooseTheme('light'));await page.setViewportSize({width:390,height:844});await page.waitForTimeout(350);
 assert.equal(await page.evaluate(()=>document.body.scrollWidth>innerWidth),false);assert((await page.locator('.detail-entry-actions button').boundingBox()).width>70);
 // Actual data exchange uses the public service, with no separate preview step for one record.
 await page.locator('.detail-nav').getByRole('button',{name:'关闭',exact:true}).click();await page.setViewportSize({width:1249,height:891});
 await page.locator('#recordDataEntry').click();await page.locator('#managementOverlay').waitFor({state:'visible'});
 await page.locator('#managementSubmit').click();assert((await page.locator('#managementStatus').innerText()).includes('名称不能为空'));assert.equal((await current('records')).data.length,21);
 await page.locator('[data-mfield="名称"]').fill('合成新增企业');await page.locator('[data-mfield="岗位"]').fill(job);
 await page.locator('[data-mfield="地点"]').fill('合成城市');
 await page.locator('#recordTransferTab').click();await page.locator('#recordNewTab').click();assert.equal(await page.locator('[data-mfield="岗位"]').inputValue(),job,'Switching tasks preserves the full new-record draft');
 await page.screenshot({path:path.join(out,'新增记录_完整表单.png')});
 await page.locator('#managementSubmit').click();await page.locator('#managementOverlay').waitFor({state:'hidden'});
 const addedRecords=(await current('records')).data;assert.equal(addedRecords.length,22);assert.equal(addedRecords.at(-1).岗位,job);
 await page.locator('#recordDataEntry').click();await page.locator('#recordTransferTab').click();
 const downloadPromise=page.waitForEvent('download');await page.locator('#managementOverlay').getByRole('button',{name:'导出记录',exact:true}).click();const exported=await downloadPromise;
 assert.equal(exported.suggestedFilename(),'招聘记录.json');const exportedRows=JSON.parse(fs.readFileSync(await exported.path(),'utf8'));assert.deepEqual(exportedRows,addedRecords,'Export contains saved records, not UI rows or drafts');
 await page.locator('#managementBody input[type=file]').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({records:[]}))});
 assert((await page.locator('#managementStatus').innerText()).includes('JSON 数组'));assert.equal((await current('records')).data.length,22);
 const incoming=addedRecords.concat({...record(22),名称:'合成导入企业',岗位:job});
 await page.locator('#managementBody input[type=file]').setInputFiles({name:'招聘记录.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(incoming))});
 await page.locator('#managementSubmit').waitFor();await page.waitForFunction(()=>!document.getElementById('managementSubmit').disabled);
 assert((await page.locator('#managementPreview').innerText()).includes('替换当前 22 条'));assert.equal(await page.locator('#managementPreview tbody tr').count(),5,'Import preview stays bounded');
 assert.equal((await current('records')).data.length,22,'Preview never writes records');
 await page.screenshot({path:path.join(out,'导入导出_明确范围.png')});
 await page.locator('#managementSubmit').click();await page.locator('#managementOverlay').waitFor({state:'hidden'});
 assert.deepEqual((await current('records')).data,incoming,'Explicit import confirmation persists the full file');
 // Thousands of records must not generate a second list inside this task dialog.
 await commit('records',{action:'replace',data:Array.from({length:5000},(_,i)=>record(i))});await page.evaluate(()=>refreshWorkspaceData(true));
 const openStarted=Date.now();await page.locator('#recordDataEntry').click();await page.locator('#managementOverlay').waitFor({state:'visible'});const recordDialogMs=Date.now()-openStarted;
 const recordDialogElements=await page.locator('#managementOverlay *').count();assert(recordDialogElements<120,'Record task DOM stays bounded with 5,000 source rows');assert.equal(await page.locator('.management-list').count(),0);
 await page.locator('#managementOverlay').getByRole('button',{name:'关闭',exact:true}).click();
 await page.reload();await page.waitForFunction(()=>serverMode&&data.length===5000);assert.equal(await page.locator('.theme-mode-control [aria-pressed=true]').getAttribute('data-theme'),'light','Theme persists after reopening the page');
 assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(out,'日历与详情交互验收.json'),JSON.stringify({version:signal.version,toolbar,overview,table,recordDialogMs,recordDialogElements,allDayHeight:allDay.height,monthRows:months,errors,checks:['single global setting/filter entry and idle status hidden','three icon appearance modes, keyboard control, system media and persistence','healthy and saving connection badges hidden, errors/disconnection visible','compact result row and manual new/import/export tasks without a full record list','one-click record save retains complete text','fresh JSON export equals saved records','bounded import preview does not write before confirmation','explicit full-file import and 5,000-row bounded dialog','bounded all-day overflow and all 20 entries retained','equal first/middle/last month rows across four months, two resizes and reopen','deadline-to-correct-recruitment-detail','continuous detail sections, original full text','company preparation/prospect/review open the correct real module','notes and disclosure survive marks and material navigation','field editing preserves full original','detail-to-schedule proposal then persisted save','own event-to-recruitment and reverse navigation','unknown deadline remains unplanned','dark theme and narrow layout']},null,2));
 console.log('PASS '+signal.version+' calendar geometry and recruitment detail workflow');
})().catch(async error=>{console.error(error);for(const context of browser?.contexts()||[])for(const page of context.pages()){console.error((await page.locator('body').innerText()).slice(-2000));await page.screenshot({path:path.join(out,'日历详情_失败.png')}).catch(()=>{});}process.exitCode=1;}).finally(async()=>{await browser?.close();if(service&&service.exitCode===null){service.stdin.write('shutdown\n');await once(service,'exit');}fs.rmSync(workspace,{recursive:true,force:true});});
