'use strict';
// Entirely synthetic Phoenix topology, isolated browser profile, no applicant/site data.
const assert=require('node:assert/strict'),path=require('node:path'),os=require('node:os');
let playwright;try{playwright=require('playwright');}catch(_){playwright=require(process.env.TOUDI_PLAYWRIGHT_MODULE || path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const root=path.resolve(__dirname,'../app');
const text=(value='')=>`<input class="phoenix-input" value="${value}">`;
const choice=(key,value='',kind='constant',disabled=false)=>`<div class="phoenix-select${disabled?' phoenix-select--disabled':''}" data-key="${key}" data-kind="${kind}"><div class="phoenix-select__content">${value}</div><input class="phoenix-select__input" readonly></div>`;
const field=(title,control)=>`<div class="form-item form-item--phoenix"><div class="form-item__title"><span class="form-item__text">${title}</span><span class="form-item__required">*</span></div><div class="form-item__content">${control}<p class="error">必填项未填写</p></div></div>`;
const radio=`<div class="phoenix-radio-group">${['男','女'].map(label=>`<div class="phoenix-radio"><span class="phoenix-radio__radio-text">${label}</span></div>`).join('')}</div>`;
const record=(degree,id)=>`<div class="ux-standard-form">${field('学校名称',text('合成学校'+degree))}${field('学历',choice('degree-'+id,degree))}${field('开始日期',choice('start-'+id,'','date'))}${field('GPA',text())}</div>`;
const fixture=`<!doctype html><meta charset="utf-8"><style>body{font:16px sans-serif}input{width:180px;height:26px}.form-item{padding:6px}.phoenix-select,.phoenix-radio,.list-item-container,.area-item-container,.phoenix-button{padding:6px;cursor:pointer}.common-unmodeled-layer{position:fixed;top:0;right:0;width:280px;background:#eee;z-index:100}.error{color:#900}</style><nav><input placeholder="搜索职位"></nav><form><section><h2>个人信息</h2><div class="ux-standard-form">${field('姓名',text('合成已有姓名'))}${field('性别',radio)}${field('最高学历',choice('highest',''))}${field('现居地',choice('city','','area'))}${field('出生日期',choice('birthday','','date'))}${field('锁定字段',choice('locked','硕士','constant',true))}</div></section><section><h2>教育经历</h2>${record('硕士','m')}${record('本科','b')}</section><button type="submit">提交申请</button></form><script>
window.submits=0;window.confirmations=0;window.searches=[];window.calendarEnters=0;window.behavior={};window.optionRows={'highest':['本科','硕士'],'city':['上海市'],'degree-m':['本科','硕士'],'degree-b':['本科','硕士']};
document.querySelector('form').onsubmit=e=>{e.preventDefault();submits++};
function closeLayers(){document.querySelectorAll('.common-unmodeled-layer:not(.fixture-decoy)').forEach(n=>n.remove());document.querySelectorAll('.phoenix-select--active').forEach(n=>n.classList.remove('phoenix-select--active'))}
document.querySelectorAll('.form-item__title').forEach(n=>n.onclick=closeLayers);
document.addEventListener('mousedown',e=>{if(e.target.closest('.form-item__title'))closeLayers()});
document.querySelectorAll('.phoenix-radio').forEach(n=>n.onclick=()=>{n.parentElement.querySelectorAll('.phoenix-radio').forEach(o=>o.classList.remove('phoenix-radio--checked'));n.classList.add('phoenix-radio--checked')});
document.querySelectorAll('.phoenix-select').forEach(select=>select.onclick=()=>{
if(select.classList.contains('phoenix-select--disabled'))return;const key=select.dataset.key,kind=select.dataset.kind,b=behavior[key]||{};select.classList.add('phoenix-select--active');const layer=document.createElement('div');layer.className='common-unmodeled-layer';document.body.append(layer);
if(kind==='date'){layer.innerHTML='<div class="phoenix-date-picker"><input class="phoenix-calendar-input"></div>';layer.querySelector('input').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();calendarEnters++;if(!b.failRead)select.querySelector('.phoenix-select__content').textContent=e.target.value;closeLayers()}};return;}
const area=kind==='area',rows=optionRows[key]||[],rowClass=area?'area-item-container':'list-item-container',labelClass=area?'area-text-label':'item-text-label';
layer.innerHTML='<div class="'+(area?'area-selector-container':'constant-main-selector-container')+'"><div class="'+(area?'area-search-input':'content-search')+'"><input></div>'+rows.map((v,i)=>'<div class="'+rowClass+(b.disabled?' item--disabled':'')+'"><span class="icon-container">○</span><span class="'+labelClass+'">'+v+'</span></div>').join('')+'</div><div class="'+(area?'area-footer-button':'selector-footer-button')+'"><div class="phoenix-button"><div class="phoenix-button__wraper">取消</div></div><div class="phoenix-button"><div class="phoenix-button__wraper">确定</div></div></div>';
let picked='';layer.querySelector('input').oninput=e=>searches.push({key,value:e.target.value});
layer.querySelectorAll('.'+rowClass).forEach(row=>{const pick=()=>picked=row.querySelector('.'+labelClass).textContent;if(area){row.onclick=()=>{window.areaDrills=(window.areaDrills||0)+1};row.querySelector('.icon-container').onclick=e=>{e.stopPropagation();pick()}}else row.onclick=pick});
layer.querySelectorAll('.phoenix-button__wraper').forEach(button=>button.onclick=()=>{if(button.textContent==='确定'){confirmations++;if(!b.failRead)select.querySelector('.phoenix-select__content').textContent=picked;}closeLayers()});
});
</script>`;
let browser;
(async()=>{
 browser=await playwright.chromium.launch({headless:true,executablePath:process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://fixture.invalid/**',r=>r.fulfill({contentType:'text/html',body:fixture}));await page.goto('https://fixture.invalid/apply?fixture=1');
 for(const file of ['assets/form-adapters.js','assets/form-engine.js','browser-extension/filling-aliases.js','browser-extension/filling-core.js'])await page.addScriptTag({path:path.join(root,file)});
 const scan=()=>page.evaluate(()=>TouDiFormEngine.scan());let s=await scan();const f=(label,hint)=>s.fields.find(f=>f.label===label&&(!hint||f.recordHint===hint));
 assert.equal(s.fields.length,14);assert(s.platforms.some(p=>p.id==='zhiye-phoenix'));assert(!s.fields.some(f=>/必填|合成学校|合成已有姓名|搜索职位/.test(f.label)));assert.equal(f('性别').adapter,'phoenix-radio');assert.equal(f('最高学历').adapter,'phoenix-select');assert.equal(f('出生日期').adapter,'phoenix-date');assert.equal(f('出生日期').dateFormat,undefined);assert.equal(f('出生日期').datePrecision,'deferred');assert.equal(f('锁定字段').unsupported,'disabled-or-readonly');assert.equal(f('学校名称','硕士').module,'education');assert.notEqual(f('学校名称','硕士').groupId,f('学校名称','本科').groupId);
 const inspection=await page.evaluate(s=>TouDiFormEngine.inspectOptions({fieldIds:[s.fields.find(f=>f.label==='最高学历').id,s.fields.find(f=>f.label==='现居地').id],fingerprint:s.fingerprint}),s);
 assert.deepEqual(inspection.items[0].options,[{value:'本科',text:'本科'},{value:'硕士',text:'硕士'}]);assert.deepEqual(inspection.items[1].options,[],'hierarchical region is not flattened into invented choices');assert.equal(await page.evaluate(()=>confirmations),0);assert.equal(await page.evaluate(()=>document.querySelectorAll('.common-unmodeled-layer').length),0);assert.deepEqual((await scan()).fields.map(f=>f.value),s.fields.map(f=>f.value),'inspection must not change any field');
 const personal={schemaVersion:1,profiles:[{id:'general',label:'合成资料'}],facts:[{key:'gender',label:'性别',value:'女',module:'personal'},{key:'highest',label:'最高学历',value:'硕士研究生',module:'personal'},{key:'city',label:'现居地',value:'上海市',module:'personal'},{key:'birthday',label:'出生日期',value:'2001-02-03',precision:'day',module:'personal'}],rules:[]};
 const personalPlan=await page.evaluate(({p,s})=>TouDiFillingCore.plan(TouDiFillingCore.profile(TouDiFillingCore.validatePack(p),'general'),s),{p:personal,s});assert.equal(personalPlan.statusCounts.ready,4,'radio, deferred portals and day-precision calendar must form usable local plans');
 const defs=s.fields.map(({id,label,module,groupId})=>({id,label,module,groupId}));await page.evaluate(()=>{document.querySelector('input.phoenix-input').value='合成修改值'});const changed=await scan();assert.deepEqual(changed.fields.map(({id,label,module,groupId})=>({id,label,module,groupId})),defs,'personal input values must not change field IDs or titles');s=changed;
 const action=(target,value,extra={})=>({protocol:1,origin:s.origin,path:s.path,fingerprint:s.fingerprint,actions:[{fieldId:target.id,value,expectedValue:target.value,overwrite:true,...extra}]});const apply=p=>page.evaluate(p=>TouDiFormEngine.apply(p),p);
 let result=await apply(action(f('姓名'),'不应写入',{overwrite:false}));assert.equal(result.results[0].reason,'existing-value');assert.equal((await scan()).fields.find(v=>v.id===f('姓名').id).value,'合成修改值');
 result=await apply(action(f('性别'),'女'));assert.equal(result.summary.verified,1,JSON.stringify(result));s=await scan();assert.equal(f('性别').value,'女');
 await page.evaluate(()=>{const decoy=document.createElement('div');decoy.className='common-unmodeled-layer fixture-decoy';decoy.style.left='0';decoy.style.right='auto';decoy.innerHTML='<div class="constant-main-selector-container"><div class="list-item-container"><span class="item-text-label">硕士</span></div></div>';decoy.onclick=()=>window.decoyClicks=(window.decoyClicks||0)+1;document.body.append(decoy)});
 result=await apply(action(f('最高学历'),'硕士研究生'));assert.equal(result.results[0].reason,'menu-not-closed','An unrelated persistent portal must not become this field\'s menu');assert.equal(await page.evaluate(()=>window.decoyClicks||0),0);await page.evaluate(()=>document.querySelector('.fixture-decoy').remove());
 result=await apply(action(f('最高学历'),'硕士研究生'));assert.equal(result.summary.verified,1,JSON.stringify(result));s=await scan();assert.equal(f('最高学历').value,'硕士');assert((await page.evaluate(()=>searches)).some(v=>v.key==='highest'&&v.value==='硕士'));
 result=await apply(action(f('现居地'),'上海市'));assert.equal(result.summary.verified,1,JSON.stringify(result));s=await scan();assert.equal(f('现居地').value,'上海市');assert.equal(await page.evaluate(()=>window.areaDrills||0),0,'select region icon rather than drilling into it');assert.equal(await page.evaluate(()=>confirmations),2);
 result=await apply(action(f('出生日期'),'2001-02-03'));assert.equal(result.summary.verified,1,JSON.stringify(result));s=await scan();assert.equal(f('出生日期').value,'2001-02-03');assert.equal(await page.evaluate(()=>calendarEnters),1);
 const profile={schemaVersion:1,profiles:[{id:'general',label:'合成资料'}],facts:[{key:'start-m',label:'开始日期',value:'2024-09',precision:'month',module:'education',recordId:'m',recordHint:'硕士'},{key:'gpa-m',label:'GPA',value:'3.8',module:'education',recordId:'m',recordHint:'硕士'},{key:'gpa-b',label:'GPA',value:'3.5',module:'education',recordId:'b',recordHint:'本科'}],rules:[]};
 const plan=await page.evaluate(({p,s})=>TouDiFillingCore.plan(TouDiFillingCore.profile(TouDiFillingCore.validatePack(p),'general'),s),{p:profile,s});assert.equal(plan.rows.find(r=>r.fieldId===f('开始日期','硕士').id).status,'ready','closed Phoenix picker must defer its actual month/day precision');const gpas=plan.rows.filter(r=>r.label==='GPA');assert(gpas.every(r=>r.status==='ready'));const approved=await page.evaluate(p=>TouDiFillingCore.confirm(p,p.rows.filter(r=>r.label==='GPA').map(r=>r.fieldId)),plan);result=await apply(approved);assert.equal(result.summary.verified,2,JSON.stringify(result));s=await scan();
 result=await apply(action(f('开始日期','硕士'),'2024-09'));assert.equal(result.results[0].reason,'date-precision-required');
 result=await apply(action(f('锁定字段'),'本科'));assert.equal(result.results[0].reason,'disabled-or-readonly');
 const highest=()=>f('最高学历');await page.evaluate(()=>{behavior.highest={disabled:true}});result=await apply(action(highest(),'本科'));assert.equal(result.results[0].reason,'option-disabled');assert.equal((await scan()).fields.find(v=>v.id===highest().id).value,'硕士');
 await page.evaluate(()=>{behavior.highest={};optionRows.highest=['本科','本科','硕士']});s=await scan();result=await apply(action(highest(),'本科'));assert.equal(result.results[0].reason,'option-not-unique');
 await page.evaluate(()=>{optionRows.highest=['硕士']});s=await scan();result=await apply(action(highest(),'本科'));assert.equal(result.results[0].reason,'option-not-found');
 await page.evaluate(()=>{optionRows.highest=['本科','硕士'];behavior.highest={failRead:true}});s=await scan();result=await apply(action(highest(),'本科'));assert.equal(result.results[0].reason,'value-not-retained');assert.equal((await scan()).fields.find(v=>v.id===highest().id).value,'硕士');
 await page.evaluate(()=>{behavior.birthday={failRead:true}});s=await scan();result=await apply(action(f('出生日期'),'2002-03-04'));assert.equal(result.results[0].reason,'date-not-retained');assert.equal((await scan()).fields.find(v=>v.id===f('出生日期').id).value,'2001-02-03');
 await page.evaluate(()=>document.querySelector('.phoenix-radio').classList.add('phoenix-radio--disabled'));s=await scan();result=await apply(action(f('性别'),'男'));assert.equal(result.results[0].reason,'option-disabled');await page.evaluate(()=>{const male=document.querySelector('.phoenix-radio');male.classList.remove('phoenix-radio--disabled');const clone=male.cloneNode(true);clone.dataset.duplicate='true';male.parentElement.append(clone)});s=await scan();result=await apply(action(f('性别'),'男'));assert.equal(result.results[0].reason,'option-not-unique');await page.evaluate(()=>document.querySelector('[data-duplicate]').remove());s=await scan();result=await apply(action(f('性别'),'不存在'));assert.equal(result.results[0].reason,'option-not-found');
 // Real Phoenix variants stay synthetic and use only this isolated fixture browser.
 await page.evaluate(markup=>{
   document.querySelector('form').insertAdjacentHTML('beforeend',markup);
   window.extraSelections=[];window.extraIconClicks=0;window.extraRowClicks=0;
   document.querySelectorAll('[data-extra]').forEach(select=>select.onclick=()=>{
     closeLayers();select.classList.add('phoenix-select--active');const layer=document.createElement('div');layer.className='common-unmodeled-layer';document.body.append(layer);
     const mode=select.dataset.extra;
     if(mode==='single'){
       layer.innerHTML='<div class="phoenix-selectList"><div class="phoenix-selectList__searchWrapper"><input></div><div class="phoenix-selectList__listItem"><span class="phoenix-selectList__singleLabel">全国普通高等院校全日制</span></div><div class="phoenix-selectList__listItem"><span class="phoenix-selectList__singleLabel">全国普通高等院校非全日制</span></div></div>';
       layer.querySelector('input').oninput=e=>searches.push({key:'single',value:e.target.value});
       layer.querySelectorAll('.phoenix-selectList__listItem').forEach(row=>row.onclick=()=>{extraSelections.push('single');select.querySelector('.phoenix-select__content').textContent=row.querySelector('span').textContent;closeLayers()});return;
     }
     const area=mode==='region',rows=area?[['西湖区','浙江省 杭州市'],['西湖区','合成省 合成市']]:[['合成单位性质','']];
     layer.innerHTML='<div class="'+(area?'area-selector-container':'constant-main-selector-container')+'"><div class="'+(area?'area-search-input':'content-search')+'"><input></div>'+rows.map(([label,path])=>'<div class="'+(area?'area-item-container':'list-item-container')+'"><span class="icon-container">○</span><span class="'+(area?'area-text-label':'item-text-label')+'">'+label+'</span><span class="area-item-path">'+path+'</span></div>').join('')+'</div><div class="'+(area?'area-footer-button':'selector-footer-button')+'"><div class="phoenix-button"><div class="phoenix-button__wraper">取消</div></div><div class="phoenix-button"><div class="phoenix-button__wraper">确定</div></div></div>';
     let picked='';layer.querySelector('input').oninput=e=>searches.push({key:mode,value:e.target.value});
     layer.querySelectorAll(area?'.area-item-container':'.list-item-container').forEach(row=>{
       row.onclick=()=>{extraRowClicks++};row.querySelector('.icon-container').onclick=e=>{e.stopPropagation();extraIconClicks++;picked=row.querySelector(area?'.area-text-label':'.item-text-label').textContent;extraSelections.push(row.querySelector('.area-item-path').textContent)};
     });
     layer.querySelectorAll('.phoenix-button__wraper').forEach(button=>button.onclick=()=>{if(button.textContent==='确定'){confirmations++;select.querySelector('.phoenix-select__content').textContent=picked}closeLayers()});
   });
   document.querySelector('[data-numeric-score]').addEventListener('input',e=>{e.target.value=Number(e.target.value).toFixed(5)});
   document.querySelector('[data-numeric-id]').addEventListener('input',e=>{e.target.value=Number(e.target.value).toFixed(5)});
 },'<section><h2>个人信息</h2><div class="ux-standard-form">'+field('学历类型',choice('single').replace('data-kind="constant"','data-kind="constant" data-extra="single"'))+field('单位性质',choice('icon').replace('data-kind="constant"','data-kind="constant" data-extra="constant"'))+field('籍贯',choice('region').replace('data-kind="constant"','data-kind="constant" data-extra="region"'))+field('证件号码',text().replace('class="phoenix-input"','class="phoenix-input" data-numeric-id'))+'</div></section><section><h2>语言能力</h2><div class="ux-standard-form">'+field('语言成绩',text().replace('class="phoenix-input"','class="phoenix-input" data-numeric-score'))+'</div></section><section><h2>家庭成员</h2><div class="ux-standard-form">'+field('姓名',text('合成家属'))+'</div></section>');
 s=await scan();const beforeSingle=await page.evaluate(()=>confirmations);
 result=await apply(action(f('学历类型'),'普通全日制'));assert.equal(result.summary.verified,1,JSON.stringify(result));s=await scan();assert.equal(f('学历类型').value,'全国普通高等院校全日制');assert.equal(await page.evaluate(()=>confirmations),beforeSingle,'selectList single choice commits without footer confirmation');assert((await page.evaluate(()=>searches)).some(v=>v.key==='single'&&v.value==='全日制'));
 result=await apply(action(f('单位性质'),'合成单位性质'));assert.equal(result.summary.verified,1,JSON.stringify(result));assert.equal(await page.evaluate(()=>extraIconClicks),1);assert.equal(await page.evaluate(()=>extraRowClicks),0,'constant row text cannot substitute for radio icon selection');
 s=await scan();result=await apply(action(f('籍贯'),'浙江省杭州市西湖区'));assert.equal(result.summary.verified,1,JSON.stringify(result));assert((await page.evaluate(()=>searches)).some(v=>v.key==='region'&&v.value==='西湖区'));assert.equal(await page.evaluate(()=>extraSelections.at(-1)),'浙江省 杭州市');assert.equal(await page.evaluate(()=>extraRowClicks),0);
 s=await scan();result=await apply(action(f('籍贯'),'浙江省西湖区'));assert.equal(result.summary.verified,1,JSON.stringify(result));assert.equal(await page.evaluate(()=>extraSelections.at(-1)),'浙江省 杭州市','short province/leaf path selects the same uniquely matching hierarchy');
 s=await scan();result=await apply(action(f('籍贯'),'西湖区'));assert.equal(result.results[0].reason,'option-not-unique','leaf alone must not guess between matching regions');
 s=await scan();const family=s.fields.find(field=>field.label==='姓名'&&field.module==='family');assert(family);assert.equal(family.unsupported,undefined);
 const familyPlans=await page.evaluate(({scan,familyId})=>{const C=TouDiFillingCore,make=facts=>C.profile(C.validatePack({schemaVersion:1,profiles:[{id:'general',label:'合成资料'}],facts,rules:[]}));const unrelated=C.plan(make([{key:'self-name',module:'personal',label:'姓名',value:'合成本人'}]),scan);let blocked=false;try{C.confirm(unrelated,[familyId])}catch(e){blocked=/需要先核对/.test(e.message)}const related=C.plan(make([{key:'family-name',module:'family',recordId:'family-one',recordLabel:'合成家属',label:'姓名',value:'合成家属已确认'}]),scan);return {blocked,related:C.confirm(related,[familyId],[familyId]),row:related.rows.find(r=>r.fieldId===familyId)};},{scan:s,familyId:family.id});
 assert(familyPlans.blocked,'applicant name cannot be used for a family member');assert.equal(await page.evaluate(()=>[...document.querySelectorAll('section')].find(section=>section.querySelector('h2')?.textContent==='家庭成员').querySelector('input').value),'合成家属');assert.equal(familyPlans.row.factKey,'family-name');result=await apply(familyPlans.related);assert.equal(result.summary.verified,1,JSON.stringify(result));
 s=await scan();result=await apply(action(f('语言成绩'),'554'));assert.equal(result.summary.verified,1,JSON.stringify(result));s=await scan();assert.equal(f('语言成绩').value,'554.00000');
 result=await apply(action(f('证件号码'),'554'));assert.equal(result.results[0].reason,'value-not-retained','identifiers must not use score numeric equivalence');
 // Phoenix month calendar, including the observed adjacent-decade year behavior.
 await page.evaluate(markup=>{
   document.querySelector('form').insertAdjacentHTML('beforeend',markup);window.monthBehavior={};window.monthYearClicks=[];window.monthSpecialClicks=0;window.monthDefaultClicks=0;
   const select=document.querySelector('[data-month-calendar]');select.onclick=()=>{
     closeLayers();select.classList.add('phoenix-select--active');const layer=document.createElement('div');layer.className='common-unmodeled-layer';
     layer.innerHTML='<div class="phoenix-date-picker"><div class="phoenix-calendar phoenix-calendar-month-calendar"></div><div class="phoenix-date-picker-special-text"><input disabled value="至今"></div><div class="phoenix-date-picker-special-check"><input class="phoenix-checkbox__input" type="checkbox"></div><button type="button" class="fixture-today">今天</button></div>';document.body.append(layer);
     layer.querySelector('.phoenix-checkbox__input').onclick=()=>monthSpecialClicks++;layer.querySelector('.fixture-today').onclick=()=>monthDefaultClicks++;
     const calendar=layer.querySelector('.phoenix-calendar');let currentYear=2026;
     const monthView=()=>{
       calendar.innerHTML='<a class="phoenix-calendar-month-panel-prev-year-btn">前一年</a><a class="phoenix-calendar-month-panel-year-select"><span class="phoenix-calendar-month-panel-year-select-content">'+currentYear+'</span></a><a class="phoenix-calendar-month-panel-next-year-btn">后一年</a>'+Array.from({length:12},(_,i)=>'<a class="phoenix-calendar-month-panel-month'+(monthBehavior.disabled&&i===8?' Disabled':'')+'">'+(i+1)+'月</a>').join('');
       calendar.querySelector('.phoenix-calendar-month-panel-prev-year-btn').onclick=()=>{if(!monthBehavior.stalled)currentYear--;monthView()};calendar.querySelector('.phoenix-calendar-month-panel-next-year-btn').onclick=()=>{if(!monthBehavior.stalled)currentYear++;monthView()};
       calendar.querySelector('.phoenix-calendar-month-panel-year-select').onclick=()=>yearView(Math.floor(currentYear/10)*10);if(monthBehavior.noYearPanel)calendar.querySelector('.phoenix-calendar-month-panel-year-select').classList.remove('phoenix-calendar-month-panel-year-select');
       calendar.querySelectorAll('.phoenix-calendar-month-panel-month').forEach((month,index)=>month.onclick=()=>{if(!monthBehavior.failRead)select.querySelector('.phoenix-select__content').textContent=currentYear+'-'+String(index+1).padStart(2,'0');closeLayers()});
     };
     const yearView=decade=>{
       calendar.innerHTML='<div class="phoenix-calendar-year-panel"><a class="phoenix-calendar-year-panel-prev-decade-btn">前十年</a><a class="phoenix-calendar-year-panel-decade-select">'+decade+'-'+(decade+9)+'</a><a class="phoenix-calendar-year-panel-next-decade-btn">后十年</a>'+Array.from({length:12},(_,i)=>'<a class="phoenix-calendar-year-panel-year">'+(decade-1+i)+'</a>').join('')+'</div>';
       calendar.querySelector('.phoenix-calendar-year-panel-prev-decade-btn').onclick=()=>yearView(monthBehavior.stalled?decade:decade-10);calendar.querySelector('.phoenix-calendar-year-panel-next-decade-btn').onclick=()=>yearView(monthBehavior.stalled?decade:decade+10);
       calendar.querySelectorAll('.phoenix-calendar-year-panel-year').forEach(year=>year.onclick=()=>{const wanted=Number(year.textContent);monthYearClicks.push(wanted);if(wanted<decade||wanted>decade+9)yearView(Math.floor(wanted/10)*10);else {currentYear=wanted;monthView()}});
     };monthView();
   };
 },'<section><h2>获奖情况</h2><div class="ux-standard-form">'+field('获奖时间',choice('award-month').replace('data-kind="constant"','data-kind="constant" data-month-calendar'))+'</div></section>');
 s=await scan();assert.equal(f('获奖时间').adapter,'phoenix-date');assert.equal(f('获奖时间').datePrecision,'deferred');assert.equal(f('获奖时间').dateFormat,undefined);
 result=await apply(action(f('获奖时间'),'2020-09'));assert.equal(result.summary.verified,1,JSON.stringify(result));s=await scan();assert.equal(f('获奖时间').value,'2020-09');assert.equal(result.results[0].datePrecisionReduced,undefined);
 result=await apply(action(f('获奖时间'),'2033-12'));assert.equal(result.summary.verified,1,JSON.stringify(result));s=await scan();assert.equal(f('获奖时间').value,'2033-12');
 result=await apply(action(f('获奖时间'),'2019-03'));assert.equal(result.summary.verified,1,JSON.stringify(result));assert.deepEqual(await page.evaluate(()=>monthYearClicks.slice(-2)),[2019,2019],'adjacent-decade year needs a second exact year click before month selection');
 s=await scan();result=await apply(action(f('获奖时间'),'2024-09-15'));assert.equal(result.summary.verified,1,JSON.stringify(result));assert.equal(result.results[0].datePrecisionReduced,true);assert.equal(result.results[0].sourcePrecision,'day');assert.equal(result.results[0].writtenPrecision,'month');s=await scan();assert.equal(f('获奖时间').value,'2024-09');
 result=await apply(action(f('获奖时间'),'2024-13'));assert.equal(result.results[0].reason,'invalid-date');
 await page.evaluate(()=>{monthBehavior={noYearPanel:true}});s=await scan();result=await apply(action(f('获奖时间'),'2025-07'));assert.equal(result.summary.verified,1,JSON.stringify(result));s=await scan();assert.equal(f('获奖时间').value,'2025-07','year prev/next fallback must select the verified year');
 await page.evaluate(()=>{monthBehavior={disabled:true}});s=await scan();result=await apply(action(f('获奖时间'),'2026-09'));assert.equal(result.results[0].reason,'date-month-disabled');
 await page.evaluate(()=>{monthBehavior={stalled:true}});s=await scan();result=await apply(action(f('获奖时间'),'2040-09'));assert.equal(result.results[0].reason,'date-year-navigation-stalled');
 await page.evaluate(()=>{monthBehavior={failRead:true}});s=await scan();result=await apply(action(f('获奖时间'),'2020-09'));assert.equal(result.results[0].reason,'date-not-retained');assert.equal((await scan()).fields.find(field=>field.id===f('获奖时间').id).value,'2025-07');
 assert.equal(await page.evaluate(()=>monthSpecialClicks),0,'the special present checkbox is never a date fallback');assert.equal(await page.evaluate(()=>monthDefaultClicks),0,'month selection never uses today/default date');
 // Synthetic copies of the real field-title topology; selected names are only record hints.
 const roleCard=(name)=>'<div class="ux-standard-form">'+field('在校职务类别',choice('category-'+name,'其他'))+field('在校职务名称',text(name))+field('在校职务描述',text())+field('开始时间',choice('role-start-'+name))+field('结束时间',choice('role-end-'+name))+'</div>';
 const projectCard=(name)=>'<div class="ux-standard-form">'+field('在校科研及实践项目',text(name))+field('担任角色',text())+field('实践描述',text())+field('开始时间',choice('project-start-'+name))+field('结束时间',choice('project-end-'+name))+'</div>';
 const paperCard=(name)=>'<div class="ux-standard-form">'+field('名称',text(name))+field('发布时间',choice('paper-date-'+name))+'</div>';
 await page.evaluate(markup=>document.querySelector('form').insertAdjacentHTML('beforeend',markup),'<section><h2>在校职务</h2>'+roleCard('合成学习委员甲')+roleCard('合成干事乙')+'</section><section><h2>在校实践</h2>'+projectCard('合成项目甲')+projectCard('合成项目乙')+'</section><section><h2>论文/专著</h2>'+paperCard('合成论文完整题目甲')+paperCard('合成论文完整题目乙')+'</section>');
 s=await scan();const scoped=s.fields.filter(field=>['campus-role','projects','publications'].includes(field.module));assert.equal(scoped.length,24);assert(scoped.every(field=>field.recordHint && !field.label.includes('合成')),'selected identities must never become field labels');
 for(const module of ['campus-role','projects','publications'])assert.equal(new Set(scoped.filter(field=>field.module===module).map(field=>field.groupId)).size,2);
 const contextFacts=[];for(const [module,label,values] of [['campus-role','职务',['合成学习委员甲','合成干事乙']],['project','名称',['合成项目甲','合成项目乙']],['publications','论文名称',['合成论文完整题目甲','合成论文完整题目乙']]])values.forEach((value,i)=>{
   const recordId=module+'-'+i,base={module,recordId,recordLabel:value,recordHint:value};contextFacts.push({...base,key:recordId+'.name',label,value});
   if(module==='campus-role')for(const [label,value] of [['职责描述','合成职责'],['开始日期','2020-09'],['结束日期','2024-06']])contextFacts.push({...base,key:recordId+'.'+label,label,value});
   if(module==='project')for(const [label,value] of [['角色','合成团队成员'],['简述','合成实践描述'],['开始日期','2024-09'],['结束日期','2025-06']])contextFacts.push({...base,key:recordId+'.'+label,label,value});
   if(module==='publications')contextFacts.push({...base,key:recordId+'.date',label:'发表日期',value:'2025-11'});
 });
 const contextPlan=await page.evaluate(({facts,scan})=>{const p=TouDiFillingCore.profile(TouDiFillingCore.validatePack({schemaVersion:1,profiles:[{id:'general',label:'合成资料'}],facts,rules:[]}));return TouDiFillingCore.plan(p,{...scan,fields:scan.fields.map(field=>({...field,value:''}))});},{facts:contextFacts,scan:{...s,fields:scoped}});
 assert.equal(contextPlan.rows.filter(row=>row.status==='ready').length,22);assert.equal(contextPlan.rows.filter(row=>row.status==='missing').length,2);assert(contextPlan.rows.filter(row=>row.label==='在校职务类别').every(row=>row.status==='missing'&&/候选选项/.test(row.reason)),'role names cannot substitute for category options');
 const ids=scoped.map(field=>field.id);await page.evaluate(()=>document.querySelector('input[value="合成学习委员甲"]').value='');s=await scan();const rescoped=s.fields.filter(field=>['campus-role','projects','publications'].includes(field.module));assert.deepEqual(rescoped.map(field=>field.id),ids,'clearing an identity does not rename fields');assert(rescoped.filter(field=>field.module==='campus-role'&&field.groupId===scoped.find(field=>field.recordHint==='合成学习委员甲').groupId).every(field=>!field.recordHint),'blank card has no inferred ordered identity');
 // Website business validation can fail while native validity remains true.
 await page.evaluate(markup=>{
   document.querySelector('form').insertAdjacentHTML('beforeend',markup);
   const input=document.querySelector('[data-business-title]'),error=input.closest('.form-item--phoenix').querySelector('.form-item__error');
   input.addEventListener('blur',()=>{error.textContent=input.value.length>100?'最多输入100个字':'';error.style.display=input.value.length>100?'block':'none'});
 },'<section><h2>论文/专著</h2><div class="ux-standard-form">'+field('名称',text().replace('class="phoenix-input"','class="phoenix-input" data-business-title')).replace('<p class="error">必填项未填写</p>','<p class="form-item__error" style="display:none"></p>')+field('发布时间',text()).replace('<p class="error">必填项未填写</p>','<p class="form-item__error">其他字段错误</p>')+'</div></section>');
 s=await scan();const business=()=>s.fields.find(field=>field.label==='名称'&&field.groupId===s.fields.find(field=>field.label==='发布时间'&&field.value===''&&field.type==='text').groupId);
 assert(business());result=await apply(action(business(),'合'.repeat(108)));assert.equal(result.results[0].reason,'validation-failed');assert.equal(result.results[0].validationMessage,'最多输入100个字');assert.equal(await page.evaluate(()=>document.querySelector('[data-business-title]').validity.valid),true,'native constraints do not expose website business validation');
 s=await scan();result=await apply(action(business(),'合成缩略题名'));assert.equal(result.summary.verified,1,JSON.stringify(result));
 await page.evaluate(()=>{const error=document.querySelector('[data-business-title]').closest('.form-item--phoenix').querySelector('.form-item__error');error.textContent='隐藏旧错误';error.style.display='none';document.querySelector('[data-business-title]').onblur=null});
 s=await scan();result=await apply(action(business(),'合成有效题名'));assert.equal(result.summary.verified,1,JSON.stringify(result));
 assert.equal(await page.evaluate(()=>submits),0);assert.deepEqual(errors,[]);console.log('PASS Phoenix synthetic title/value isolation, stable education groups, radio, scoped portal search/confirm and area icon, calendar Enter, month/date precision protection, disabled/duplicate/missing/readback failures, existing-value protection, zero submissions, selectList direct commit, constant icon-only selection, region leaf/path disambiguation, family identity isolation and scoped numeric readback, deferred month/day calendars with year/decade navigation, explicit day-to-month reduction and no invented day/today/present');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close()});
