'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{makePack,installFixture,fullText}=require('./profile_ui_fixture.cjs');
let pw;try{pw=require('playwright')}catch(_){pw=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'))}
let browser;
(async()=>{
 browser=await pw.chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const page=await browser.newPage({viewport:{width:400,height:660}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const pack=makePack(),L=require('../app/browser-extension/profile-library.js'),records=Object.fromEntries(pack.profiles.map(p=>[p.id,L.copyRecords(pack,p.id)]));
 await page.addInitScript(installFixture,{pack,records});await page.addInitScript(()=>{
  const original=chrome.runtime.sendMessage;let current=null,lastPlan;
  window.fixtureAutoCalls=0;window.fixtureReviewCalls=0;
  chrome.runtime.sendMessage=async m=>{
   if(m.op==='agent-review'){fixtureReviewCalls++;current={plan:lastPlan,agentReview:{status:'running',message:'正在核对个人信息…'}};return new Promise(r=>window.fixtureReviewFinish=()=>{current={plan:lastPlan,agentReview:{status:'completed',accepted:1}};r({value:current})})}
   if(m.op==='auto-fill'){fixtureAutoCalls++;current={plan:lastPlan,automation:{id:'run',status:'running',phase:'writing'}};return new Promise(r=>window.fixtureFinish=()=>{current={plan:lastPlan,automation:{id:'run',status:'completed',phase:'done'},report:{summary:{verified:12},results:[]},pending:[{fieldId:'unmatched',label:'未提供的主观问题',groupLabel:'补充信息',status:'missing'}]};r({value:current})})}
   const result=await original(m);if(m.op==='state')result.value.state=current;if(m.op==='scan'){current=result.value;lastPlan=current.plan;}return result;
  };
 });
 await page.route('https://fixture.invalid/**',r=>{const file=path.basename(new URL(r.request().url()).pathname);return r.fulfill({body:fs.readFileSync(path.join(__dirname,file==='logo.svg'?'../app/assets/favicon.svg':'../app/browser-extension/'+file)),contentType:file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html'})});await page.goto('https://fixture.invalid/popup.html');await page.locator('#scanSummary').filter({hasText:'识别到 2 项'}).waitFor();assert.equal(await page.evaluate(()=>fixtureAutoCalls),0);await page.locator('.scan-module summary').click();assert.match(await page.locator('#scanGroups').innerText(),/姓名、手机/);await page.locator('#reviewAgent').click();await page.locator('#progress').filter({hasText:'正在核对个人信息'}).waitFor();assert.equal(await page.evaluate(()=>fixtureAutoCalls),0);assert(await page.locator('#fill').isDisabled());await page.evaluate(()=>fixtureReviewFinish());await page.locator('#reviewResult').filter({hasText:'核对完成'}).waitFor();assert(await page.locator('#fill').isEnabled());await page.locator('#fill').click();await page.locator('#fill:disabled').waitFor();await page.locator('#progress').filter({hasText:'正在填写并检查结果'}).waitFor();
 assert.equal(await page.locator('#review,#agentFeedback,[data-record-group]').count(),0);assert.equal(await page.locator('#tabLibrary').isEnabled(),true);await page.locator('#tabLibrary').click();await page.locator('[data-copy-fact]').first().waitFor();assert(await page.locator('#copyRecords').evaluate(n=>n.clientHeight>400));assert.equal(await page.evaluate(()=>fixtureAutoCalls),1);
 await page.evaluate(()=>fixtureFinish());await page.locator('#tabFill').click();await page.locator('#result .finish').filter({hasText:'已填写 12 项'}).waitFor();if(process.env.TOUDI_PANEL_EVIDENCE)await page.screenshot({path:path.join(process.env.TOUDI_PANEL_EVIDENCE,'核对后填写_简洁结果.png')});assert.equal(await page.evaluate(()=>fixtureReviewCalls),1);assert.doesNotMatch(await page.locator('#fillPane').innerText(),/Luna|新增|空白板块|采纳|匹配计划/);await page.locator('.remaining summary').click();await page.locator('[data-fallback-label]').click();assert.equal(await page.locator('#copySearch').inputValue(),'未提供的主观问题');assert.equal(await page.locator('#tabLibrary').getAttribute('aria-selected'),'true');
 await page.locator('#copySearch').fill('');assert.equal(await page.locator('[data-copy-fact]').count(),pack.facts.filter(f=>f.profiles.includes('general')).length);await page.locator('#tabFill').click();assert.equal(await page.locator('#fill').isEnabled(),true);assert.deepEqual(errors,[]);console.log('PASS slim popup: read-only grouped recognition before filling, optional review returns before separate fill, library browsing during run, simple durable report, missing-field copy search, full continuous library and no internal model/record plans');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>browser?.close());
