'use strict';
// Synthetic fields reproducing Moka's observed DOM topology. No applicant/site data.
const assert=require('node:assert/strict'),path=require('node:path'),os=require('node:os');
let playwright;try{playwright=require('playwright');}catch(_){playwright=require(process.env.TOUDI_PLAYWRIGHT_MODULE || path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const root=path.resolve(__dirname,'../app');
const input=(placeholder='',error='',value='')=>`<div class="sd-Tooltip-container-fixture"><label class="sd-Input-container-fixture"><input placeholder="${placeholder}" value="${value}">${error?'<div class="sd-Input-message-fixture">必填项未填写</div>':''}</label></div>`;
const select=(value='',options=[],disabled=false)=>`<div class="sd-Dropdown-container-fixture"><label class="sd-Input-container-fixture sd-Select-container-fixture"><span class="sd-Input-display-value-fixture">${value}</span><input placeholder="请选择" ${disabled?'disabled readonly':''}><span class="sd-Input-addon-fixture">▼</span><div class="sd-Input-message-fixture">必填项未填写</div></label><span><div class="sd-Dropdown-dropdown-fixture" hidden>${options.map(v=>`<div class="sd-Menu-content-item-fixture">${v}</div>`).join('')}</div></span></div>`;
const field=(title,control,cls='string_info-fixture')=>`<div class="apply-field-fixture ${cls}"><div class="title-fixture"><span><span>${title}</span></span><span class="required-asterisk-fixture">*</span></div><div class="ctrl-fixture">${control}</div></div>`;
const record=degree=>`<div class="apply-fields-fixture multi-fixture">${field('学校名称',select('合成学校'+degree,['合成学校'+degree]))}${field('学历',select(degree,['本科','硕士']))}${field('学制',select('', ['全日制','非全日制']))}${field('是否统招',select('是',['是','否']))}${field('就读时间',select('2024',['2024'])+select('9',['9'])+select('2027',['2027'])+select('6',['6']),'date_info-fixture')}${field('GPA',input('',true))}</div>`;
const block=(title,body)=>`<div class="apply-block-fixture"><div class="blockTitle-fixture"><div><span class="text-fixture"><span>${title}</span></span></div></div>${body}</div>`;
const fixture=`<!doctype html><meta charset="utf-8"><title>Synthetic Moka form regression</title><style>body{font:16px sans-serif}input{width:160px;height:24px}.apply-field-fixture{padding:8px}.sd-Input-message-fixture{color:#900}[hidden]{display:none!important}</style><nav><input placeholder="搜索职位"></nav><form>${block('个人信息',`<div class="apply-fields-fixture">${field('姓名',input('姓名','','合成姓名'))}${field('身高（cm）',input('身高（cm）',true))}${field('性别',select('男',['男','女']))}${field('证件号码',select('身份证',['身份证','护照'])+input('证件号码'))}${field('手机号码',select('+86',['+86'])+input('请输入手机号'))}${field('出生日期 (年龄)','<label class="sd-Input-container-fixture"><input readonly placeholder="出生日期 (年龄)"><div>必填项未填写</div></label>','day_info-fixture')}${field('最高学历',select('硕士',['硕士'],true))}</div>`)}${block('教育背景',record('硕士')+record('本科'))}<button type="submit">提交</button></form><script>window.submits=0;document.querySelector('form').onsubmit=e=>{e.preventDefault();submits++};document.querySelectorAll('.sd-Dropdown-container-fixture').forEach(c=>{const input=c.querySelector('input'),menu=c.querySelector('.sd-Dropdown-dropdown-fixture');input.onclick=()=>menu.hidden=false;c.querySelectorAll('.sd-Menu-content-item-fixture').forEach(o=>o.onclick=()=>{c.querySelector('.sd-Input-display-value-fixture').textContent=o.textContent;input.value='';menu.hidden=true;document.querySelector('.sd-Input-message-fixture')?.remove()})});document.querySelectorAll('.title-fixture').forEach(t=>t.onclick=()=>document.querySelectorAll('.sd-Dropdown-dropdown-fixture').forEach(m=>m.hidden=true));</script>`;
let browser;
(async()=>{
 browser=await playwright.chromium.launch({headless:true,executablePath:process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://fixture.invalid/**',r=>r.fulfill({contentType:'text/html',body:fixture}));await page.goto('https://fixture.invalid/application');
 if(process.env.OLD_ENGINE){await page.addScriptTag({path:process.env.OLD_ENGINE});const old=await page.evaluate(()=>TouDiFormEngine.scan());console.log('BEFORE',JSON.stringify({fields:old.fields.length,correctHeight:old.fields.some(f=>f.label==='身高（cm）'),errorLabels:old.fields.filter(f=>f.label.includes('必填项')).length,education:old.fields.filter(f=>f.module==='education').length}));}
 for(const file of ['assets/form-engine.js','browser-extension/filling-aliases.js','browser-extension/filling-core.js'])await page.addScriptTag({path:path.join(root,file)});
 const scan=()=>page.evaluate(()=>TouDiFormEngine.scan());let s=await scan();const f=(label,hint)=>s.fields.find(f=>f.label===label && (!hint || f.recordHint===hint));
 assert.equal(s.fields.length,27);assert(!s.fields.some(f=>f.label.includes('必填项')));assert.equal(f('身高（cm）').module,'personal');assert(f('身高（cm）').required);assert.equal(f('性别').value,'男');assert.equal(f('性别').adapter,'moka-select');assert.equal(f('证件类型').value,'身份证');assert.equal(f('电话区号').value,'+86');assert(f('手机号码'));assert.equal(f('最高学历').unsupported,'disabled-or-readonly');assert.equal(f('出生日期 (年龄)').unsupported,'custom-date');assert.equal(f('就读时间 · 开始年份','硕士').unsupported,'split-date');assert.equal(f('学校名称','硕士').module,'education');assert.notEqual(f('学校名称','硕士').groupId,f('学校名称','本科').groupId);
 const profile={schemaVersion:1,profiles:[{id:'general',label:'合成资料'}],facts:[{key:'height',label:'身高cm',value:'175',module:'personal'},{key:'gender',label:'性别',value:'男',module:'personal'},{key:'gpa1',label:'GPA',value:'3.8',module:'education',recordId:'m',recordHint:'硕士'},{key:'gpa2',label:'GPA',value:'3.5',module:'education',recordId:'b',recordHint:'本科'},{key:'type1',label:'学制',value:'全日制',module:'education',recordId:'m',recordHint:'硕士'},{key:'type2',label:'学制',value:'非全日制',module:'education',recordId:'b',recordHint:'本科'}],rules:[]};
 const plan=await page.evaluate(({profile,s})=>{const C=TouDiFillingCore;return C.plan(C.profile(C.validatePack(profile),'general'),s)},{profile,s});assert.equal(plan.rows.find(r=>r.label==='性别').status,'already');assert.equal(plan.statusCounts.ready,5);
 const approved=await page.evaluate(plan=>TouDiFillingCore.confirm(plan,plan.rows.filter(r=>r.status==='ready').map(r=>r.fieldId)),plan);let result=await page.evaluate(p=>TouDiFormEngine.apply(p),approved);assert.equal(result.summary.verified,5,JSON.stringify(result));assert.equal(await page.evaluate(()=>submits),0);
 s=await scan();assert.equal(f('学制','硕士').value,'全日制');assert.equal(f('学制','本科').value,'非全日制');assert.equal(f('姓名').value,'合成姓名');assert.equal(s.fingerprint,plan.fingerprint,'validation messages and selected values must not change field identity');
 const target=f('学制','硕士');const action=value=>({protocol:1,origin:s.origin,path:s.path,fingerprint:s.fingerprint,actions:[{fieldId:target.id,value,expectedValue:target.value,overwrite:true}]});
 result=await page.evaluate(p=>TouDiFormEngine.apply(p),action('不存在的选项'));assert.equal(result.results[0].reason,'option-not-found');assert.equal((await scan()).fields.find(f=>f.id===target.id).value,'全日制');
 await page.evaluate(()=>{const o=document.querySelector('.multi-fixture .apply-field-fixture:nth-child(3) .sd-Menu-content-item-fixture');o.parentElement.append(o.cloneNode(true))});s=await scan();result=await page.evaluate(p=>TouDiFormEngine.apply(p),action('全日制'));assert.equal(result.results[0].reason,'option-not-unique');
 const times=await page.evaluate(async()=>{const times=[];for(let i=0;i<20;i++){const t=performance.now();await TouDiFormEngine.scan();times.push(performance.now()-t);}return times.sort((a,b)=>a-b)});assert(times[18]<500,'field collection must stay bounded on this form');assert.deepEqual(errors,[]);
 console.log('AFTER',JSON.stringify({fields:s.fields.length,education:s.fields.filter(f=>f.module==='education').length,ready:plan.statusCounts.ready,verified:5,scanMedianMs:times[10],scanP95Ms:times[18],errors:errors.length}));console.log('PASS Moka title/error isolation, stable identities, required fields, education grouping, split dates, displayed values, scoped menu selection, duplicate/missing option protection, no overwrite/submit');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close()});
