'use strict';
// Browser plugin not available. This uses an isolated extension profile, never the user's Chrome.
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
let playwright;try{playwright=require('playwright')}catch(_){playwright=require(process.env.TOUDI_PLAYWRIGHT_MODULE||path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const repo=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'toudi-panel-runtime-')),extension=path.join(temp,'extension');
fs.cpSync(path.join(repo,'app/browser-extension'),extension,{recursive:true});
for(const [src,dst]of [['favicon.svg','logo.svg'],['form-engine.js','form-engine.js'],['form-adapters.js','form-adapters.js']])fs.copyFileSync(path.join(repo,'app/assets',src),path.join(extension,dst));
// Only the isolated fixture gets a localhost permission, replacing a toolbar user gesture.
// Production manifest permissions are unchanged; production listeners and sender checks still run.
const manifest=JSON.parse(fs.readFileSync(path.join(extension,'manifest.json')));manifest.host_permissions=['http://127.0.0.1/*'];fs.writeFileSync(path.join(extension,'manifest.json'),JSON.stringify(manifest));
// Verify the runtime acknowledgement even when the cross-origin window message is absent.
const popup=path.join(extension,'popup.js');fs.writeFileSync(popup,fs.readFileSync(popup,'utf8').replace("parent.postMessage({type:'toudi-panel-ready'},'*');",'/* fixture: runtime acknowledgement only */'));
const worker=path.join(extension,'worker.js');fs.writeFileSync(worker,'const actionListener=chrome.action.onClicked.addListener.bind(chrome.action.onClicked);chrome.action.onClicked.addListener=fn=>{globalThis.fixtureAction=fn;actionListener(fn)};\n'+fs.readFileSync(worker,'utf8'));
const antItem=(label,input)=>'<div class="ant-form-item"><div class="ant-form-item-label"><label>'+label+'</label></div><div class="ant-form-item-control-wrapper"><div class="ant-form-item-control"><span class="ant-form-item-children">'+input+'</span></div></div></div>';
const antFixture='<title>合成 Ant 申请表</title><fieldset><legend>个人信息</legend>'+antItem('姓名','<input id="antName" placeholder="请填写姓名">')+antItem('联系电话','<input id="antPhone" placeholder="请填写联系电话">')+antItem('性别','<div class="ant-radio-group"><label><input type="radio" value="opaque-male">男</label><label><input type="radio" value="opaque-female">女</label></div>')+'</fieldset>';
const reviewField=(label,input)=>'<div class="form-item form-item--phoenix"><div class="form-item__title"><span class="form-item__text">'+label+'</span></div>'+input+'</div>';
const reviewFixture='<title>合成经历申请表</title><style>body{font:14px sans-serif;padding:50px;background:#f5f6f7}.form-item{margin:18px 0}input,select{display:block;margin-top:8px;padding:8px;min-width:240px}section{margin-bottom:40px}</style><h1>填写经历信息</h1><section><h2>论文/专著</h2><div class="ux-standard-form">'+reviewField('名称','<input class="phoenix-input" value="合成研究论文">')+reviewField('作者','<select id="paperAuthor"><option value="">请选择</option><option value="first">第一作者</option><option value="corresponding">通讯作者</option><option value="other">其他</option></select>')+'</div></section><section><h2>在校职务</h2><div class="ux-standard-form">'+reviewField('在校职务名称','<input class="phoenix-input" value="学习部干事">')+reviewField('在校职务类别','<select id="campusCategory"><option value="">请选择</option><option value="president">主席</option><option value="minister">部长</option><option value="member">其他</option></select>')+'</div></section>';
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');res.end(req.url.startsWith('/review')?reviewFixture:req.url.startsWith('/ant')?antFixture:'<!doctype html><title>合成招聘表单</title><body style="font:16px sans-serif;padding:60px;background:#f5f6f7"><h1>填写申请资料</h1><label>姓名<input id="personName" value="原有姓名" style="display:block;margin-top:16px;padding:10px"></label><label>手机号码<input id="personPhone" style="display:block;margin-top:16px;padding:10px"></label><p>本页仅用于验证浮窗显示与识别，无真实个人资料。</p>');});
let context;
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 context=await playwright.chromium.launchPersistentContext(path.join(temp,'profile'),{channel:'chromium',headless:true,args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`],viewport:{width:1360,height:900}});
 const sw=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker'),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await sw.evaluate(async()=>{await init;await chrome.storage.local.set({toudiPrivateProfile:Core.validatePack({schemaVersion:1,profiles:[{id:'general',label:'示例资料'}],facts:[{key:'person.name',module:'personal',recordId:'person',recordLabel:'基本信息',label:'姓名',value:'示例同学',profiles:['general']},{key:'person.phone',module:'personal',recordId:'person',recordLabel:'基本信息',label:'手机',value:'13800000000',profiles:['general'],sensitive:true}],rules:[]}),toudiFillingPreferences:{profile:'general',agentMode:'external',autoAgent:false}});});
 await page.goto('http://127.0.0.1:'+server.address().port);await page.bringToFront();
 const sourceTab=await sw.evaluate(async()=>{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});return tab.id});
 const clickAction=()=>sw.evaluate(async id=>fixtureAction(await chrome.tabs.get(id)),sourceTab);
 const panel=async()=>{await page.waitForFunction(()=>document.querySelector('#toudi-floating-host'));for(let i=0;i<50;i++){const f=page.frames().find(f=>f.url().startsWith('chrome-extension:'));if(f){await f.locator('#runtimeVersion').filter({hasText:'扩展'}).waitFor();await f.locator('#scanSummary').filter({hasText:'识别到'}).waitFor();return f}await new Promise(r=>setTimeout(r,50))}throw Error('Extension frame did not load')};
 await clickAction();let ui=await panel();const initialBounds=await page.locator('#toudi-floating-host').boundingBox();assert.equal(initialBounds.height,690);assert.equal(await page.locator('#personPhone').inputValue(),'','opening only scans');assert.equal(await ui.title(),'TouDi · 辅助填报');assert(await ui.locator('#fill').isEnabled());
 await ui.locator('#tabLibrary').click();await ui.locator('#copyLibrary').waitFor();await ui.locator('[data-copy-fact="person.name"]').waitFor();assert.equal(await ui.locator('[data-copy-fact="person.name"]').innerText(),'示例同学');assert(await ui.locator('#notice').isHidden());assert.equal(await ui.locator('#tabLibrary').getAttribute('aria-selected'),'true');
 if(process.env.TOUDI_PANEL_EVIDENCE)await page.screenshot({path:path.join(process.env.TOUDI_PANEL_EVIDENCE,'真实扩展_资料标签.png')});
 assert.equal((await page.locator('#toudi-floating-host').boundingBox()).height,initialBounds.height,'library and filling tabs have the same fixed host height');await ui.locator('#tabFill').click();await ui.locator('#fillPane').waitFor();assert(await ui.locator('#copyLibrary').isHidden());assert.equal(await ui.locator('#tabFill').getAttribute('aria-selected'),'true');assert.equal(await ui.locator('#review,[data-record-group]').count(),0);assert.equal(await ui.locator('#fillMode').inputValue(),'all');
 if(process.env.TOUDI_PANEL_EVIDENCE)await page.screenshot({path:path.join(process.env.TOUDI_PANEL_EVIDENCE,'真实扩展_识别标签.png')});
 const previousURL=ui.url();await ui.goto('about:blank');await clickAction();ui=await panel();assert.notEqual(ui.url(),previousURL);assert.equal(await page.locator('#toudi-floating-host').count(),1);assert(await ui.locator('#fill').isEnabled());
 await ui.locator('#tabLibrary').click();await ui.locator('[data-copy-fact="person.name"]').waitFor();
 // Simulate orphan DOM surviving an invalidated content-script context.
 await sw.evaluate(async()=>{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});await chrome.scripting.executeScript({target:{tabId:tab.id},func:()=>{delete globalThis.TouDiPanelHost}})});
 await clickAction();ui=await panel();assert.equal(await page.locator('#toudi-floating-host').count(),1);
 await ui.locator('#fillMode').selectOption('empty');await ui.locator('#fill').click();await ui.locator('#result .finish').waitFor();assert.match(await ui.locator('#result .finish').innerText(),/已填写 1 项/);assert.equal(await page.locator('#personName').inputValue(),'原有姓名');assert.equal(await page.locator('#personPhone').inputValue(),'13800000000');
 assert.equal(await ui.locator('#review,#actions').count(),0);
 await ui.locator('#fillMode').selectOption('all');await ui.locator('#fill').click();await ui.locator('#result .finish').waitFor();assert.match(await ui.locator('#result .finish').innerText(),/已填写 1 项/);assert.equal(await page.locator('#personName').inputValue(),'示例同学');assert.equal(await page.locator('#personPhone').inputValue(),'13800000000');assert.deepEqual(errors,[]);
 // The production worker must also inject the shared adapter on another form.
 await sw.evaluate(async()=>{const {toudiPrivateProfile:p}=await chrome.storage.local.get('toudiPrivateProfile');p.facts.push({key:'person.gender',module:'personal',recordId:'person',recordLabel:'基本信息',label:'性别',value:'女',profiles:['general']});await chrome.storage.local.set({toudiPrivateProfile:Core.validatePack(p)});});
 await page.goto('http://127.0.0.1:'+server.address().port+'/ant');await page.bringToFront();
 // A fixture-only reference lets us reproduce later frame replacement while the
 // production shadow root stays closed and the production host stays unchanged.
 await sw.evaluate(async()=>{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});await chrome.scripting.executeScript({target:{tabId:tab.id},func:()=>{const create=document.createElement.bind(document);document.createElement=function(name,...args){const node=create(name,...args);if(String(name).toLowerCase()==='iframe')globalThis.fixturePanelFrame=node;return node};}})});
 await clickAction();ui=await panel();assert.match(await ui.locator('#runtimeVersion').innerText(),new RegExp(manifest.version.replaceAll('.','\\.')));await ui.locator('#fill').click();await ui.locator('#result .finish').waitFor();assert.match(await ui.locator('#result .finish').innerText(),/已填写 3 项/);assert.equal(await page.locator('#antName').inputValue(),'示例同学');assert.equal(await page.locator('#antPhone').inputValue(),'13800000000');assert.equal(await page.locator('.ant-radio-group input:checked').inputValue(),'opaque-female');assert.deepEqual(errors,[]);
 const failureUI=()=>sw.evaluate(async id=>{return (await chrome.scripting.executeScript({target:{tabId:id},func:()=>{const frame=globalThis.fixturePanelFrame,shell=frame.parentElement,host=document.querySelector('#toudi-floating-host'),status=shell.querySelector('[role="status"]'),fallback=shell.querySelector('.fallback'),minimize=shell.querySelector('.bar button');const rect=n=>{const r=n.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height}};return {text:status?.textContent,height:host?.getBoundingClientRect().height || 0,status:status&&rect(status),fallback:fallback&&rect(fallback),minimize:rect(minimize),srcdoc:frame.getAttribute('srcdoc'),frameDisplay:getComputedStyle(frame).display};}}))[0].result;},sourceTab);
 const windowCount=context.pages().length;
 await sw.evaluate(async()=>{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});await chrome.scripting.executeScript({target:{tabId:tab.id},func:()=>{globalThis.fixturePanelFrame.srcdoc='';}})});
 await page.waitForTimeout(100);let failedUI=await failureUI();assert.match(failedUI.text,/浮窗未能加载/);assert.equal(context.pages().length,windowCount);assert(failedUI.height===690 && failedUI.status.height>0 && failedUI.fallback.height>0);assert.equal(failedUI.srcdoc,'');assert.equal(failedUI.frameDisplay,'none');
 await page.mouse.click(failedUI.minimize.x+13,failedUI.minimize.y+13);failedUI=await failureUI();assert.equal(failedUI.height,38);assert.equal(failedUI.status.height,0);assert.equal(failedUI.fallback.height,0);
 await page.mouse.click(failedUI.minimize.x+13,failedUI.minimize.y+13);failedUI=await failureUI();assert(failedUI.height===690 && failedUI.fallback.height>0);
 await page.mouse.click(failedUI.fallback.x+15,failedUI.fallback.y+12);ui=await panel();assert.equal(context.pages().length,windowCount);assert.equal(await page.locator('#antName').inputValue(),'示例同学');assert.equal((await failureUI()).status.height,0,'Runtime ready acknowledgement clears the error');assert.equal((await page.locator('#toudi-floating-host').boundingBox()).height,690);
 // A first-load failure offers a same-page retry, without opening another window.
 await page.goto('http://127.0.0.1:'+server.address().port+'/ant?first-load');await page.bringToFront();
 await sw.evaluate(async()=>{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});await chrome.scripting.executeScript({target:{tabId:tab.id},func:()=>{let once=true;const create=document.createElement.bind(document);document.createElement=function(name,...args){const node=create(name,...args);if(String(name).toLowerCase()==='iframe'){globalThis.fixturePanelFrame=node;if(once){once=false;node.srcdoc='';}}return node};}})});
 await clickAction();await page.waitForTimeout(100);failedUI=await failureUI();assert.match(failedUI.text,/浮窗未能加载/);assert.equal(context.pages().length,windowCount);
 await page.mouse.click(failedUI.fallback.x+15,failedUI.fallback.y+12);ui=await panel();assert.equal(await ui.locator('#tabFill').getAttribute('aria-selected'),'true');await ui.locator('#fill').click();await ui.locator('#result .finish').filter({hasText:'已填写 3 项'}).waitFor();assert.equal(await page.locator('#antName').inputValue(),'示例同学');assert.equal(await page.locator('.ant-radio-group input:checked').inputValue(),'opaque-female');assert.equal(context.pages().length,windowCount);
 if(process.env.TOUDI_PANEL_EVIDENCE)await page.screenshot({path:path.join(process.env.TOUDI_PANEL_EVIDENCE,'网页内重试_填写与读回.png')});assert.deepEqual(errors,[]);
 // Exercise production polling and result rendering with controlled, synthetic
 // native replies. Nothing in this test touches the user's installed extension.
 await sw.evaluate(async()=>{
  await chrome.storage.local.set({toudiPrivateProfile:Core.validatePack({schemaVersion:1,profiles:[{id:'general',label:'合成资料'}],rules:[],facts:[{key:'title',label:'论文名称',module:'publications',recordId:'paper',recordLabel:'合成研究论文',value:'合成研究论文'},{key:'rank',label:'作者排序',module:'publications',recordId:'paper',recordLabel:'合成研究论文',value:'第五作者'},{key:'post',label:'职务',module:'campus-role',recordId:'campus',recordLabel:'学习部干事',value:'学习部干事'}]}),toudiFillingPreferences:{profile:'general',agentMode:'codex',agentModel:'fixture-model'}});
  globalThis.fixtureDecisions=[];native=request=>new Promise(resolve=>fixtureDecisions.push({request,resolve}));
 });
 await page.goto('http://127.0.0.1:'+server.address().port+'/review');await page.bringToFront();await clickAction();ui=await panel();
 await ui.locator('#reviewAgent').click();await ui.locator('#progress').filter({hasText:'正在核对论文发表（1/2）'}).waitFor();
 assert.equal(await page.locator('#paperAuthor').inputValue(),'','Review remains read-only');assert.equal(await ui.locator('#reviewDetails').isHidden(),true);
 if(process.env.TOUDI_PANEL_EVIDENCE)await page.screenshot({path:path.join(process.env.TOUDI_PANEL_EVIDENCE,'模块核对进度_真实扩展.png')});
 const respond=()=>sw.evaluate(()=>{const {request,resolve}=fixtureDecisions.shift(),field=request.fields[0],factKey=field.module==='publications'?'rank':'post',optionValue=factKey==='rank'?'other':'member';if(request.fields.length!==1 || request.allowedFacts.length!==1)throw Error('Unbounded module request');resolve({mappings:{[field.id]:factKey},provider:{called:true,model:'fixture-model',optionDecisions:{[field.id]:{factKey,optionValue,sourceKeys:[factKey],reason:factKey==='rank'?'第五作者对应其他作者。':'干事不属于主席或部长。'}}}})});
 await respond();await ui.locator('#progress').filter({hasText:'正在核对在校经历（2/2）'}).waitFor();await respond();
 await ui.locator('#reviewResult').filter({hasText:'已匹配 2 项'}).waitFor();await ui.locator('#reviewDetailsSummary').click();assert.equal(await ui.locator('.review-item').count(),2);assert.match(await ui.locator('#reviewItems').innerText(),/作者[\s\S]*选择：其他[\s\S]*第五作者/);assert.match(await ui.locator('#reviewItems').innerText(),/在校职务类别[\s\S]*选择：其他[\s\S]*学习部干事/);
 assert.equal((await page.locator('#toudi-floating-host').boundingBox()).height,690);assert.equal(await ui.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false);
 if(process.env.TOUDI_PANEL_EVIDENCE)await page.screenshot({path:path.join(process.env.TOUDI_PANEL_EVIDENCE,'核对结果_真实扩展.png')});
 await ui.locator('#fill').click();await ui.locator('#result .finish').filter({hasText:'已填写 2 项'}).waitFor();assert.equal(await page.locator('#paperAuthor').inputValue(),'other');assert.equal(await page.locator('#campusCategory').inputValue(),'member');assert.equal(await sw.evaluate(()=>fixtureDecisions.length),0,'Filling never invokes a second model review');assert.deepEqual(errors,[]);
 console.log('PASS real MV3 runtime: fixed same-page panel, scan/review/fill separation, per-module progress, readable guarded option results, library, generic/Ant write/readback, reload/orphan recovery, no new windows and unchanged form');
})().catch(async e=>{console.error(e);if(context)for(const page of context.pages())for(const frame of page.frames())if(frame.url().startsWith('chrome-extension:'))console.error('Runtime failure state:',await frame.evaluate(()=>({notice:document.querySelector('#notice')?.textContent,rows:document.querySelectorAll('#review .field').length,source:document.querySelector('#sourceStatus')?.textContent,result:document.querySelector('#result')?.textContent})).catch(()=>null));process.exitCode=1}).finally(async()=>{await context?.close();server.close();fs.rmSync(temp,{recursive:true,force:true})});
