'use strict';
// Browser plugin not available. All data and runtime state are isolated, synthetic fixtures.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const {spawn}=require('node:child_process'),{once}=require('node:events');
let pw;try{pw=require('playwright')}catch(_){pw=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const root=path.resolve(__dirname,'..'),workspace=fs.mkdtempSync(path.join(os.tmpdir(),'toudi-schedule-'));
const out=process.env.TOUDI_SCHEDULE_EVIDENCE||os.tmpdir(),token=crypto.randomBytes(32).toString('hex');
let service,browser;
const write=(relative,data)=>{const target=path.join(workspace,relative);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,JSON.stringify(data));};
(async()=>{
  fs.mkdirSync(out,{recursive:true});
  const command=process.env.TOUDI_TEST_RUNTIME||'python3',args=process.env.TOUDI_TEST_RUNTIME?['serve']:[path.join(root,'app/desktop_runtime.py'),'serve'];
  service=spawn(command,args,{env:{...process.env,TOUDI_WORKSPACE:workspace,TOUDI_APP_HOME:path.join(workspace,'config'),TOUDI_DESKTOP_TOKEN:token,TOUDI_PORT:'0'},stdio:['pipe','pipe','pipe']});
  let logs='';service.stderr.on('data',chunk=>logs+=chunk);let line='';const signal=await new Promise((resolve,reject)=>{service.stdout.on('data',chunk=>{line+=chunk;const first=line.split('\n')[0];try{resolve(JSON.parse(first));}catch(_){}});service.once('exit',code=>reject(Error('Runtime exited '+code+' '+logs)));});
  const origin='http://127.0.0.1:'+signal.port;
  browser=await pw.chromium.launch({headless:true,executablePath:process.env.TOUDI_CHROMIUM});
  const context=await browser.newContext({viewport:{width:1536,height:1024},extraHTTPHeaders:{Authorization:'Bearer '+token}});
  const page=await context.newPage(),errors=[];page.on('pageerror',error=>{errors.push(error.message);console.error('PAGE ERROR',error.message);});page.on('console',message=>{if(['error','warning'].includes(message.type()))console.error('CONSOLE',message.text());});
  const get=async module=>(await context.request.get(origin+'/api/manage?module='+module)).json();
  const commit=async(module,body)=>{const current=await get(module);const response=await context.request.post(origin+'/api/manage',{data:{module,base:current.version,workspaceKey:current.workspaceKey,...body},headers:{Origin:origin}});assert(response.ok(),await response.text());return response.json();};
  await page.goto(origin+'/投递管理.html');await page.waitForFunction(()=>serverMode&&toudiWorkspaceStorage.id);
  await page.locator('[data-module="schedule"]').click();await page.waitForFunction(()=>document.querySelector('#scheduleCalendar')?.children.length>0);
  assert.equal(await page.title(),'TouDi · 投递中控台');assert(await page.locator('#scheduleCalendar').textContent());
  await page.screenshot({path:path.join(out,'日程_空工作区.png')});
  await commit('records',{action:'replace',data:[{名称:'示例企业A',截止时间:'2026/10/9'},{名称:'示例企业B',截止时间:'2026-11'},{名称:'示例企业C',截止时间:'招满即止'}]});
  await page.waitForFunction(()=>data.length===3,null,{timeout:12000});
  await page.locator('[data-schedule="new"]').first().click();
  await page.locator('#scheduleForm [name="title"]').fill('示例企业A · 面试');
  await page.locator('#scheduleForm [name="type"]').selectOption('interview');
  const date=await page.locator('#scheduleForm [name="date"]').inputValue();
  await page.locator('#scheduleCompanyQuery').fill('示例企业A');
  await page.locator('#scheduleCompanyList [role=option]').filter({hasText:'示例企业A'}).click();
  const meetingInfo='会议号：123 456 789\n入会密码：0123';
  await page.locator('#scheduleForm [name="meetingInfo"]').fill(meetingInfo);
  assert(await page.locator('#scheduleForm').evaluate(form=>form.checkValidity()),'A meeting number is valid form input');
  await page.locator('#scheduleForm [name="notes"]').fill('完整备注：核对岗位职责、整理项目经历。\n保留第二行。');
  await page.locator('#scheduleForm [type="submit"]').click();
  await page.getByText('日程已保存',{exact:true}).waitFor();
  let current=await get('schedule');assert.equal(current.data.events.length,1);const id=current.data.events[0].id;
  assert.equal(current.data.events[0].notes,'完整备注：核对岗位职责、整理项目经历。\n保留第二行。');
  assert.equal(current.data.events[0].meetingInfo,meetingInfo);assert.equal(current.data.events[0].url,'');
  await page.reload();await page.waitForFunction(()=>serverMode);await page.locator('[data-module="schedule"]').click();await page.waitForFunction(()=>document.querySelector('[data-schedule-event]'));
  await page.locator('[data-module="delivery"]').click();await page.locator('[data-module="schedule"]').click();
  await page.waitForFunction(()=>document.querySelector('[data-schedule-event]'));
  await page.evaluate(()=>window.toudiSchedule.show());
  assert(await page.locator('[data-schedule-event="'+id+'"]').count(),'Reopening retains the mounted calendar');
  await page.locator(`[data-schedule-event="${id}"]`).first().click();
  assert.equal(await page.locator('#scheduleForm [name="notes"]').inputValue(),current.data.events[0].notes);
  assert.equal(await page.locator('#scheduleForm [name="meetingInfo"]').inputValue(),meetingInfo);
  await page.screenshot({path:path.join(out,'日程_会议号与入会说明.png')});
  // Old URL-only events open in the same field; changing to a number removes the stale URL.
  const legacyLink='https://example.invalid/join?meeting=123456789';
  await page.locator('#scheduleForm [name="meetingInfo"]').fill(legacyLink);
  await page.locator('#scheduleForm [type="submit"]').click();await page.waitForFunction(()=>!window.toudiSchedule.hasDraft());
  assert.equal((await get('schedule')).data.events[0].url,legacyLink);
  const legacy=(await get('schedule')).data;delete legacy.events[0].meetingInfo;
  await commit('schedule',{action:'replace',data:legacy});
  await page.waitForFunction(()=>!('meetingInfo' in window.toudiSchedule.get().events[0]),null,{timeout:12000});
  await page.locator(`[data-schedule-event="${id}"]`).first().click();
  assert.equal(await page.locator('#scheduleForm [name="meetingInfo"]').inputValue(),legacyLink);
  await page.locator('#scheduleForm [name="meetingInfo"]').fill(meetingInfo);
  await page.locator('#scheduleForm [type="submit"]').click();await page.waitForFunction(()=>!window.toudiSchedule.hasDraft());
  assert.equal((await get('schedule')).data.events[0].url,'');
  await page.evaluate(()=>window.__SNAPSHOT__=true);await page.locator(`[data-schedule-event="${id}"]`).first().click();
  assert((await page.locator('#scheduleInspector .schedule-notes').allTextContents()).includes(meetingInfo));
  assert.equal(await page.locator('#scheduleInspector a.action-link').count(),0,'A meeting number is not a fake clickable URL');
  await page.evaluate(()=>window.__SNAPSHOT__=false);
  await page.locator('[data-schedule="cancel"]').first().click();await page.locator(`[data-schedule-event="${id}"]`).first().click();
  await page.screenshot({path:path.join(out,'日程_周历与编辑.png')});
  const inspector=await page.locator('#scheduleInspector').boundingBox(),canvas=await page.locator('#scheduleCalendar').boundingBox();
  assert(Math.abs(inspector.y-canvas.y)<2);assert(Math.abs(inspector.height-canvas.height)<2);
  await page.locator('[data-schedule="cancel"]').first().click();
  // Exercise the actual drag/resize UI, then read back the persisted dates.
  const beforeDrag=(await get('schedule')).data.events[0];
  const laneWidth=await page.locator('#scheduleCalendar [data-date="'+date+'"]').evaluateAll(nodes=>nodes.filter(node=>node.getBoundingClientRect().height>100).at(-1)?.getBoundingClientRect().width);
  assert(laneWidth>20,'Visible day lane');
  let eventBox=await page.locator('[data-schedule-event="'+id+'"]').first().boundingBox();
  const direction=new Date(date+'T12:00:00Z').getUTCDay()===0?-1:1;
  await page.mouse.move(eventBox.x+eventBox.width/2,eventBox.y+14);await page.mouse.down();await page.mouse.move(eventBox.x+eventBox.width/2+laneWidth*direction,eventBox.y+14,{steps:12});await page.mouse.up();
  await page.waitForFunction(({id,start})=>window.toudiSchedule.get().events.find(row=>row.id===id).start!==start,{id,start:beforeDrag.start});
  const dragged=(await get('schedule')).data.events[0];assert.equal(new Date(dragged.start)-new Date(beforeDrag.start),direction*86400000);
  const eventNode=page.locator('[data-schedule-event="'+id+'"]').first();await eventNode.hover();
  const resizeBox=await eventNode.locator('.fc-Xm').boundingBox();assert(resizeBox,'Visible resize handle');
  await page.mouse.move(resizeBox.x+resizeBox.width/2,resizeBox.y+resizeBox.height/2);await page.mouse.down();await page.mouse.move(resizeBox.x+resizeBox.width/2,resizeBox.y+resizeBox.height/2+36,{steps:12});await page.mouse.up();
  await page.waitForFunction(({id,end})=>window.toudiSchedule.get().events.find(row=>row.id===id).end!==end,{id,end:dragged.end});
  assert(new Date((await get('schedule')).data.events[0].end)>new Date(dragged.end));
  await page.screenshot({path:path.join(out,'日程_拖动改期与拉伸.png')});
  await page.locator('[data-schedule-mode="dayGridMonth"]').click();await page.screenshot({path:path.join(out,'日程_月历.png')});
  const sourceIds=await page.locator('[data-schedule-event^="deadline:"]').evaluateAll(nodes=>nodes.map(node=>node.dataset.scheduleEvent));
  assert(sourceIds.some(key=>key.includes('示例企业A')),'Exact source date is projected');
  assert(sourceIds.every(key=>!key.includes('示例企业B')&&!key.includes('示例企业C')),'No fabricated exact dates');
  await page.locator('[data-schedule-mode="agenda"]').click();await page.locator(`[data-schedule-id="${id}"]`).first().click();
  await page.locator('#scheduleForm [name="scheduled"]').uncheck();await page.locator('#scheduleForm [type="submit"]').click();
  await page.waitForFunction(()=>window.toudiSchedule.get().events[0]?.start===null);
  assert.equal((await get('schedule')).data.events[0].end,null);
  assert(await page.locator('#scheduleAgenda').textContent().then(text=>text.includes('待安排')));
  // Agent updates are received by an open module without restarting the App.
  current=await get('schedule');await commit('schedule',{action:'upsert',item:{...current.data.events[0],title:'Agent 更新的完整事项'}});
  await page.locator('#scheduleAgenda').getByText('Agent 更新的完整事项',{exact:true}).waitFor({timeout:12000});
  await page.locator(`[data-schedule-id="${id}"]`).first().click();await page.locator('#scheduleForm [name="title"]').fill('我的未提交编辑');
  await commit('schedule',{action:'upsert',item:{...(await get('schedule')).data.events[0],title:'外部最新事项'}});
  await page.waitForFunction(()=>workspacePendingUpdates.has('schedule'),null,{timeout:12000});
  assert.equal(await page.locator('#scheduleForm [name="title"]').inputValue(),'我的未提交编辑');
  await page.locator('#scheduleForm [type="submit"]').click();await page.locator('#scheduleFormError').filter({hasText:'冲突'}).waitFor();
  assert.equal((await get('schedule')).data.events[0].title,'外部最新事项');
  await page.locator('[data-schedule="cancel"]').first().click();await page.getByText('外部最新事项',{exact:true}).first().waitFor({timeout:12000});
  // Draft restoration after navigation/reload remains bound to the original version.
  await page.locator(`[data-schedule-id="${id}"]`).first().click();await page.locator('#scheduleForm [name="title"]').fill('可恢复的编辑');
  await page.evaluate(()=>{const draft=listUnsavedDrafts().find(entry=>entry.domain==='schedule').draft;draft.data.form.url=draft.data.form.meetingInfo;delete draft.data.form.meetingInfo;writeDraft('schedule',draft.base,draft.data);});
  await page.reload();await page.waitForFunction(()=>serverMode);await page.locator('[data-module="schedule"]').click();await page.locator('[data-schedule="restore"]').waitFor();
  await page.locator('[data-schedule="restore"]').click();assert.equal(await page.locator('#scheduleForm [name="title"]').inputValue(),'可恢复的编辑');
  assert.equal(await page.locator('#scheduleForm [name="meetingInfo"]').inputValue(),meetingInfo,'A blocked URL-field draft recovers its meeting number');
  await page.locator('#scheduleForm [type="submit"]').click();await page.waitForFunction(()=>!window.toudiSchedule.hasDraft());
  assert.equal(await page.evaluate(()=>listUnsavedDrafts().filter(row=>row.domain==='schedule').length),0);
  // Native sync UI tested with a deterministic bridge; actual EventKit permission is separate.
  await page.evaluate(()=>{window.__scheduleCalls=[];window.toudiDesktop={calendar:async(action,request)=>{window.__scheduleCalls.push({action,request});if(action==='status')return {supported:true,authorization:'fullAccess'};if(action==='calendars')return {supported:true,authorization:'fullAccess',calendars:[{id:'synthetic-calendar',title:'测试日历'}]};return {supported:true,authorization:'fullAccess',results:request.items.map(item=>({id:item.id,ok:true,operation:'updated'}))};}};});
  await page.locator('[data-schedule="connect"]').click();await page.locator('#scheduleNativeCalendar').selectOption('synthetic-calendar');await page.locator('[data-schedule="enable-sync"]').click();
  await page.locator('[data-schedule="cancel"]').first().click();await page.locator(`[data-schedule-id="${id}"]`).first().click();
  await page.locator('#scheduleForm [name="scheduled"]').check();await page.locator('#scheduleForm [name="hasEnd"]').check();await page.locator('#scheduleForm [name="syncToCalendar"]').check();await page.locator('#scheduleForm [type="submit"]').click();
  await page.waitForFunction(()=>window.__scheduleCalls.some(call=>call.action==='sync'&&call.request.items.length===1));
  const call=await page.evaluate(()=>window.__scheduleCalls.filter(call=>call.action==='sync'&&call.request.items.length===1).at(-1));
  assert.equal(call.request.items[0].id,id);assert.equal(call.request.items[0].notes,current.data.events[0].notes);
  assert.equal(call.request.items[0].meetingInfo,meetingInfo);assert.equal(call.request.items[0].url,'');
  const ics=await context.request.get(origin+'/api/schedule.ics');assert(ics.ok());const icsText=(await ics.text()).replace(/\r\n /g,'');assert(icsText.includes('BEGIN:VEVENT'));
  assert(icsText.includes('入会信息：会议号：123 456 789\\n入会密码：0123'));assert(!icsText.includes('\r\nURL:'));
  await page.locator('[data-schedule-mode="agenda"]').click();
  await page.locator('[data-schedule-id="'+id+'"]').first().click();await page.locator('[data-schedule="delete"]').click();
  await page.waitForFunction(()=>window.__scheduleCalls.some(call=>call.action==='sync'&&call.request.items[0]?.status==='cancelled'));
  assert.equal((await get('schedule')).data.events[0].status,'cancelled');
  const cancelledIcs=await context.request.get(origin+'/api/schedule.ics');assert(!(await cancelledIcs.text()).includes('BEGIN:VEVENT'));
  const restore=(await get('schedule')).data.events[0];await commit('schedule',{action:'upsert',item:{...restore,status:'planned'}});await page.waitForFunction(()=>window.toudiSchedule.get().events[0].status==='planned');
  await page.locator('[data-schedule-mode="timeGridWeek"]').click();
  await page.waitForFunction(()=>!workspacePendingUpdates.size);
  await page.evaluate(()=>chooseTheme('dark'));await page.waitForTimeout(2800);await page.screenshot({path:path.join(out,'日程_深色.png')});
  await page.evaluate(()=>chooseTheme('light'));await page.waitForTimeout(2800);await page.setViewportSize({width:1024,height:768});await page.screenshot({path:path.join(out,'日程_紧凑桌面.png')});
  assert.equal(await page.evaluate(()=>document.body.scrollWidth>innerWidth),false);
  assert((await page.locator('#scheduleCalendar').boundingBox()).width>700,'Compact calendar keeps readable day lanes');
  await page.locator('[data-schedule="new"]').first().click();
  assert((await page.locator('#scheduleInspector').boundingBox()).width>=300,'Compact editor opens without squeezing the grid');
  assert((await page.locator('#scheduleCalendar').boundingBox()).width>700);
  await page.locator('[data-schedule="cancel"]').first().click();
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'日程_窄屏.png')});
  assert.equal(await page.evaluate(()=>document.body.scrollWidth>innerWidth),false);
  const withoutCalendar=(await get('schedule')).data;delete withoutCalendar.calendar;
  await commit('schedule',{action:'replace',data:withoutCalendar});
  await page.waitForFunction(()=>window.toudiSchedule.get().calendar.enabled===false);
  assert.equal(await page.locator('#scheduleNotice').isVisible(),false,'Optional connection config defaults safely');
  assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(out,'日程浏览器验收.json'),JSON.stringify({runtime:signal.version,checks:['empty calendar layout','CRUD + readback + reload','meeting ID and multiline instructions saved intact','legacy URL-only records preserved','replacing URL with meeting ID clears stale link','read-only meeting information display','original full notes','shared company association','week/month/list','actual mouse drag and resize persisted','unplanned precision','source date precision','Agent live update','conflict preserves both sides','old URL-field draft recovery','native bridge includes meetingInfo with unchanged notes','cancel keeps tombstone and syncs removal','ICS excludes cancelled items','restore cancelled item through Agent','ICS export retains meeting information without invalid URL','dark mode','compact desktop and narrow viewport'],errors},null,2));
  console.log('PASS '+signal.version+' schedule workflow');
})().catch(async error=>{console.error(error);for(const context of browser?.contexts()||[])for(const page of context.pages()){console.error((await page.locator('body').innerText()).slice(-6000));await page.screenshot({path:path.join(out,'日程_失败排查.png')}).catch(()=>{});}process.exitCode=1}).finally(async()=>{await browser?.close();if(service&&service.exitCode===null){service.stdin.write('shutdown\n');await once(service,'exit');}fs.rmSync(workspace,{recursive:true,force:true});});
