'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),L=require('../app/browser-extension/profile-library.js');
let playwright;try{playwright=require('playwright');}catch(_){playwright=require(process.env.TOUDI_PLAYWRIGHT_MODULE || path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
let pack=L.emptyPack();pack=L.saveRecord(pack,'personal','',{name:'合成姓名',phone:'13900000000'});pack=L.saveRecord(pack,'campus-role','',{organization:'合成学生组织',role:'合成负责人',start:'2023-09',end:'2024-06',tasks:'合成活动组织工作'});pack=L.saveRecord(pack,'awards','',{name:'合成奖项',level:'校级',date:'2024-06'});pack=L.saveRecord(pack,'publications','',{name:'合成论文',venue:'合成刊物',date:'2024-07',order:'第二作者'});pack.profiles.push({id:'alternate',label:'合成另一版本'});pack.facts.push({key:'alternate.skill',label:'专业技能',value:'另一版本专属内容',module:'personal',recordId:'alt',recordLabel:'合成另一版',profiles:['alternate'],aliases:['专业技能']});pack.sourceVersion='fixture-v1';
const records={general:L.copyRecords(pack,'general'),alternate:L.copyRecords(pack,'alternate')},root=path.resolve(__dirname,'../app/browser-extension');let browser;
(async()=>{browser=await playwright.chromium.launch({headless:true,executablePath:process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const context=await browser.newContext(),errors=[];
 await context.route('https://fixture.invalid/**',r=>{const file=path.basename(new URL(r.request().url()).pathname);r.fulfill({body:fs.readFileSync(file==='logo.svg'?path.join(root,'../assets/favicon.svg'):path.join(root,file)),contentType:file.endsWith('.svg')?'image/svg+xml':file.endsWith('.css')?'text/css':file.endsWith('.js')?'application/javascript':'text/html'});});
 await context.addInitScript(({pack,records})=>{const preferences={profile:'general',agentMode:'external',agentModel:'',autoAgent:false};window.fixtureCalls=[];window.fixtureCopied='';Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.fixtureCopied=text}}});window.chrome={runtime:{sendMessage:async message=>{window.fixtureCalls.push(message);if(message.op==='profile-read')return {value:{pack,preferences,sync:{status:'disconnected'}}};if(message.op==='state')return {value:{state:null,profile:{count:pack.facts.length,profiles:pack.profiles.map(p=>({...p,count:pack.facts.filter(f=>f.profiles.includes(p.id)).length}))},preferences,sync:{status:'disconnected'}}};if(message.op==='copy-library')return {value:{profileId:message.profile,sourceVersion:'fixture-v1',records:records[message.profile]}};if(message.op==='preferences'){Object.assign(preferences,message.preferences);return {value:preferences};}if(message.op==='profile-save'){pack=message.pack;pack.sourceVersion='fixture-v2';window.fixtureSaved=pack;return {value:{}};}return {value:{}};}}};},{pack,records});
 const popup=await context.newPage();popup.on('pageerror',e=>errors.push(e.message));await popup.setViewportSize({width:440,height:900});await popup.goto('https://fixture.invalid/popup.html');await popup.locator('#openCopyLibrary').click();await popup.locator('.copy-record summary').click();await popup.locator('[data-copy-fact]').first().click();assert.equal(await popup.evaluate(()=>fixtureCopied),'合成姓名');assert.equal(await popup.evaluate(()=>fixtureCalls.some(c=>c.op==='scan')),false);
 await popup.locator('#copyModule').selectOption('campus-role');await popup.locator('.copy-record summary').click();await popup.locator('[data-copy-record]').click();assert.match(await popup.evaluate(()=>fixtureCopied),/组织名称：合成学生组织\n职务：合成负责人/);assert.match(await popup.evaluate(()=>fixtureCopied),/开始日期：2023-09/);
 for(const m of ['awards','publications']){await popup.locator('#copyModule').selectOption(m);await popup.locator('.copy-record summary').click();assert(await popup.locator('[data-copy-record]').isVisible());}
 assert(await popup.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await popup.evaluate(()=>scrollTo(0,0));await popup.screenshot({path:'/tmp/toudi-profile-copy-popup.png',fullPage:true});
 await popup.locator('#profile').selectOption('alternate');assert(await popup.locator('#copyLibrary').isHidden());await popup.locator('#openCopyLibrary').click();await popup.locator('.copy-record summary').click();assert.match(await popup.locator('#copyRecords').innerText(),/另一版本专属内容/);assert(!(await popup.locator('#copyRecords').innerText()).includes('合成学生组织'));
 const options=await context.newPage();options.on('pageerror',e=>errors.push(e.message));await options.setViewportSize({width:1100,height:900});await options.goto('https://fixture.invalid/options.html');
 for(const m of ['campus-role','awards','publications'])assert(await options.locator(`[data-add-record="${m}"]`).isVisible());
 await options.locator('[data-add-record="campus-role"]').click();await options.locator('#recordField-organization').fill('新增合成组织');await options.locator('#recordField-role').fill('新增合成职务');await options.locator('#recordField-start').fill('2024-09');await options.locator('#recordField-end').fill('2025-06');await options.locator('#recordField-tasks').fill('新增合成职责');await options.locator('#recordForm button[type="submit"]').click();await options.locator('#recordEditor').waitFor({state:'hidden'});assert.equal(await options.evaluate(()=>fixtureSaved.facts.filter(f=>f.module==='campus-role' && f.value==='新增合成组织').length),1);
 const rec=options.locator('.record').filter({has:options.getByText('新增合成组织 · 新增合成职务',{exact:true})});if(!(await rec.evaluate(n=>n.open)))await rec.locator('summary').click();await rec.locator('[data-record-copy]').click();await options.getByText('资料已复制，可自行粘贴。',{exact:true}).waitFor();assert.match(await options.evaluate(()=>fixtureCopied),/职责描述：新增合成职责/);await rec.locator('[data-fact-copy]').first().click();await options.getByText('资料已复制，可自行粘贴。',{exact:true}).waitFor();assert.equal(await options.evaluate(()=>fixtureCopied),'新增合成组织');
 assert(await options.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await options.screenshot({path:'/tmp/toudi-profile-copy-options.png',fullPage:true});assert.deepEqual(errors,[]);
 console.log('PASS rendered profile copy: no scan required, sensitive self-use field copy, labelled record copy, selected-version isolation, 440px layout; all three new templates visible and campus record save/copy works, zero page errors');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close()});
