'use strict';
// Entirely synthetic Phoenix topology, isolated browser profile, no applicant/site data.
const assert=require('node:assert/strict'),path=require('node:path'),os=require('node:os');
let playwright;try{playwright=require('playwright');}catch(_){playwright=require(process.env.TOUDI_PLAYWRIGHT_MODULE || path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const root=path.resolve(__dirname,'../app');
const text=(value='')=>`<input class="phoenix-input" value="${value}">`;
const choice=(key,value='',kind='constant',disabled=false)=>`<div class="phoenix-select${disabled?' phoenix-select--disabled':''}" data-key="${key}" data-kind="${kind}"><div class="phoenix-select__content">${value}</div><input class="phoenix-select__input" readonly></div>`;
const field=(title,control)=>`<div class="form-item form-item--phoenix"><div class="form-item__title"><span class="form-item__text">${title}</span><span class="form-item__required">*</span></div><div class="form-item__content">${control}<p class="error">必填项未填写</p></div></div>`;
const radio=`<div class="phoenix-radio-group">${['男','女'].map(label=>`<div class="phoenix-radio"><span class="phoenix-radio__radio-text">${label}</span></div>`).join('')}</div>`;
const record=(degree,id)=>`<div class="ux-standard-form">${field('学校名称',text('合成学校'+degree))}${field('学历',choice('degree-'+id,degree))}${field('开始日期',choice('start-'+id,'','date'))}${field('GPA',text())}</div>`;
const fixture=`<!doctype html><meta charset="utf-8"><style>body{font:16px sans-serif}input{width:180px;height:26px}.form-item{padding:6px}.phoenix-select,.phoenix-radio,.list-item-container,.area-item-container,.phoenix-button{padding:6px;cursor:pointer}.common-unmodeled-layer{position:fixed;top:0;right:0;width:280px;background:#eee;z-index:100}.error{color:#900}</style><nav><input placeholder="搜索职位"></nav><form><section><h2>个人信息</h2><div class="ux-standard-form">${field('姓名',text('合成已有姓名'))}${field('性别',radio)}${field('最高学历',choice('highest',''))}${field('现居地',choice('city','','area'))}${field('出生日期',choice('birthday','','date'))}${field('锁定字段',choice('locked','硕士','constant',true))}</div></section><section><h2>教育经历</h2>${record('硕士','m')}${record('本科','b')}</section><button type="submit">提交申请</button></form><script>
window.submits=0;window.confirmations=0;window.searches=[];window.calendarEnters=0;window.behavior={};window.optionRows={'highest':['本科','硕士'],'city':['上海市'],'degree-m':['本科','硕士'],'degree-b':['本科','硕士']};
document.querySelector('form').onsubmit=e=>{e.preventDefault();submits++};
function closeLayers(){document.querySelectorAll('.common-unmodeled-layer:not(.fixture-decoy)').forEach(n=>n.remove());document.querySelectorAll('.phoenix-select--active').forEach(n=>n.classList.remove('phoenix-select--active'))}
document.querySelectorAll('.form-item__title').forEach(n=>n.onclick=closeLayers);
document.querySelectorAll('.phoenix-radio').forEach(n=>n.onclick=()=>{n.parentElement.querySelectorAll('.phoenix-radio').forEach(o=>o.classList.remove('phoenix-radio--checked'));n.classList.add('phoenix-radio--checked')});
document.querySelectorAll('.phoenix-select').forEach(select=>select.onclick=()=>{
if(select.classList.contains('phoenix-select--disabled'))return;const key=select.dataset.key,kind=select.dataset.kind,b=behavior[key]||{};select.classList.add('phoenix-select--active');const layer=document.createElement('div');layer.className='common-unmodeled-layer';document.body.append(layer);
if(kind==='date'){layer.innerHTML='<input class="phoenix-calendar-input">';layer.querySelector('input').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();calendarEnters++;if(!b.failRead)select.querySelector('.phoenix-select__content').textContent=e.target.value;closeLayers()}};return;}
const area=kind==='area',rows=optionRows[key]||[],rowClass=area?'area-item-container':'list-item-container',labelClass=area?'area-text-label':'item-text-label';
layer.innerHTML='<div class="'+(area?'area-selector-container':'constant-main-selector-container')+'"><div class="'+(area?'area-search-input':'content-search')+'"><input></div>'+rows.map((v,i)=>'<div class="'+rowClass+(b.disabled?' item--disabled':'')+'"><span class="icon-container">○</span><span class="'+labelClass+'">'+v+'</span></div>').join('')+'</div><div class="'+(area?'area-footer-button':'selector-footer-button')+'"><button type="button" class="phoenix-button">取消</button><button type="button" class="phoenix-button">确定</button></div>';
let picked='';layer.querySelector('input').oninput=e=>searches.push({key,value:e.target.value});
layer.querySelectorAll('.'+rowClass).forEach(row=>{const pick=()=>picked=row.querySelector('.'+labelClass).textContent;if(area){row.onclick=()=>{window.areaDrills=(window.areaDrills||0)+1};row.querySelector('.icon-container').onclick=e=>{e.stopPropagation();pick()}}else row.onclick=pick});
layer.querySelectorAll('.phoenix-button').forEach(button=>button.onclick=()=>{if(button.textContent==='确定'){confirmations++;if(!b.failRead)select.querySelector('.phoenix-select__content').textContent=picked;}closeLayers()});
});
</script>`;
let browser;
(async()=>{
 browser=await playwright.chromium.launch({headless:true,executablePath:process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://fixture.invalid/**',r=>r.fulfill({contentType:'text/html',body:fixture}));await page.goto('https://fixture.invalid/apply?fixture=1');
 for(const file of ['assets/form-adapters.js','assets/form-engine.js','browser-extension/filling-aliases.js','browser-extension/filling-core.js'])await page.addScriptTag({path:path.join(root,file)});
 const scan=()=>page.evaluate(()=>TouDiFormEngine.scan());let s=await scan();const f=(label,hint)=>s.fields.find(f=>f.label===label&&(!hint||f.recordHint===hint));
 assert.equal(s.fields.length,14);assert(s.platforms.some(p=>p.id==='zhiye-phoenix'));assert(!s.fields.some(f=>/必填|合成学校|合成已有姓名|搜索职位/.test(f.label)));assert.equal(f('性别').adapter,'phoenix-radio');assert.equal(f('最高学历').adapter,'phoenix-select');assert.equal(f('出生日期').adapter,'phoenix-date');assert.equal(f('出生日期').dateFormat,'YYYY-MM-DD');assert.equal(f('锁定字段').unsupported,'disabled-or-readonly');assert.equal(f('学校名称','硕士').module,'education');assert.notEqual(f('学校名称','硕士').groupId,f('学校名称','本科').groupId);
 const personal={schemaVersion:1,profiles:[{id:'general',label:'合成资料'}],facts:[{key:'gender',label:'性别',value:'女',module:'personal'},{key:'highest',label:'最高学历',value:'硕士研究生',module:'personal'},{key:'city',label:'现居地',value:'上海市',module:'personal'},{key:'birthday',label:'出生日期',value:'2001-02-03',precision:'day',module:'personal'}],rules:[]};
 const personalPlan=await page.evaluate(({p,s})=>TouDiFillingCore.plan(TouDiFillingCore.profile(TouDiFillingCore.validatePack(p),'general'),s),{p:personal,s});assert.equal(personalPlan.statusCounts.ready,4,'radio, deferred portals and day-precision calendar must form usable local plans');
 const defs=s.fields.map(({id,label,module,groupId})=>({id,label,module,groupId}));await page.evaluate(()=>{document.querySelector('input.phoenix-input').value='合成修改值'});const changed=await scan();assert.deepEqual(changed.fields.map(({id,label,module,groupId})=>({id,label,module,groupId})),defs,'personal input values must not change field IDs or titles');s=changed;
 const action=(target,value,extra={})=>({protocol:1,origin:s.origin,path:s.path,fingerprint:s.fingerprint,actions:[{fieldId:target.id,value,expectedValue:target.value,overwrite:true,...extra}]});const apply=p=>page.evaluate(p=>TouDiFormEngine.apply(p),p);
 let result=await apply(action(f('姓名'),'不应写入',{overwrite:false}));assert.equal(result.results[0].reason,'existing-value');assert.equal((await scan()).fields.find(v=>v.id===f('姓名').id).value,'合成修改值');
 result=await apply(action(f('性别'),'女'));assert.equal(result.summary.verified,1,JSON.stringify(result));s=await scan();assert.equal(f('性别').value,'女');
 await page.evaluate(()=>{const decoy=document.createElement('div');decoy.className='common-unmodeled-layer fixture-decoy';decoy.style.left='0';decoy.style.right='auto';decoy.innerHTML='<div class="constant-main-selector-container"><div class="list-item-container"><span class="item-text-label">硕士</span></div></div>';decoy.onclick=()=>window.decoyClicks=(window.decoyClicks||0)+1;document.body.append(decoy)});
 result=await apply(action(f('最高学历'),'硕士研究生'));assert.equal(result.summary.verified,1,JSON.stringify(result));s=await scan();assert.equal(f('最高学历').value,'硕士');assert((await page.evaluate(()=>searches)).some(v=>v.key==='highest'&&v.value==='硕士'));assert.equal(await page.evaluate(()=>window.decoyClicks||0),0);await page.evaluate(()=>document.querySelector('.fixture-decoy').remove());
 result=await apply(action(f('现居地'),'上海市'));assert.equal(result.summary.verified,1,JSON.stringify(result));s=await scan();assert.equal(f('现居地').value,'上海市');assert.equal(await page.evaluate(()=>window.areaDrills||0),0,'select region icon rather than drilling into it');assert.equal(await page.evaluate(()=>confirmations),2);
 result=await apply(action(f('出生日期'),'2001-02-03'));assert.equal(result.summary.verified,1,JSON.stringify(result));s=await scan();assert.equal(f('出生日期').value,'2001-02-03');assert.equal(await page.evaluate(()=>calendarEnters),1);
 const profile={schemaVersion:1,profiles:[{id:'general',label:'合成资料'}],facts:[{key:'start-m',label:'开始日期',value:'2024-09',precision:'month',module:'education',recordId:'m',recordHint:'硕士'},{key:'gpa-m',label:'GPA',value:'3.8',module:'education',recordId:'m',recordHint:'硕士'},{key:'gpa-b',label:'GPA',value:'3.5',module:'education',recordId:'b',recordHint:'本科'}],rules:[]};
 const plan=await page.evaluate(({p,s})=>TouDiFillingCore.plan(TouDiFillingCore.profile(TouDiFillingCore.validatePack(p),'general'),s),{p:profile,s});assert.equal(plan.rows.find(r=>r.fieldId===f('开始日期','硕士').id).status,'manual','month precision must never invent a day');const gpas=plan.rows.filter(r=>r.label==='GPA');assert(gpas.every(r=>r.status==='ready'));const approved=await page.evaluate(p=>TouDiFillingCore.confirm(p,p.rows.filter(r=>r.label==='GPA').map(r=>r.fieldId)),plan);result=await apply(approved);assert.equal(result.summary.verified,2,JSON.stringify(result));s=await scan();
 result=await apply(action(f('开始日期','硕士'),'2024-09'));assert.equal(result.results[0].reason,'date-precision-required');
 result=await apply(action(f('锁定字段'),'本科'));assert.equal(result.results[0].reason,'disabled-or-readonly');
 const highest=()=>f('最高学历');await page.evaluate(()=>{behavior.highest={disabled:true}});result=await apply(action(highest(),'本科'));assert.equal(result.results[0].reason,'option-disabled');assert.equal((await scan()).fields.find(v=>v.id===highest().id).value,'硕士');
 await page.evaluate(()=>{behavior.highest={};optionRows.highest=['本科','本科','硕士']});s=await scan();result=await apply(action(highest(),'本科'));assert.equal(result.results[0].reason,'option-not-unique');
 await page.evaluate(()=>{optionRows.highest=['硕士']});s=await scan();result=await apply(action(highest(),'本科'));assert.equal(result.results[0].reason,'option-not-found');
 await page.evaluate(()=>{optionRows.highest=['本科','硕士'];behavior.highest={failRead:true}});s=await scan();result=await apply(action(highest(),'本科'));assert.equal(result.results[0].reason,'value-not-retained');assert.equal((await scan()).fields.find(v=>v.id===highest().id).value,'硕士');
 await page.evaluate(()=>{behavior.birthday={failRead:true}});s=await scan();result=await apply(action(f('出生日期'),'2002-03-04'));assert.equal(result.results[0].reason,'date-not-retained');assert.equal((await scan()).fields.find(v=>v.id===f('出生日期').id).value,'2001-02-03');
 await page.evaluate(()=>document.querySelector('.phoenix-radio').classList.add('phoenix-radio--disabled'));s=await scan();result=await apply(action(f('性别'),'男'));assert.equal(result.results[0].reason,'option-disabled');await page.evaluate(()=>{const male=document.querySelector('.phoenix-radio');male.classList.remove('phoenix-radio--disabled');const clone=male.cloneNode(true);clone.dataset.duplicate='true';male.parentElement.append(clone)});s=await scan();result=await apply(action(f('性别'),'男'));assert.equal(result.results[0].reason,'option-not-unique');await page.evaluate(()=>document.querySelector('[data-duplicate]').remove());s=await scan();result=await apply(action(f('性别'),'不存在'));assert.equal(result.results[0].reason,'option-not-found');
 // Real Phoenix variants stay synthetic and use only this isolated fixture browser.
 await page.evaluate(markup=>{
   document.querySelector('form').insertAdjacentHTML('beforeend',markup);
   window.extraSelections=[];window.extraIconClicks=0;window.extraRowClicks=0;
   document.querySelectorAll('[data-extra]').forEach(select=>select.onclick=()=>{
     closeLayers();select.classList.add('phoenix-select--active');const layer=document.createElement('div');layer.className='common-unmodeled-layer';document.body.append(layer);
     const mode=select.dataset.extra;
     if(mode==='single'){
       layer.innerHTML='<div class="phoenix-selectList"><div class="phoenix-selectList__searchWrapper"><input></div><div class="phoenix-selectList__listItem"><span class="phoenix-selectList__singleLabel">全日制</span></div><div class="phoenix-selectList__listItem"><span class="phoenix-selectList__singleLabel">非全日制</span></div></div>';
       layer.querySelector('input').oninput=e=>searches.push({key:'single',value:e.target.value});
       layer.querySelectorAll('.phoenix-selectList__listItem').forEach(row=>row.onclick=()=>{extraSelections.push('single');select.querySelector('.phoenix-select__content').textContent=row.querySelector('span').textContent;closeLayers()});return;
     }
     const area=mode==='region',rows=area?[['张家港市','江苏省 苏州市'],['张家港市','合成省 合成市']]:[['合成单位性质','']];
     layer.innerHTML='<div class="'+(area?'area-selector-container':'constant-main-selector-container')+'"><div class="'+(area?'area-search-input':'content-search')+'"><input></div>'+rows.map(([label,path])=>'<div class="'+(area?'area-item-container':'list-item-container')+'"><span class="icon-container">○</span><span class="'+(area?'area-text-label':'item-text-label')+'">'+label+'</span><span class="area-item-path">'+path+'</span></div>').join('')+'</div><div class="'+(area?'area-footer-button':'selector-footer-button')+'"><button type="button" class="phoenix-button">取消</button><button type="button" class="phoenix-button">确定</button></div>';
     let picked='';layer.querySelector('input').oninput=e=>searches.push({key:mode,value:e.target.value});
     layer.querySelectorAll(area?'.area-item-container':'.list-item-container').forEach(row=>{
       row.onclick=()=>{extraRowClicks++};row.querySelector('.icon-container').onclick=e=>{e.stopPropagation();extraIconClicks++;picked=row.querySelector(area?'.area-text-label':'.item-text-label').textContent;extraSelections.push(row.querySelector('.area-item-path').textContent)};
     });
     layer.querySelectorAll('button').forEach(button=>button.onclick=()=>{if(button.textContent==='确定'){confirmations++;select.querySelector('.phoenix-select__content').textContent=picked}closeLayers()});
   });
   document.querySelector('[data-numeric-score]').addEventListener('input',e=>{e.target.value=Number(e.target.value).toFixed(5)});
   document.querySelector('[data-numeric-id]').addEventListener('input',e=>{e.target.value=Number(e.target.value).toFixed(5)});
 },'<section><h2>个人信息</h2><div class="ux-standard-form">'+field('学历类型',choice('single').replace('data-kind="constant"','data-kind="constant" data-extra="single"'))+field('单位性质',choice('icon').replace('data-kind="constant"','data-kind="constant" data-extra="constant"'))+field('籍贯',choice('region').replace('data-kind="constant"','data-kind="constant" data-extra="region"'))+field('证件号码',text().replace('class="phoenix-input"','class="phoenix-input" data-numeric-id'))+'</div></section><section><h2>语言能力</h2><div class="ux-standard-form">'+field('语言成绩',text().replace('class="phoenix-input"','class="phoenix-input" data-numeric-score'))+'</div></section><section><h2>家庭成员</h2><div class="ux-standard-form">'+field('姓名',text('合成家属'))+'</div></section>');
 s=await scan();const beforeSingle=await page.evaluate(()=>confirmations);
 result=await apply(action(f('学历类型'),'普通全日制'));assert.equal(result.summary.verified,1,JSON.stringify(result));s=await scan();assert.equal(f('学历类型').value,'全日制');assert.equal(await page.evaluate(()=>confirmations),beforeSingle,'selectList single choice commits without footer confirmation');assert((await page.evaluate(()=>searches)).some(v=>v.key==='single'&&v.value==='全日制'));
 result=await apply(action(f('单位性质'),'合成单位性质'));assert.equal(result.summary.verified,1,JSON.stringify(result));assert.equal(await page.evaluate(()=>extraIconClicks),1);assert.equal(await page.evaluate(()=>extraRowClicks),0,'constant row text cannot substitute for radio icon selection');
 s=await scan();result=await apply(action(f('籍贯'),'江苏省苏州市张家港市'));assert.equal(result.summary.verified,1,JSON.stringify(result));assert((await page.evaluate(()=>searches)).some(v=>v.key==='region'&&v.value==='张家港市'));assert.equal(await page.evaluate(()=>extraSelections.at(-1)),'江苏省 苏州市');assert.equal(await page.evaluate(()=>extraRowClicks),0);
 s=await scan();result=await apply(action(f('籍贯'),'江苏省张家港市'));assert.equal(result.summary.verified,1,JSON.stringify(result));assert.equal(await page.evaluate(()=>extraSelections.at(-1)),'江苏省 苏州市','short province/leaf path selects the same uniquely matching hierarchy');
 s=await scan();result=await apply(action(f('籍贯'),'张家港市'));assert.equal(result.results[0].reason,'option-not-unique','leaf alone must not guess between matching regions');
 s=await scan();const family=s.fields.find(field=>field.label==='姓名'&&field.module==='family');assert(family);assert.equal(family.unsupported,'family-member');result=await apply(action(family,'合成本人'));assert.equal(result.results[0].reason,'family-member');assert.equal(await page.evaluate(()=>[...document.querySelectorAll('section')].find(section=>section.querySelector('h2')?.textContent==='家庭成员').querySelector('input').value),'合成家属');
 s=await scan();result=await apply(action(f('语言成绩'),'554'));assert.equal(result.summary.verified,1,JSON.stringify(result));s=await scan();assert.equal(f('语言成绩').value,'554.00000');
 result=await apply(action(f('证件号码'),'554'));assert.equal(result.results[0].reason,'value-not-retained','identifiers must not use score numeric equivalence');
 assert.equal(await page.evaluate(()=>submits),0);assert.deepEqual(errors,[]);console.log('PASS Phoenix synthetic title/value isolation, stable education groups, radio, scoped portal search/confirm and area icon, calendar Enter, month/date precision protection, disabled/duplicate/missing/readback failures, existing-value protection, zero submissions, selectList direct commit, constant icon-only selection, region leaf/path disambiguation, family-member rejection and scoped numeric readback');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close()});
